/**
 * subjects page translations (ar).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  subjects: {
    all: "all",
    subject: "subject",
    noSubjects: "no Subjects"
  }
};
