/**
 * subjects page translations (ps).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  subjects: {
    all: "ټول",
    subject: "مضمون",
    noSubjects: "مضامین نشته"
  }
};
