/**
 * dashboard page translations (ar).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  dashboard: {
    activeClasses: "الفصول النشطة",
    activeStaff: "Assets Dashboard",
    activeStudents: "Assets Dashboard",
    addStudent: "إضافة طالب",
    availableRooms: "Assets Dashboard",
    buildings: "Assets Dashboard",
    genderDistribution: "Assets Dashboard",
    markAttendance: "تسجيل الحضور",
    overview: "Assets Dashboard",
    quickActions: "إجراءات سريعة",
    schoolBuildings: "Assets Dashboard",
    title: "لوحة التحكم",
    totalBuildings: "Assets Dashboard",
    totalClasses: "Assets Dashboard",
    totalStaff: "إجمالي الموظفين",
    viewReports: "عرض التقارير",
    viewTabsForDetails: "Assets Dashboard",
    welcomeBack: "Assets Dashboard",
    welcomeMessage: "Assets Dashboard"
  }
};
