/**
 * dashboard page translations (ps).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  dashboard: {
    activeClasses: "فعال ټولګي",
    activeStaff: "فعال کارمندان",
    activeStudents: "فعال زده کونکي",
    addStudent: "زده کوونکی اضافه کړئ",
    availableRooms: "موجود اتاقونه",
    buildings: "تعمیرات/ ودانی",
    genderDistribution: "د جنس په اساس توزیع",
    markAttendance: "حاضري واخلئ ",
    overview: "نمایش",
    quickActions: "چټکې کړنې",
    schoolBuildings: "د ښوونځي تعمیرات",
    title: "ډشبورډ",
    totalBuildings: "ټول تعمیرات",
    totalClasses: "ټول صنفونه",
    totalStaff: "ټول کارکوونکي",
    viewReports: "راپورونه وګورئ",
    viewTabsForDetails: "د مالي چارو، شتمنیو، کتابتون، حاضرۍ، رخصتیو او اسنادو د لیدلو لپاره نور ټبونه (بټنې) وګورئ.",
    welcomeBack: "بېرته ښه راغلاست",
    welcomeMessage: "نن مو په جامعه/ ښوونځي کې څه پیشيږي"
  }
};
