/**
 * dashboard page translations (fa).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  dashboard: {
    activeClasses: "صنف‌های فعال",
    activeStaff: "کارمندان برحال",
    activeStudents: "شاگردان برحال",
    addStudent: "افزودن شاگرد",
    availableRooms: "اتاق‌های موجود",
    buildings: "ساختمان‌ها",
    genderDistribution: "توزیع جنسیت",
    markAttendance: "ثبت حاضری",
    overview: "نمای کلی",
    quickActions: "اقدامات سریع",
    schoolBuildings: "ساختمان‌های مکتب",
    title: "داشبورد",
    totalBuildings: "مجموع ساختمان‌ها",
    totalClasses: "مجموع صنف‌ها",
    totalStaff: "مجموع کارمندان",
    viewReports: "مشاهده گزارش‌ها",
    viewTabsForDetails: "مشاهده تب‌ها برای جزئیات مالی، دارایی‌ها، کتابخانه، حاضری، درخواست‌های رخصتی و اسناد",
    welcomeBack: "خوش آمدید",
    welcomeMessage: "آنچه امروز در مکتب شما می‌گذرد"
  }
};
