/**
 * dashboard page translations (en).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  dashboard: {
    activeClasses: "Active Classes",
    activeStaff: "Active Staff",
    activeStudents: "Active Students",
    addStudent: "Add Student",
    availableRooms: "Available Rooms",
    buildings: "Buildings",
    genderDistribution: "Gender Distribution",
    markAttendance: "Mark Attendance",
    overview: "Overview",
    quickActions: "Quick Actions",
    schoolBuildings: "School Buildings",
    title: "Dashboard",
    totalBuildings: "Total Buildings",
    totalClasses: "Total Classes",
    totalStaff: "Total Staff",
    viewReports: "View Reports",
    viewTabsForDetails: "View other tabs for Finance, Assets, Library, Attendance, Leave Requests, and Documents",
    welcomeBack: "Welcome Back",
    welcomeMessage: "Here's what's happening in your school today"
  }
};
