/**
 * activity-logs page translations (ar).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  activityLogs: {
    title: "سجلات النشاط",
    description: "عرض وتصفية جميع سجلات نشاط النظام."
  }
};
