/**
 * activity-logs page translations (fa).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  activityLogs: {
    title: "لاگ‌های فعالیت",
    description: "مشاهده تاریخچه فعالیت‌های سیستم",
    filters: {
      searchPlaceholder: "جستجو بر اساس توضیحات، کاربر...",
      user: "کاربر",
      action: "عملیات",
      entity: "نوع موجودیت",
      dateFrom: "از تاریخ",
      dateTo: "تا تاریخ"
    },
    table: {
      user: "کاربر",
      action: "عملیات",
      entity: "موجودیت",
      description: "توضیحات",
      date: "تاریخ و زمان",
      ipAddress: "آدرس IP",
      properties: "جزئیات"
    },
    actions: {
      created: "ایجاد شد",
      updated: "به‌روز شد",
      deleted: "حذف شد",
      restored: "بازیابی شد",
      login: "ورود",
      logout: "خروج",
      viewed: "مشاهده شد",
      exported: "خروجی گرفته شد"
    },
    noLogs: "هیچ لاگ فعالیتی یافت نشد",
    loadMore: "بارگذاری بیشتر",
    exportPdf: "خروجی PDF",
    exportExcel: "خروجی Excel"
  }
};
