/**
 * activity-logs page translations (ps).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  activityLogs: {
    title: "د فعالیتونو لاګونه",
    description: "د سیسټم فعالیت تاریخ وګورئ",
    filters: {
      searchPlaceholder: "د تفصیل، کارونکي په واسطه ولټوئ...",
      user: "کارونکی",
      action: "عمل",
      entity: "د موضوع ډول",
      dateFrom: "له نیټې",
      dateTo: "تر نیټې"
    },
    table: {
      user: "کارونکی",
      action: "عمل",
      entity: "موضوع",
      description: "تفصیل",
      date: "نیټه او وخت",
      ipAddress: "IP پته",
      properties: "جزئیات"
    },
    actions: {
      created: "جوړ شو",
      updated: "تازه شو",
      deleted: "حذف شو",
      restored: "بیرته راوستل شو",
      login: "ننوتل",
      logout: "وتل",
      viewed: "لیدل شو",
      exported: "صادر شو"
    },
    noLogs: "هیڅ فعالیت لاګونه ونه موندل شول",
    loadMore: "نور ولوستل",
    exportPdf: "PDF صادرول",
    exportExcel: "Excel صادرول"
  }
};
