/**
 * website-admin page translations (fa).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  websiteAdmin: {
    common: {
      filters: "فیلترها",
      search: "جستجو",
      status: "وضعیت",
      publishedAt: "تاریخ نشر",
      expiresAt: "تاریخ انقضا",
      actions: "اقدامات",
      title: "عنوان",
      slug: "اسلاگ",
      excerpt: "چکیده",
      content: "محتوا",
      description: "توضیحات",
      category: "دسته‌بندی",
      type: "نوع",
      visible: "قابل نمایش",
      order: "ترتیب",
      url: "URL",
      parent: "والد",
      created: "ایجاد شده",
      preview: "پیش‌نمایش",
      fileName: "نام فایل",
      altText: "متن جایگزین",
      public: "عمومی",
      yes: "بله",
      no: "خیر",
      all: "همه",
      none: "هیچ",
      notSet: "تنظیم نشده",
      sortOrder: "ترتیب",
      uploading: "در حال بارگذاری..."
    },
    statuses: {
      draft: "پیش‌نویس",
      scheduled: "زمان‌بندی‌شده",
      published: "منتشر شده",
      archived: "بایگانی‌شده",
      assigned: "محول‌شده",
      answered: "پاسخ‌داده‌شده",
      active: "فعال",
      inactive: "غیرفعال",
      pending: "در انتظار",
      verified: "تأیید شده",
      unverified: "تأیید نشده",
      expired: "منقضی"
    },
    announcements: {
      title: "اعلانات",
      description: "اعلانات وب‌سایت را مدیریت کنید",
      new: "اعلان جدید",
      searchPlaceholder: "جستجوی اعلانات...",
      pinned: "سنجاق شده",
      pinToHomepage: "به صفحه اصلی سنجاق کنید",
      noResults: "اعلانی پیدا نشد",
      createTitle: "ایجاد اعلان",
      createDescription: "یک اعلان جدید ایجاد کنید",
      editTitle: "ویرایش اعلان",
      editDescription: "جزئیات اعلان را به‌روز کنید",
      deleteTitle: "حذف اعلان",
      deleteDescription: "آیا مطمئن هستید که این اعلان را حذف می‌کنید؟ این عمل برگشت‌پذیر نیست.",
      fields: {
        title: "عنوان",
        content: "محتوا",
        status: "وضعیت",
        publishedAt: "تاریخ نشر",
        expiresAt: "تاریخ انقضا"
      },
      placeholders: {
        title: "عنوان اعلان",
        content: "محتوای اعلان..."
      }
    },
    articles: {
      title: "مقالات و بلاگ",
      description: "پست‌های بلاگ و مقالات را مدیریت کنید",
      new: "مقاله جدید",
      searchPlaceholder: "جستجوی مقالات...",
      noResults: "مقاله‌ای پیدا نشد",
      createTitle: "ایجاد مقاله",
      createDescription: "یک پست بلاگ یا مقاله جدید ایجاد کنید",
      editTitle: "ویرایش مقاله",
      editDescription: "جزئیات مقاله را به‌روز کنید",
      deleteTitle: "حذف مقاله",
      deleteDescription: "آیا مطمئن هستید که این مقاله را حذف می‌کنید؟ این عمل برگشت‌پذیر نیست.",
      fields: {
        slug: "اسلاگ",
        title: "عنوان",
        excerpt: "چکیده",
        content: "محتوای مقاله",
        status: "وضعیت",
        publishedAt: "تاریخ نشر"
      },
      placeholders: {
        slug: "my-article",
        title: "عنوان مقاله",
        excerpt: "خلاصه کوتاه مقاله...",
        content: "مقاله خود را بنویسید..."
      }
    },
    pages: {
      title: "صفحات",
      description: "صفحات وب‌سایت را مدیریت کنید",
      new: "صفحه جدید",
      searchPlaceholder: "جستجوی صفحات...",
      noResults: "صفحه‌ای پیدا نشد",
      createTitle: "ایجاد صفحه",
      createDescription: "یک صفحه جدید وب‌سایت ایجاد کنید",
      editTitle: "ویرایش صفحه",
      editDescription: "جزئیات صفحه را به‌روز کنید",
      deleteTitle: "حذف صفحه",
      deleteDescription: "آیا مطمئن هستید که این صفحه را حذف می‌کنید؟ این عمل برگشت‌پذیر نیست.",
      fields: {
        slug: "اسلاگ",
        title: "عنوان",
        status: "وضعیت",
        publishedAt: "تاریخ نشر",
        content: "محتوا"
      },
      placeholders: {
        slug: "about-us",
        title: "درباره ما"
      }
    },
    navigation: {
      title: "ناوبری",
      description: "منوی سرصفحه و پاصفحه را مدیریت کنید",
      new: "آیتم منو جدید",
      searchPlaceholder: "جستجوی آیتم‌های منو...",
      noResults: "آیتم منویی پیدا نشد",
      createTitle: "ایجاد آیتم منو",
      createDescription: "یک آیتم منو جدید اضافه کنید",
      editTitle: "ویرایش آیتم منو",
      editDescription: "جزئیات آیتم منو را به‌روز کنید",
      deleteTitle: "حذف آیتم منو",
      deleteDescription: "آیا مطمئن هستید که این آیتم منو را حذف می‌کنید؟ این عمل برگشت‌پذیر نیست.",
      fields: {
        label: "برچسب",
        url: "URL",
        parentMenu: "منوی والد",
        sortOrder: "ترتیب",
        visible: "قابل نمایش",
        linkToPage: "لینک به صفحه (اختیاری)",
        order: "ترتیب"
      },
      placeholders: {
        selectPage: "یک صفحه را انتخاب کنید...",
        label: "خانه",
        url: "/home",
        parentNone: "هیچ (سطح بالا)"
      }
    },
    events: {
      title: "رویدادها",
      description: "تقویم رویدادهای وب‌سایت را مدیریت کنید",
      new: "رویداد جدید",
      searchPlaceholder: "جستجوی رویدادها...",
      noResults: "رویدادی پیدا نشد",
      createTitle: "ایجاد رویداد",
      createDescription: "یک رویداد جدید ایجاد کنید",
      editTitle: "ویرایش رویداد",
      editDescription: "جزئیات رویداد را به‌روز کنید",
      deleteTitle: "حذف رویداد",
      deleteDescription: "آیا مطمئن هستید که این رویداد را حذف می‌کنید؟ این عمل برگشت‌پذیر نیست.",
      fields: {
        title: "عنوان",
        location: "موقعیت",
        startsAt: "شروع",
        endsAt: "پایان",
        summary: "خلاصه",
        publicEvent: "رویداد عمومی"
      },
      placeholders: {
        title: "عنوان رویداد",
        location: "مکان رویداد",
        summary: "خلاصه رویداد..."
      }
    },
    domains: {
      title: "دامنه‌ها",
      description: "دامنه‌های وب‌سایت را مدیریت کنید",
      new: "افزودن دامنه",
      searchPlaceholder: "جستجوی دامنه‌ها...",
      noResults: "دامنه‌ای پیدا نشد",
      createTitle: "افزودن دامنه",
      createDescription: "یک دامنه جدید اضافه کنید",
      editTitle: "ویرایش دامنه",
      editDescription: "جزئیات دامنه را به‌روز کنید",
      deleteTitle: "حذف دامنه",
      deleteDescription: "آیا مطمئن هستید که این دامنه را حذف می‌کنید؟ این عمل برگشت‌پذیر نیست.",
      fields: {
        domain: "دامنه",
        primary: "دامنه اصلی",
        verificationStatus: "وضعیت تأیید",
        sslStatus: "وضعیت SSL"
      },
      placeholders: {
        domain: "example.com",
        selectStatus: "انتخاب وضعیت"
      }
    },
    media: {
      title: "رسانه",
      description: "کتابخانه رسانه وب‌سایت را مدیریت کنید",
      new: "بارگذاری رسانه",
      searchPlaceholder: "جستجوی رسانه...",
      noResults: "رسانه‌ای پیدا نشد",
      createTitle: "افزودن رسانه",
      createDescription: "یک آیتم رسانه جدید به کتابخانه اضافه کنید",
      editTitle: "ویرایش رسانه",
      editDescription: "جزئیات رسانه را به‌روز کنید",
      deleteTitle: "حذف رسانه",
      deleteDescription: "آیا مطمئن هستید که این آیتم رسانه را حذف می‌کنید؟ این عمل برگشت‌پذیر نیست.",
      previewAlt: "پیش‌نمایش رسانه",
      libraryPickerTitle: "از کتابخانه انتخاب کنید",
      libraryPickerDescription: "یک تصویر موجود را انتخاب کنید",
      noLibraryImages: "هیچ تصویری در کتابخانه نیست. ابتدا بارگذاری کنید.",
      fields: {
        type: "نوع",
        category: "دسته‌بندی",
        filePath: "مسیر فایل",
        fileName: "عنوان / نام فایل",
        altText: "متن جایگزین / توضیح"
      },
      placeholders: {
        search: "جستجوی رسانه...",
        selectCategory: "انتخاب دسته‌بندی",
        imageUrl: "https://... یا مسیر",
        videoUrl: "https://www.youtube.com/watch?v=...",
        documentUrl: "https://...",
        fileName: "عکس عالی من",
        altText: "توضیح کوتاه محتوا"
      },
      helpers: {
        uploadOrSelect: "بارگذاری یا انتخاب تصویر",
        uploadHint: "بارگذاری (یک یا چند)",
        imageUrlHint: "URL یا مسیر تصویر (یا از بالا بارگذاری/کتابخانه استفاده کنید)",
        videoHint: "از YouTube، Vimeo یا لینک مستقیم MP4 پشتیبانی می‌شود.",
        categoryAppliesToAll: "{count} تصویر آماده است — دسته‌بندی/متن جایگزین زیر برای همه اعمال می‌شود"
      },
      types: {
        image: "تصویر",
        video: "ویدیو (YouTube/لینک)",
        document: "سند"
      },
      uncategorized: "بدون دسته‌بندی",
      selectFromLibrary: "از کتابخانه انتخاب کنید",
      addFromLibrary: "از کتابخانه انتخاب کنید"
    },
    fatwas: {
      title: "پرسش‌ها و فتواها",
      description: "فتواها، دسته‌بندی‌ها و پرسش‌ها را مدیریت کنید",
      editTitle: "ویرایش فتوا",
      editDescription: "جزئیات فتوا را به‌روز کنید",
      editCategoryTitle: "ویرایش دسته‌بندی",
      editCategoryDescription: "جزئیات دسته‌بندی را به‌روز کنید",
      tabs: {
        fatwas: "فتواها",
        categories: "دسته‌بندی‌ها",
        questions: "پرسش‌ها"
      },
      newFatwa: "فتوا جدید",
      newCategory: "دسته‌بندی جدید",
      anonymous: "ناشناس",
      noFatwas: "فتوایی پیدا نشد",
      noCategories: "دسته‌بندی‌ای پیدا نشد",
      noQuestions: "پرسشی پیدا نشد",
      searchFatwas: "جستجوی فتواها...",
      searchQuestions: "جستجوی پرسش‌ها...",
      fields: {
        slug: "اسلاگ",
        title: "عنوان",
        category: "دسته‌بندی",
        question: "پرسش",
        answer: "پاسخ",
        status: "وضعیت",
        featured: "ویژه",
        publishedAt: "تاریخ نشر",
        name: "نام",
        description: "توضیحات",
        sortOrder: "ترتیب",
        active: "فعال",
        assignedTo: "محول به",
        internalNotes: "یادداشت‌های داخلی",
        answerDraft: "پیش‌نویس پاسخ"
      },
      placeholders: {
        slug: "fatwa-slug",
        title: "عنوان فتوا",
        question: "متن پرسش...",
        answer: "پاسخ فتوا...",
        categorySlug: "category-slug",
        categoryName: "نام دسته‌بندی",
        categoryDescription: "توضیح دسته‌بندی...",
        assignedTo: "شناسه کاربر یا ایمیل",
        internalNotes: "یادداشت‌های داخلی برای بررسی...",
        answerDraft: "پیش‌نویس پاسخ...",
        selectCategory: "انتخاب دسته‌بندی"
      },
      moderation: {
        title: "بررسی پرسش",
        description: "وضعیت و تخصیص پرسش را به‌روز کنید",
        submittedBy: "ارسال شده توسط",
        questionLabel: "پرسش"
      },
      delete: {
        titleFatwa: "حذف فتوا",
        titleCategory: "حذف دسته‌بندی",
        descriptionFatwa: "آیا مطمئن هستید که این فتوا را حذف می‌کنید؟ این عمل برگشت‌پذیر نیست.",
        descriptionCategory: "آیا مطمئن هستید که این دسته‌بندی را حذف می‌کنید؟ این عمل برگشت‌پذیر نیست."
      }
    },
    gallery: {
      title: "دسته‌بندی‌های گالری",
      description: "دسته‌بندی‌ها و آلبوم‌های گالری را مدیریت کنید",
      new: "دسته‌بندی جدید",
      searchPlaceholder: "جستجوی دسته‌بندی‌ها...",
      noResults: "دسته‌بندی‌ای پیدا نشد",
      slugLabel: "اسلاگ",
      sortLabel: "ترتیب",
      noDescription: "بدون توضیح",
      createTitle: "ایجاد دسته‌بندی گالری",
      createDescription: "یک دسته‌بندی جدید گالری اضافه کنید",
      editTitle: "ویرایش دسته‌بندی گالری",
      editDescription: "جزئیات دسته‌بندی گالری را به‌روز کنید",
      deleteTitle: "حذف دسته‌بندی گالری",
      deleteDescription: "آیا مطمئن هستید که این دسته‌بندی را حذف می‌کنید؟ این عمل برگشت‌پذیر نیست.",
      fields: {
        name: "نام",
        coverImage: "تصویر کاور"
      },
      placeholders: {
        name: "نام دسته‌بندی",
        slug: "gallery-category",
        coverPath: "مسیر یا URL تصویر"
      },
      coverUploadCta: "تصویر کاور را بارگذاری یا از کتابخانه انتخاب کنید",
      coverPreviewAlt: "پیش‌نمایش کاور گالری"
    },
    courses: {
      title: "کورس‌ها",
      description: "کورس‌های عمومی را مدیریت کنید",
      new: "کورس جدید",
      searchPlaceholder: "جستجوی کورس‌ها...",
      noResults: "کورسی پیدا نشد",
      createTitle: "ایجاد کورس",
      createDescription: "یک کورس جدید اضافه کنید",
      editTitle: "ویرایش کورس",
      editDescription: "جزئیات کورس را به‌روز کنید",
      deleteTitle: "حذف کورس",
      deleteDescription: "آیا مطمئن هستید که این کورس را حذف می‌کنید؟ این عمل برگشت‌پذیر نیست.",
      fields: {
        title: "عنوان",
        instructor: "استاد",
        duration: "مدت",
        level: "سطح",
        enrollmentLink: "لینک ثبت‌نام",
        coverImage: "تصویر کاور"
      },
      placeholders: {
        title: "عنوان کورس",
        instructor: "نام استاد",
        duration: "مثلاً ۸ هفته",
        level: "انتخاب سطح",
        enrollmentLink: "https://...",
        description: "توضیحات کورس...",
        category: "دسته‌بندی"
      },
      levels: {
        beginner: "مبتدی",
        intermediate: "متوسط",
        advanced: "پیشرفته"
      },
      featured: "ویژه",
      uploadImage: "بارگذاری کاور",
      coverPreviewAlt: "پیش‌نمایش کاور کورس",
      noImage: "تصویر کاور ندارد",
      enrollmentHelp: "لینک ثبت‌نام را وارد کنید یا خالی بگذارید تا دکمه پنهان شود"
    },
    library: {
      title: "کتابخانه",
      description: "کتاب‌های عمومی را مدیریت کنید",
      new: "کتاب جدید",
      searchPlaceholder: "جستجوی کتاب‌ها...",
      noResults: "کتابی پیدا نشد",
      createTitle: "افزودن کتاب",
      createDescription: "یک کتاب جدید به کتابخانه اضافه کنید",
      editTitle: "ویرایش کتاب",
      editDescription: "جزئیات کتاب را به‌روز کنید",
      deleteTitle: "حذف کتاب",
      deleteDescription: "آیا مطمئن هستید که این کتاب را حذف می‌کنید؟ این عمل برگشت‌پذیر نیست.",
      fields: {
        title: "عنوان",
        author: "نویسنده",
        coverImage: "تصویر کاور",
        file: "فایل PDF",
        downloads: "دانلودها"
      },
      placeholders: {
        title: "عنوان کتاب",
        author: "نام نویسنده",
        category: "دسته‌بندی",
        description: "خلاصه کتاب...",
        fileUrl: "https://...pdf"
      },
      uploadCover: "بارگذاری کاور",
      uploadFile: "بارگذاری فایل",
      featured: "ویژه در صفحه اصلی",
      coverPreviewAlt: "پیش‌نمایش کاور کتاب"
    },
    donations: {
      title: "کمک‌ها",
      description: "کمپاین‌های کمک عمومی را مدیریت کنید",
      new: "کمپاین جدید",
      searchPlaceholder: "جستجوی کمپاین‌ها...",
      noResults: "کمپاینی پیدا نشد",
      createTitle: "ایجاد کمپاین",
      createDescription: "یک کمپاین کمک جدید ایجاد کنید",
      editTitle: "ویرایش کمپاین",
      editDescription: "جزئیات کمپاین را به‌روز کنید",
      deleteTitle: "حذف کمپاین",
      deleteDescription: "آیا مطمئن هستید که این کمپاین را حذف می‌کنید؟ این عمل برگشت‌پذیر نیست.",
      fields: {
        fundName: "نام صندوق",
        target: "مبلغ هدف",
        raised: "جمع‌آوری‌شده",
        progress: "پیشرفت",
        active: "فعال"
      },
      placeholders: {
        fundName: "نام صندوق",
        target: "10000",
        raised: "2500",
        description: "توضیحات کمپاین..."
      }
    },
    scholars: {
      title: "علما",
      description: "فهرست علما را مدیریت کنید",
      new: "عالم جدید",
      searchPlaceholder: "جستجوی علما...",
      noResults: "عالمی پیدا نشد",
      createTitle: "افزودن عالم",
      createDescription: "پروفایل عالم را اضافه کنید",
      editTitle: "ویرایش عالم",
      editDescription: "پروفایل عالم را به‌روز کنید",
      deleteTitle: "حذف عالم",
      deleteDescription: "آیا مطمئن هستید که این عالم را حذف می‌کنید؟ این عمل برگشت‌پذیر نیست.",
      fields: {
        name: "نام",
        title: "عنوان",
        email: "ایمیل",
        bio: "زندگی‌نامه",
        photo: "عکس"
      },
      placeholders: {
        name: "نام کامل",
        title: "عنوان یا نقش",
        email: "name@example.com",
        bio: "زندگی‌نامه کوتاه..."
      },
      featured: "ویژه در صفحه اصلی",
      photoAfterCreate: "عکس پس از ایجاد عالم بارگذاری می‌شود.",
      uploadPhoto: "بارگذاری عکس"
    },
    graduates: {
      title: "فارغان و فارغ‌التحصیلان",
      description: "دوره‌های فراغت و فارغان را نمایش دهید",
      new: "فارغ جدید",
      searchPlaceholder: "جستجوی فارغان...",
      noResults: "فارغی پیدا نشد",
      createTitle: "افزودن فارغ",
      createDescription: "یک فارغ جدید به نمایش فارغان اضافه کنید",
      editTitle: "ویرایش فارغ",
      editDescription: "جزئیات فارغ را به‌روز کنید",
      deleteTitle: "حذف فارغ",
      deleteDescription: "آیا مطمئن هستید که این فارغ را حذف می‌کنید؟",
      fields: {
        name: "نام",
        program: "برنامه / مدرک",
        year: "سال فراغت",
        bio: "زندگی‌نامه"
      },
      placeholders: {
        name: "نام کامل",
        program: "مثلاً مطالعات اسلامی",
        year: "2024",
        bio: "زندگی‌نامه کوتاه..."
      },
      featured: "ویژه در صفحه اصلی"
    },
    admissions: {
      title: "ثبت‌نام آنلاین",
      description: "درخواست‌های ثبت‌نام آنلاین را بررسی و مدیریت کنید.",
      tabs: {
        applications: "درخواست‌ها",
        fields: "فیلدهای فورم"
      },
      allStatuses: "همه وضعیت‌ها",
      searchPlaceholder: "جستجو بر اساس نام، تلفن سرپرست، یا شماره درخواست",
      applicationsTitle: "درخواست‌ها",
      fieldsTitle: "فیلدهای فورم",
      columns: {
        applicationNo: "شماره درخواست",
        student: "شاگرد",
        guardianPhone: "تلفن سرپرست",
        applyingGrade: "صنف درخواستی",
        submitted: "ثبت شده"
      },
      fieldColumns: {
        key: "کلید",
        label: "برچسب",
        type: "نوع",
        required: "اجباری",
        enabled: "فعال",
        sort: "ترتیب"
      },
      loading: "درخواست‌ها در حال بارگذاری...",
      noResults: "درخواستی پیدا نشد.",
      actions: {
        view: "مشاهده",
        addField: "افزودن فیلد",
        accept: "قبول و ایجاد شاگرد",
        saveChanges: "ذخیره تغییرات",
        confirmAcceptance: "تأیید پذیرش",
        editField: "ویرایش فیلد",
        newField: "فیلد جدید",
        saveField: "ذخیره فیلد"
      },
      noFields: "هیچ فیلد سفارشی تنظیم نشده است.",
      detailsTitle: "جزئیات درخواست",
      detailsDescription: "این درخواست ثبت‌نام آنلاین را مشاهده و مدیریت کنید.",
      loadingSingle: "درخواست در حال بارگذاری...",
      sections: {
        student: "شاگرد",
        guardian: "سرپرست",
        address: "آدرس",
        previousSchool: "مکتب قبلی",
        statusActions: "وضعیت و اقدامات",
        documents: "اسناد",
        extraFields: "فیلدهای اضافی"
      },
      labels: {
        father: "پدر",
        applying: "درخواست",
        guardian: "سرپرست",
        origin: "اصلی",
        current: "فعلی",
        grade: "صنف",
        year: "سال",
        notes: "یادداشت‌ها",
        internalNotes: "یادداشت‌های داخلی",
        rejectionReason: "دلیل رد",
        field: "فیلد",
        download: "دانلود",
        admissionNoOptional: "شماره ثبت‌نام (اختیاری)",
        admissionYearOptional: "سال ثبت‌نام (اختیاری)"
      },
      selectStatus: "انتخاب وضعیت",
      placeholders: {
        internalNotes: "یادداشت‌های داخلی...",
        rejectionReason: "دلیل رد..."
      },
      noDocuments: "هیچ سندی بارگذاری نشده است.",
      noExtraFields: "هیچ فیلد اضافی پر نشده است.",
      acceptTitle: "قبول درخواست",
      acceptDescription: "از این درخواست یک شاگرد ایجاد کنید. شماره و سال ثبت‌نام اختیاری است.",
      fieldDialog: {
        editDescription: "فیلد فورم ثبت‌نام را به‌روز کنید.",
        newDescription: "یک فیلد جدید به فورم ثبت‌نام آنلاین اضافه کنید."
      },
      fieldForm: {
        key: "کلید",
        label: "برچسب",
        type: "نوع فیلد",
        selectType: "انتخاب نوع",
        sortOrder: "ترتیب",
        options: "گزینه‌ها (جدا شده با کاما)",
        placeholder: "متن راهنما",
        helpText: "متن راهنما",
        required: "اجباری",
        enabled: "فعال"
      },
      fieldTypes: {
        text: "متن",
        textarea: "جعبه متن",
        phone: "تلفن",
        number: "عدد",
        select: "انتخاب",
        multiselect: "چند انتخابی",
        date: "تاریخ",
        toggle: "سوئیچ",
        email: "ایمیل",
        idNumber: "شماره تذکره",
        address: "آدرس",
        photo: "عکس",
        file: "فایل"
      },
      statuses: {
        submitted: "ثبت شده",
        underReview: "در حال بررسی",
        accepted: "پذیرفته شده",
        rejected: "رد شده",
        archived: "بایگانی‌شده"
      }
    },
    inbox: {
      title: "صندوق پیام",
      description: "پیام‌های فرم تماس و استعلام‌ها",
      searchPlaceholder: "جستجوی پیام‌ها...",
      noResults: "پیامی پیدا نشد",
      noSubject: "(بدون موضوع)",
      received: "دریافت شده",
      stats: {
        new: "جدید",
        read: "خوانده شده",
        replied: "پاسخ داده شده",
        total: "همه"
      },
      statuses: {
        new: "جدید",
        read: "خوانده شده",
        replied: "پاسخ داده شده",
        archived: "بایگانی‌شده"
      },
      actions: {
        markRead: "علامت خوانده شد",
        markReplied: "علامت پاسخ داده شد",
        archive: "بایگانی",
        delete: "حذف"
      },
      deleteTitle: "حذف پیام",
      deleteDescription: "آیا مطمئن هستید که این پیام را حذف می‌کنید؟ این عمل برگشت‌پذیر نیست."
    },
    users: {
      title: "کاربران وب‌سایت",
      description: "دعوت و مدیریت حساب‌هایی که فقط به ابزارهای وب‌سایت دسترسی دارند.",
      helperTitle: "دسترسی فقط وب‌سایت",
      helperDescription: "کاربرانی که نقش وب‌سایت دارند فقط منوی مدیریت وب‌سایت را می‌بینند مگر اینکه مجوزهای دیگری بگیرند.",
      stats: {
        total: "کل کاربران",
        active: "فعال",
        inactive: "غیرفعال",
        roles: "نقش‌های استفاده‌شده"
      },
      filters: {
        searchPlaceholder: "جستجوی نام یا ایمیل...",
        role: "نقش",
        status: "وضعیت",
        allRoles: "همه نقش‌ها",
        allStatuses: "همه وضعیت‌ها"
      },
      table: {
        name: "نام",
        email: "ایمیل",
        role: "نقش",
        status: "وضعیت",
        actions: "اقدامات"
      },
      empty: {
        title: "هنوز کاربری برای وب‌سایت وجود ندارد",
        description: "برای شروع یک عضو تیم وب‌سایت را دعوت کنید."
      },
      dialogs: {
        createTitle: "دعوت کاربر وب‌سایت",
        createDescription: "ایجاد حساب جدید با دسترسی فقط وب‌سایت.",
        editTitle: "ویرایش کاربر وب‌سایت",
        editDescription: "به‌روزرسانی اطلاعات تماس و وضعیت دسترسی.",
        deleteTitle: "حذف کاربر وب‌سایت",
        deleteDescription: "این کار حساب را حذف و دسترسی وب‌سایت را لغو می‌کند.",
        resetTitle: "بازنشانی گذرواژه",
        resetDescription: "گذرواژه جدیدی برای این کاربر تنظیم کنید."
      },
      form: {
        fullName: "نام کامل",
        email: "ایمیل",
        password: "گذرواژه موقت",
        role: "نقش وب‌سایت",
        phone: "تلفن",
        defaultSchool: "مدرسه پیش‌فرض",
        selectSchool: "انتخاب مدرسه",
        noDefaultSchool: "بدون مدرسه پیش‌فرض",
        active: "فعال",
        activeHint: "کاربران غیرفعال قادر به ورود برای مدیریت وب‌سایت نیستند."
      },
      status: {
        active: "فعال",
        inactive: "غیرفعال"
      },
      actions: {
        invite: "دعوت کاربر",
        edit: "ویرایش",
        delete: "حذف",
        resetPassword: "بازنشانی گذرواژه"
      },
      roles: {
        website_admin: "مدیر وب‌سایت",
        website_editor: "ویرایشگر وب‌سایت",
        website_media: "مدیر رسانه"
      },
      noPermissionTitle: "دسترسی غیرمجاز",
      noPermissionDescription: "شما مجوز مدیریت کاربران را ندارید.",
      roleLocked: "تغییر نقش‌ها توسط مدیران انجام می‌شود."
    },
    seo: {
      title: "ابزارهای SEO",
      description: "پوشش میتاداتا، کمبودهای SEO و سلامت محتوا را تعقیب کنید.",
      tabs: {
        overview: "نمای کلی",
        content: "سلامت محتوا"
      },
      stats: {
        coverage: "پوشش SEO",
        coverageHint: "مواردی که میتاداتای کامل دارند",
        needsAttention: "نیازمند توجه",
        needsAttentionHint: "صفحه/پست‌هایی که فیلدهای SEO را ندارند",
        total: "مجموع موارد",
        totalHint: "صفحه‌ها و پست‌های تحت تعقیب"
      },
      checklist: {
        title: "چک‌لیست SEO",
        description: "این موارد اساسی را برای دیده‌شدن بهتر تکمیل کنید.",
        metaTitles: "برای هر صفحه و پست عنوان SEO یکتا بنویسید.",
        metaDescriptions: "توضیح کوتاه برای هر صفحه درج کنید.",
        socialImages: "تصویر شبکه‌های اجتماعی را اضافه کنید.",
        cleanUrls: "اسلاگ‌ها را کوتاه، خوانا و متمرکز بر کلیدواژه نگه دارید."
      },
      filters: {
        searchPlaceholder: "جستجوی صفحه‌ها و پست‌ها...",
        type: "نوع محتوا",
        status: "وضعیت",
        allTypes: "همه انواع",
        pages: "صفحه‌ها",
        posts: "پست‌ها",
        allStatuses: "همه وضعیت‌ها",
        needsAttention: "نیازمند توجه",
        complete: "کامل"
      },
      table: {
        title: "عنوان",
        type: "نوع",
        missing: "کمبودها",
        status: "وضعیت",
        publishedAt: "تاریخ نشر"
      },
      empty: "هیچ مشکل SEO مطابق این فیلترها پیدا نشد.",
      missing: {
        title: "عنوان SEO",
        description: "توضیح SEO",
        image: "تصویر SEO"
      },
      complete: "کامل",
      types: {
        page: "صفحه",
        post: "پست"
      },
      actions: {
        openManager: "باز کردن مدیریت"
      }
    },
    audit: {
      title: "گزارشات حسابرسی",
      description: "ببینید چه کسی محتوای وب‌سایت را ایجاد یا ویرایش کرده است.",
      searchPlaceholder: "جستجو بر اساس عنوان یا کاربر...",
      noResults: "هیچ ورودی حسابرسی یافت نشد.",
      systemUser: "سیستم",
      untitled: "بدون عنوان",
      export: "صدور CSV",
      refresh: "به‌روزرسانی",
      summary: {
        total: "کل فعالیت",
        created: "ایجاد شده",
        updated: "به‌روزرسانی شده",
        uniqueUsers: "ویرایش‌کنندگان فعال"
      },
      filters: {
        action: "عمل",
        type: "نوع محتوا"
      },
      actions: {
        created: "ایجاد شده",
        updated: "به‌روزرسانی شده"
      },
      columns: {
        activity: "فعالیت",
        action: "عمل",
        user: "کاربر",
        occurredAt: "تاریخ",
        status: "وضعیت"
      },
      types: {
        page: "صفحه",
        post: "پست",
        announcement: "اعلان",
        event: "رویداد",
        media: "رسانه",
        mediaCategory: "دسته‌بندی رسانه",
        menuLink: "لینک منو",
        domain: "دامنه",
        fatwa: "فتوا",
        publicBook: "کتاب کتابخانه",
        scholar: "عالم",
        course: "دوره",
        graduate: "فارغ‌التحصیل",
        donation: "اهداء"
      }
    }
  }
};
