/**
 * website-admin page translations (ps).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  websiteAdmin: {
    common: {
      filters: "فلټرونه",
      search: "لټون",
      status: "حالت",
      publishedAt: "د خپرېدو نېټه",
      expiresAt: "د ختمېدو نېټه",
      actions: "اقدامات",
      title: "سرلیک",
      slug: "سلګ",
      excerpt: "لنډیز",
      content: "منځپانګه",
      description: "تشریح",
      category: "کټګوري",
      type: "ډول",
      visible: "ښکاره",
      order: "ترتیب",
      url: "URL",
      parent: "والد",
      created: "جوړ شوی",
      preview: "مخکینی لید",
      fileName: "د فایل نوم",
      altText: "بدیل متن",
      public: "عامه",
      yes: "هو",
      no: "نه",
      all: "ټول",
      none: "هیڅ",
      notSet: "نه دی ټاکل شوی",
      sortOrder: "د ترتیب شمېره",
      uploading: "پورته کېږي..."
    },
    statuses: {
      draft: "مسوده",
      scheduled: "مهالویش شوی",
      published: "خپور شوی",
      archived: "آرشیف شوی",
      assigned: "سپارل شوی",
      answered: "ځواب شوی",
      active: "فعال",
      inactive: "غیرفعال",
      pending: "تر څار لاندې",
      verified: "تایید شوی",
      unverified: "نا تایید",
      expired: "منقضي"
    },
    announcements: {
      title: "اعلانونه",
      description: "د وېبپاڼې اعلانونه مدیریت کړئ",
      new: "نوی اعلان",
      searchPlaceholder: "اعلانونه ولټوئ...",
      pinned: "پن شوی",
      pinToHomepage: "په مخپاڼه کې پن کړئ",
      noResults: "اعلانونه ونه موندل شول",
      createTitle: "اعلان جوړ کړئ",
      createDescription: "نوی اعلان جوړ کړئ",
      editTitle: "اعلان سمول",
      editDescription: "د اعلان جزئیات تازه کړئ",
      deleteTitle: "اعلان ړنګول",
      deleteDescription: "ایا ډاډه یاست چې دا اعلان ړنګوئ؟ دا عمل بېرته نه شي کېدای.",
      fields: {
        title: "سرلیک",
        content: "منځپانګه",
        status: "حالت",
        publishedAt: "د خپرېدو نېټه",
        expiresAt: "د ختمېدو نېټه"
      },
      placeholders: {
        title: "د اعلان سرلیک",
        content: "د اعلان منځپانګه..."
      }
    },
    articles: {
      title: "مقالې او بلاګ",
      description: "د بلاګ پوسټونه او مقالې مدیریت کړئ",
      new: "نوی مقاله",
      searchPlaceholder: "مقالې ولټوئ...",
      noResults: "مقالې ونه موندل شوې",
      createTitle: "مقاله جوړول",
      createDescription: "نوی بلاګ پوسټ یا مقاله جوړ کړئ",
      editTitle: "مقاله سمول",
      editDescription: "د مقالې جزئیات تازه کړئ",
      deleteTitle: "مقاله ړنګول",
      deleteDescription: "ایا ډاډه یاست چې دا مقاله ړنګوئ؟ دا عمل بېرته نه شي کېدای.",
      fields: {
        slug: "سلګ",
        title: "سرلیک",
        excerpt: "لنډیز",
        content: "د مقالې منځپانګه",
        status: "حالت",
        publishedAt: "د خپرېدو نېټه"
      },
      placeholders: {
        slug: "my-article",
        title: "د مقالې سرلیک",
        excerpt: "د مقالې لنډیز...",
        content: "خپل مقاله ولیکئ..."
      }
    },
    pages: {
      title: "پاڼې",
      description: "د وېبپاڼې پاڼې مدیریت کړئ",
      new: "نوې پاڼه",
      searchPlaceholder: "پاڼې ولټوئ...",
      noResults: "پاڼې ونه موندل شوې",
      createTitle: "پاڼه جوړول",
      createDescription: "نوې وېبپاڼه پاڼه جوړ کړئ",
      editTitle: "پاڼه سمول",
      editDescription: "د پاڼې جزئیات تازه کړئ",
      deleteTitle: "پاڼه ړنګول",
      deleteDescription: "ایا ډاډه یاست چې دا پاڼه ړنګوئ؟ دا عمل بېرته نه شي کېدای.",
      fields: {
        slug: "سلګ",
        title: "سرلیک",
        status: "حالت",
        publishedAt: "د خپرېدو نېټه",
        content: "منځپانګه"
      },
      placeholders: {
        slug: "about-us",
        title: "زموږ په اړه"
      }
    },
    navigation: {
      title: "ناوبار",
      description: "د سر او پښو مېنوګانې مدیریت کړئ",
      new: "نوې مېنو توکی",
      searchPlaceholder: "مېنو توکي ولټوئ...",
      noResults: "مېنو توکي ونه موندل شول",
      createTitle: "مېنو توکی جوړول",
      createDescription: "نوی مېنو توکی اضافه کړئ",
      editTitle: "مېنو توکی سمول",
      editDescription: "د مېنو توکي جزئیات تازه کړئ",
      deleteTitle: "مېنو توکی ړنګول",
      deleteDescription: "ایا ډاډه یاست چې دا مېنو توکی ړنګوئ؟ دا عمل بېرته نه شي کېدای.",
      fields: {
        label: "لیبل",
        url: "URL",
        parentMenu: "اصلي مېنو",
        sortOrder: "د ترتیب شمېره",
        visible: "ښکاره",
        linkToPage: "پاڼې ته لینک (اختیاري)",
        order: "ترتیب"
      },
      placeholders: {
        selectPage: "یوه پاڼه وټاکئ...",
        label: "کور",
        url: "/home",
        parentNone: "هیڅ (لوړ کچه)"
      }
    },
    events: {
      title: "پیښې",
      description: "د وېبپاڼې د پیښو مهالوېش مدیریت کړئ",
      new: "نوې پیښه",
      searchPlaceholder: "پیښې ولټوئ...",
      noResults: "پیښې ونه موندل شوې",
      createTitle: "پیښه جوړول",
      createDescription: "نوې پیښه جوړ کړئ",
      editTitle: "پیښه سمول",
      editDescription: "د پیښې جزئیات تازه کړئ",
      deleteTitle: "پیښه ړنګول",
      deleteDescription: "ایا ډاډه یاست چې دا پیښه ړنګوئ؟ دا عمل بېرته نه شي کېدای.",
      fields: {
        title: "سرلیک",
        location: "ځای",
        startsAt: "پیل نېټه",
        endsAt: "پای نېټه",
        summary: "لنډیز",
        publicEvent: "عامه پیښه"
      },
      placeholders: {
        title: "د پیښې سرلیک",
        location: "د پیښې ځای",
        summary: "د پیښې لنډیز..."
      }
    },
    domains: {
      title: "ډومېنونه",
      description: "د وېبپاڼې ډومېنونه مدیریت کړئ",
      new: "ډومېن اضافه کړئ",
      searchPlaceholder: "ډومېنونه ولټوئ...",
      noResults: "ډومېنونه ونه موندل شول",
      createTitle: "ډومېن اضافه کول",
      createDescription: "نوی ډومېن اضافه کړئ",
      editTitle: "ډومېن سمول",
      editDescription: "د ډومېن جزئیات تازه کړئ",
      deleteTitle: "ډومېن ړنګول",
      deleteDescription: "ایا ډاډه یاست چې دا ډومېن ړنګوئ؟ دا عمل بېرته نه شي کېدای.",
      fields: {
        domain: "ډومېن",
        primary: "اصلي ډومېن",
        verificationStatus: "د تایید حالت",
        sslStatus: "د SSL حالت"
      },
      placeholders: {
        domain: "example.com",
        selectStatus: "حالت وټاکئ"
      }
    },
    media: {
      title: "رسنۍ",
      description: "د وېبپاڼې د رسنیو کتابتون مدیریت کړئ",
      new: "رسنۍ پورته کول",
      searchPlaceholder: "رسنۍ ولټوئ...",
      noResults: "رسنۍ ونه موندل شوې",
      createTitle: "رسنۍ اضافه کول",
      createDescription: "نوی رسنۍ توکی کتابتون ته اضافه کړئ",
      editTitle: "رسنۍ سمول",
      editDescription: "د رسنیو جزئیات تازه کړئ",
      deleteTitle: "رسنۍ ړنګول",
      deleteDescription: "ایا ډاډه یاست چې دا رسنۍ توکی ړنګوئ؟ دا عمل بېرته نه شي کېدای.",
      previewAlt: "د رسنۍ مخکینی لید",
      libraryPickerTitle: "له کتابتون څخه وټاکئ",
      libraryPickerDescription: "یوه شته انځور وټاکئ",
      noLibraryImages: "په کتابتون کې انځور نشته. لومړی پورته یې کړئ.",
      fields: {
        type: "ډول",
        category: "کټګوري",
        filePath: "د فایل لاره",
        fileName: "سرلیک / د فایل نوم",
        altText: "بدیل متن / تشریح"
      },
      placeholders: {
        search: "رسنۍ ولټوئ...",
        selectCategory: "کټګوري وټاکئ",
        imageUrl: "https://... یا لاره",
        videoUrl: "https://www.youtube.com/watch?v=...",
        documentUrl: "https://...",
        fileName: "زما ښکلی انځور",
        altText: "د منځپانګې لنډه تشریح"
      },
      helpers: {
        uploadOrSelect: "انځور پورته یا وټاکئ",
        uploadHint: "پورته کول (یو یا څو)",
        imageUrlHint: "د انځور URL یا لاره (یا پورته/کتابتون وکاروئ)",
        videoHint: "YouTube، Vimeo یا مستقیم MP4 لینکونه ملاتړ کوي.",
        categoryAppliesToAll: "{count} انځورونه چمتو دي — لاندې کټګوري/بدیل متن په ټولو پلي کېږي"
      },
      types: {
        image: "انځور",
        video: "ویډیو (YouTube/لینک)",
        document: "سند"
      },
      uncategorized: "بې کټګورۍ",
      selectFromLibrary: "له کتابتون څخه وټاکئ",
      addFromLibrary: "له کتابتون څخه وټاکئ"
    },
    fatwas: {
      title: "پوښتنې او فتوې",
      description: "فتوې، کټګورۍ او پوښتنې مدیریت کړئ",
      editTitle: "فتوه سمول",
      editDescription: "د فتوا جزئیات تازه کړئ",
      editCategoryTitle: "کټګوري سمول",
      editCategoryDescription: "د کټګورۍ جزئیات تازه کړئ",
      tabs: {
        fatwas: "فتوې",
        categories: "کټګورۍ",
        questions: "پوښتنې"
      },
      newFatwa: "نوې فتوه",
      newCategory: "نوې کټګوري",
      anonymous: "بې نومه",
      noFatwas: "فتوې ونه موندل شوې",
      noCategories: "کټګورۍ ونه موندل شوې",
      noQuestions: "پوښتنې ونه موندل شوې",
      searchFatwas: "فتوې ولټوئ...",
      searchQuestions: "پوښتنې ولټوئ...",
      fields: {
        slug: "سلګ",
        title: "سرلیک",
        category: "کټګوري",
        question: "پوښتنه",
        answer: "ځواب",
        status: "حالت",
        featured: "ځانګړی",
        publishedAt: "د خپرېدو نېټه",
        name: "نوم",
        description: "تشریح",
        sortOrder: "د ترتیب شمېره",
        active: "فعال",
        assignedTo: "ته سپارل شوی",
        internalNotes: "داخلي یادښتونه",
        answerDraft: "د ځواب مسوده"
      },
      placeholders: {
        slug: "fatwa-slug",
        title: "د فتوا سرلیک",
        question: "د پوښتنې متن...",
        answer: "د فتوا ځواب...",
        categorySlug: "category-slug",
        categoryName: "د کټګورۍ نوم",
        categoryDescription: "د کټګورۍ تشریح...",
        assignedTo: "د کاروونکي ID یا ایمیل",
        internalNotes: "د څار لپاره داخلي یادښتونه...",
        answerDraft: "د ځواب مسوده...",
        selectCategory: "کټګوري وټاکئ"
      },
      moderation: {
        title: "پوښتنه څارل",
        description: "د پوښتنې حالت او ټاکنه تازه کړئ",
        submittedBy: "لېږدونکی",
        questionLabel: "پوښتنه"
      },
      delete: {
        titleFatwa: "فتوه ړنګول",
        titleCategory: "کټګوري ړنګول",
        descriptionFatwa: "ایا ډاډه یاست چې دا فتوه ړنګوئ؟ دا عمل بېرته نه شي کېدای.",
        descriptionCategory: "ایا ډاډه یاست چې دا کټګوري ړنګوئ؟ دا عمل بېرته نه شي کېدای."
      }
    },
    gallery: {
      title: "د ګالري کټګورۍ",
      description: "د ګالري کټګورۍ او البومونه مدیریت کړئ",
      new: "نوې کټګوري",
      searchPlaceholder: "کټګورۍ ولټوئ...",
      noResults: "کټګورۍ ونه موندل شوې",
      slugLabel: "سلګ",
      sortLabel: "د ترتیب شمېره",
      noDescription: "تشریح نشته",
      createTitle: "د ګالري کټګوري جوړول",
      createDescription: "نوې د ګالري کټګوري اضافه کړئ",
      editTitle: "د ګالري کټګوري سمول",
      editDescription: "د ګالري کټګورۍ جزئیات تازه کړئ",
      deleteTitle: "د ګالري کټګوري ړنګول",
      deleteDescription: "ایا ډاډه یاست چې دا کټګوري ړنګوئ؟ دا عمل بېرته نه شي کېدای.",
      fields: {
        name: "نوم",
        coverImage: "پوښ انځور"
      },
      placeholders: {
        name: "د کټګورۍ نوم",
        slug: "gallery-category",
        coverPath: "د انځور لاره یا URL"
      },
      coverUploadCta: "پوښ انځور پورته یا له کتابتون څخه وټاکئ",
      coverPreviewAlt: "د ګالري پوښ مخکینی لید"
    },
    courses: {
      title: "کورسونه",
      description: "عامه کورسونه مدیریت کړئ",
      new: "نوی کورس",
      searchPlaceholder: "کورسونه ولټوئ...",
      noResults: "کورسونه ونه موندل شول",
      createTitle: "کورس جوړول",
      createDescription: "نوی کورس اضافه کړئ",
      editTitle: "کورس سمول",
      editDescription: "د کورس جزئیات تازه کړئ",
      deleteTitle: "کورس ړنګول",
      deleteDescription: "ایا ډاډه یاست چې دا کورس ړنګوئ؟ دا عمل بېرته نه شي کېدای.",
      fields: {
        title: "سرلیک",
        instructor: "ښوونکی",
        duration: "موده",
        level: "کچه",
        enrollmentLink: "د نوم لیکنې لینک",
        coverImage: "پوښ انځور"
      },
      placeholders: {
        title: "د کورس سرلیک",
        instructor: "د ښوونکي نوم",
        duration: "لکه ۸ اونۍ",
        level: "کچه وټاکئ",
        enrollmentLink: "https://...",
        description: "د کورس تشریح...",
        category: "کټګوري"
      },
      levels: {
        beginner: "پیل",
        intermediate: "منځنۍ",
        advanced: "پرمختللې"
      },
      featured: "ځانګړی",
      uploadImage: "پوښ پورته کول",
      coverPreviewAlt: "د کورس پوښ مخکینی لید",
      noImage: "پوښ انځور نشته",
      enrollmentHelp: "د نوم لیکنې لینک ورکړئ یا تش پرېږدئ چې تڼۍ پټه شي"
    },
    library: {
      title: "کتابتون",
      description: "د عامه کتابتون کتابونه مدیریت کړئ",
      new: "نوی کتاب",
      searchPlaceholder: "کتابونه ولټوئ...",
      noResults: "کتابونه ونه موندل شول",
      createTitle: "کتاب اضافه کول",
      createDescription: "کتابتون ته نوی کتاب اضافه کړئ",
      editTitle: "کتاب سمول",
      editDescription: "د کتاب جزئیات تازه کړئ",
      deleteTitle: "کتاب ړنګول",
      deleteDescription: "ایا ډاډه یاست چې دا کتاب ړنګوئ؟ دا عمل بېرته نه شي کېدای.",
      fields: {
        title: "سرلیک",
        author: "لیکوال",
        coverImage: "پوښ انځور",
        file: "PDF فایل",
        downloads: "ډاونلوډونه"
      },
      placeholders: {
        title: "د کتاب سرلیک",
        author: "د لیکوال نوم",
        category: "کټګوري",
        description: "د کتاب لنډیز...",
        fileUrl: "https://...pdf"
      },
      uploadCover: "پوښ پورته کول",
      uploadFile: "فایل پورته کول",
      featured: "په مخپاڼه کې ځانګړی",
      coverPreviewAlt: "د کتاب پوښ مخکینی لید"
    },
    donations: {
      title: "مرستې",
      description: "د عامه مرستو کمپاینونه مدیریت کړئ",
      new: "نوی کمپاین",
      searchPlaceholder: "کمپاینونه ولټوئ...",
      noResults: "کمپاینونه ونه موندل شول",
      createTitle: "کمپاین جوړول",
      createDescription: "نوی د مرستو کمپاین جوړ کړئ",
      editTitle: "کمپاین سمول",
      editDescription: "د کمپاین جزئیات تازه کړئ",
      deleteTitle: "کمپاین ړنګول",
      deleteDescription: "ایا ډاډه یاست چې دا کمپاین ړنګوئ؟ دا عمل بېرته نه شي کېدای.",
      fields: {
        fundName: "د صندوق نوم",
        target: "هدف اندازه",
        raised: "راټول شوی",
        progress: "پرمختګ",
        active: "فعال"
      },
      placeholders: {
        fundName: "د صندوق نوم",
        target: "10000",
        raised: "2500",
        description: "د کمپاین تشریح..."
      }
    },
    scholars: {
      title: "علما",
      description: "د علماوو عامه لېست مدیریت کړئ",
      new: "نوی عالم",
      searchPlaceholder: "علما ولټوئ...",
      noResults: "علما ونه موندل شول",
      createTitle: "عالم اضافه کول",
      createDescription: "د عالم پروفایل اضافه کړئ",
      editTitle: "عالم سمول",
      editDescription: "د عالم پروفایل تازه کړئ",
      deleteTitle: "عالم ړنګول",
      deleteDescription: "ایا ډاډه یاست چې دا عالم ړنګوئ؟ دا عمل بېرته نه شي کېدای.",
      fields: {
        name: "نوم",
        title: "عنوان",
        email: "ایمیل",
        bio: "پیژندنه",
        photo: "انځور"
      },
      placeholders: {
        name: "بشپړ نوم",
        title: "عنوان یا رول",
        email: "name@example.com",
        bio: "لنډه پېژندنه..."
      },
      featured: "په مخپاڼه کې ځانګړی",
      photoAfterCreate: "انځور به د عالم له جوړېدو وروسته پورته شي.",
      uploadPhoto: "انځور پورته کول"
    },
    graduates: {
      title: "فارغان او پخواني زده کوونکي",
      description: "د فراغت دورې او پخواني زده کوونکي وښایئ",
      new: "نوی فارغ",
      searchPlaceholder: "فارغان ولټوئ...",
      noResults: "فارغان ونه موندل شول",
      createTitle: "فارغ اضافه کول",
      createDescription: "د پخوانیو زده کوونکو لپاره نوی فارغ اضافه کړئ",
      editTitle: "فارغ سمول",
      editDescription: "د فارغ جزئیات تازه کړئ",
      deleteTitle: "فارغ ړنګول",
      deleteDescription: "ایا ډاډه یاست چې دا فارغ ړنګوئ؟",
      fields: {
        name: "نوم",
        program: "پروګرام / درجه",
        year: "د فراغت کال",
        bio: "ژوندلیک"
      },
      placeholders: {
        name: "بشپړ نوم",
        program: "لکه اسلامي زده کړې",
        year: "2024",
        bio: "لنډه پېژندنه..."
      },
      featured: "په مخپاڼه کې ځانګړی"
    },
    admissions: {
      title: "آنلاین داخلې",
      description: "د آنلاین داخلې غوښتنلیکونه وڅېړئ او مدیریت یې کړئ.",
      tabs: {
        applications: "غوښتنلیکونه",
        fields: "د فورم ساحې"
      },
      allStatuses: "ټول حالتونه",
      searchPlaceholder: "د نوم، د سرپرست تلیفون، یا د غوښتنلیک شمېره لټون",
      applicationsTitle: "غوښتنلیکونه",
      fieldsTitle: "د فورم ساحې",
      columns: {
        applicationNo: "د غوښتنلیک شمېره",
        student: "زده کوونکی",
        guardianPhone: "د سرپرست تلیفون",
        applyingGrade: "د غوښتنې ټولګی",
        submitted: "سپارل شوی"
      },
      fieldColumns: {
        key: "کلي",
        label: "لیبل",
        type: "ډول",
        required: "اړین",
        enabled: "فعال",
        sort: "ترتیب"
      },
      loading: "داخلې لېکل کېږي...",
      noResults: "داخلې ونه موندل شوې.",
      actions: {
        view: "لیدل",
        addField: "ساحه اضافه کړئ",
        accept: "قبول او زده کوونکی جوړول",
        saveChanges: "بدلونونه خوندي کړئ",
        confirmAcceptance: "قبول تایید کړئ",
        editField: "ساحه سمول",
        newField: "نوې ساحه",
        saveField: "ساحه خوندي کړئ"
      },
      noFields: "هیڅ دودیزه ساحه نه ده تنظیم شوې.",
      detailsTitle: "د داخلې جزئیات",
      detailsDescription: "دا آنلاین د داخلې غوښتنلیک وګورئ او مدیریت یې کړئ.",
      loadingSingle: "داخلې لېکل کېږي...",
      sections: {
        student: "زده کوونکی",
        guardian: "سرپرست",
        address: "پته",
        previousSchool: "پخوانی ښوونځی",
        statusActions: "حالت او اقدامات",
        documents: "اسناد",
        extraFields: "اضافي ساحې"
      },
      labels: {
        father: "پلار",
        applying: "غوښتنه",
        guardian: "سرپرست",
        origin: "اصلي استوګنځای",
        current: "اوسنی",
        grade: "ټولګی",
        year: "کال",
        notes: "یادښتونه",
        internalNotes: "داخلي یادښتونه",
        rejectionReason: "د رد دلیل",
        field: "ساحه",
        download: "ډاونلوډ",
        admissionNoOptional: "د داخلې نمبر (اختیاري)",
        admissionYearOptional: "د داخلې کال (اختیاري)"
      },
      selectStatus: "حالت وټاکئ",
      placeholders: {
        internalNotes: "داخلي یادښتونه...",
        rejectionReason: "د رد دلیل..."
      },
      noDocuments: "هیڅ اسناد نه دي پورته شوي.",
      noExtraFields: "هیڅ اضافي ساحې نه دي ډکې شوي.",
      acceptTitle: "داخله ومنئ",
      acceptDescription: "له دې غوښتنلیک څخه زده کوونکی جوړ کړئ. د داخلې نمبر او کال اختیاري دي.",
      fieldDialog: {
        editDescription: "د داخلې فورم ساحه تازه کړئ.",
        newDescription: "آنلاین د داخلې فورم ته نوې ساحه اضافه کړئ."
      },
      fieldForm: {
        key: "کلي",
        label: "لیبل",
        type: "د ساحې ډول",
        selectType: "ډول وټاکئ",
        sortOrder: "د ترتیب شمېره",
        options: "غوراوي (په کامه جلا)",
        placeholder: "ځای نښه",
        helpText: "مرستندویه متن",
        required: "اړین",
        enabled: "فعال"
      },
      fieldTypes: {
        text: "متن",
        textarea: "د متن بکس",
        phone: "تلیفون",
        number: "شمېره",
        select: "انتخاب",
        multiselect: "څو انتخابونه",
        date: "نېټه",
        toggle: "بدلول",
        email: "ایمیل",
        idNumber: "د پېژندنې شمېره",
        address: "پته",
        photo: "انځور",
        file: "فایل"
      },
      statuses: {
        submitted: "سپارل شوی",
        underReview: "تر کتنې لاندې",
        accepted: "منل شوی",
        rejected: "رد شوی",
        archived: "آرشیف شوی"
      }
    },
    inbox: {
      title: "ان باکس",
      description: "د اړیکې فورم پیغامونه او پوښتنې",
      searchPlaceholder: "پیغامونه ولټوئ...",
      noResults: "پیغامونه ونه موندل شول",
      noSubject: "(بې موضوع)",
      received: "ترلاسه شوی",
      stats: {
        new: "نوی",
        read: "لوستل شوی",
        replied: "ځواب شوی",
        total: "ټول"
      },
      statuses: {
        new: "نوی",
        read: "لوستل شوی",
        replied: "ځواب شوی",
        archived: "آرشیف شوی"
      },
      actions: {
        markRead: "لوستل شوی وټاکئ",
        markReplied: "ځواب شوی وټاکئ",
        archive: "آرشیف",
        delete: "ړنګول"
      },
      deleteTitle: "پیغام ړنګول",
      deleteDescription: "ایا ډاډه یاست چې دا پیغام ړنګوئ؟ دا عمل بېرته نه شي کېدای."
    },
    users: {
      title: "د ویبپاڼې کاروونکي",
      description: "هغه حسابونه دعوت او اداره کړئ چې یوازې د ویبپاڼې وسایلو ته لاسرسی لري.",
      helperTitle: "یوازې د ویبپاڼې لاسرسی",
      helperDescription: "د ویبپاڼې رول لرونکي کاروونکي یوازې د ویبپاڼې مدیر مېنو ویني، پرته له دې چې نورې اجازې ولري.",
      stats: {
        total: "ټول کاروونکي",
        active: "فعال",
        inactive: "غیرفعال",
        roles: "کارېدلي رولونه"
      },
      filters: {
        searchPlaceholder: "په نوم یا ایمیل کې لټون...",
        role: "رول",
        status: "حالت",
        allRoles: "ټول رولونه",
        allStatuses: "ټول حالتونه"
      },
      table: {
        name: "نوم",
        email: "ایمیل",
        role: "رول",
        status: "حالت",
        actions: "عملونه"
      },
      empty: {
        title: "لا تر اوسه د ویبپاڼې کاروونکي نشته",
        description: "د پیل لپاره د ویبپاڼې ټیم یو غړی دعوت کړئ."
      },
      dialogs: {
        createTitle: "د ویبپاڼې کاروونکی دعوت",
        createDescription: "نوی حساب د یوازې ویبپاڼې لاسرسي سره جوړ کړئ.",
        editTitle: "د ویبپاڼې کاروونکی سمول",
        editDescription: "د اړیکې معلومات او لاسرسي حالت تازه کړئ.",
        deleteTitle: "د ویبپاڼې کاروونکی ړنګول",
        deleteDescription: "دا حساب ړنګوي او د ویبپاڼې لاسرسی لغوه کوي.",
        resetTitle: "پټ نوم بیا ټاکل",
        resetDescription: "د دې کاروونکي لپاره نوی پټ نوم وټاکئ."
      },
      form: {
        fullName: "بشپړ نوم",
        email: "ایمیل",
        password: "لنډمهاله پټ نوم",
        role: "د ویبپاڼې رول",
        phone: "تلیفون",
        defaultSchool: "اصلي ښوونځی",
        selectSchool: "ښوونځی وټاکئ",
        noDefaultSchool: "هیڅ اصلي ښوونځی نشته",
        active: "فعال",
        activeHint: "غیرفعال کاروونکي د ویبپاڼې د مدیریت لپاره ننوتلی نشي."
      },
      status: {
        active: "فعال",
        inactive: "غیرفعال"
      },
      actions: {
        invite: "کاروونکی دعوت",
        edit: "سمول",
        delete: "ړنګول",
        resetPassword: "پټ نوم بیا ټاکل"
      },
      roles: {
        website_admin: "د ویبپاڼې مدیر",
        website_editor: "د ویبپاڼې سمونګر",
        website_media: "د رسنیو مدیر"
      },
      noPermissionTitle: "اجازه نشته",
      noPermissionDescription: "تاسو د کاروونکو د مدیریت اجازه نه لرئ.",
      roleLocked: "د رول بدلونونه یوازې د مدیرانو لخوا کیږي."
    },
    seo: {
      title: "د SEO وسایل",
      description: "د میټاډېټا پوښښ، د SEO نيمګړتياوې او د محتوا روغتيا تعقيبول.",
      tabs: {
        overview: "لنډه کتنه",
        content: "د محتوا روغتيا"
      },
      stats: {
        coverage: "د SEO پوښښ",
        coverageHint: "هغه توکي چې بشپړ میټاډېټا لري",
        needsAttention: "پام ته اړتيا",
        needsAttentionHint: "صفحه/پوسټونه چې د SEO برخې يې نيمګړې دي",
        total: "ټول توکي",
        totalHint: "څارل کېدونکې پاڼې او پوسټونه"
      },
      checklist: {
        title: "د SEO چک ليست",
        description: "دا مهم ټکي بشپړ کړئ چې په لټون کې ښه ښکاره شئ.",
        metaTitles: "د هرې پاڼې او پوسټ لپاره ځانګړی SEO سرليک وليکئ.",
        metaDescriptions: "لنډ تشريح وليکئ چې د هرې پاڼې لنډيز وي.",
        socialImages: "د شريکولو لپاره ټولنيزې انځورونه ورزيات کړئ.",
        cleanUrls: "سلاګونه لنډ، لوستېدونکي او د کليدي ټکو پر بنسټ وساتئ."
      },
      filters: {
        searchPlaceholder: "پاڼې او پوسټونه ولټوئ...",
        type: "د محتوا ډول",
        status: "حالت",
        allTypes: "ټول ډولونه",
        pages: "پاڼې",
        posts: "پوسټونه",
        allStatuses: "ټول حالتونه",
        needsAttention: "پام ته اړتيا",
        complete: "بشپړ"
      },
      table: {
        title: "سرليک",
        type: "ډول",
        missing: "نيمګړې برخې",
        status: "حالت",
        publishedAt: "د خپرېدو نېټه"
      },
      empty: "د ټاکل شوو فلټرونو لپاره د SEO ستونزه ونه موندل شوه.",
      missing: {
        title: "SEO سرليک",
        description: "SEO تشريح",
        image: "SEO انځور"
      },
      complete: "بشپړ",
      types: {
        page: "پاڼه",
        post: "پوسټ"
      },
      actions: {
        openManager: "مديريت ته تلل"
      }
    },
    audit: {
      title: "د حسابرسی راپورونه",
      description: "وګورئ چې د ویب پاڼې محتوا یو چا جوړ کړی یا سمون ورکړی.",
      searchPlaceholder: "د سرلیک یا کارن له مخې لټون...",
      noResults: "د حسابرسی ننوتونو موندل نشول.",
      systemUser: "سیستم",
      untitled: "بې سرلیکه",
      export: "CSV صادرول",
      refresh: "تازه کول",
      summary: {
        total: "ټول فعالیت",
        created: "جوړ شوی",
        updated: "تازه شوی",
        uniqueUsers: "فعال سمونکاري"
      },
      filters: {
        action: "کړنه",
        type: "د محتوا ډول"
      },
      actions: {
        created: "جوړ شوی",
        updated: "تازه شوی"
      },
      columns: {
        activity: "فعالیت",
        action: "کړنه",
        user: "کارن",
        occurredAt: "نیټه",
        status: "حالت"
      },
      types: {
        page: "پاڼه",
        post: "پوسټ",
        announcement: "اعلان",
        event: "پیښه",
        media: "رسنۍ",
        mediaCategory: "د رسنیو کټګوري",
        menuLink: "د مینو لینک",
        domain: "ډومین",
        fatwa: "فتوا",
        publicBook: "د کتابتون کتاب",
        scholar: "عالم",
        course: "کورس",
        graduate: "فارغ",
        donation: "خیریه"
      }
    }
  }
};
