/**
 * website-admin page translations (en).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  websiteAdmin: {
    common: {
      filters: "Filters",
      search: "Search",
      status: "Status",
      publishedAt: "Published At",
      expiresAt: "Expires At",
      actions: "Actions",
      title: "Title",
      slug: "Slug",
      excerpt: "Excerpt",
      content: "Content",
      description: "Description",
      category: "Category",
      type: "Type",
      visible: "Visible",
      order: "Order",
      url: "URL",
      parent: "Parent",
      created: "Created",
      preview: "Preview",
      fileName: "File Name",
      altText: "Alt Text",
      public: "Public",
      yes: "Yes",
      no: "No",
      all: "All",
      none: "None",
      notSet: "Not Set",
      sortOrder: "Sort Order",
      uploading: "Uploading..."
    },
    statuses: {
      draft: "Draft",
      scheduled: "Scheduled",
      published: "Published",
      archived: "Archived",
      assigned: "Assigned",
      answered: "Answered",
      active: "Active",
      inactive: "Inactive",
      pending: "Pending",
      verified: "Verified",
      unverified: "Unverified",
      expired: "Expired"
    },
    announcements: {
      title: "Announcements",
      description: "Manage website announcements",
      new: "New Announcement",
      searchPlaceholder: "Search announcements...",
      pinned: "Pinned",
      pinToHomepage: "Pin to Homepage",
      noResults: "No announcements found",
      createTitle: "Create Announcement",
      createDescription: "Create a new announcement",
      editTitle: "Edit Announcement",
      editDescription: "Update announcement details",
      deleteTitle: "Delete Announcement",
      deleteDescription: "Are you sure you want to delete this announcement? This action cannot be undone.",
      fields: {
        title: "Title",
        content: "Content",
        status: "Status",
        publishedAt: "Published At",
        expiresAt: "Expires At"
      },
      placeholders: {
        title: "Announcement title",
        content: "Announcement content..."
      }
    },
    articles: {
      title: "Articles & Blog",
      description: "Manage blog posts and articles",
      new: "New Article",
      searchPlaceholder: "Search articles...",
      noResults: "No articles found",
      createTitle: "Create Article",
      createDescription: "Create a new blog post or article",
      editTitle: "Edit Article",
      editDescription: "Update article details",
      deleteTitle: "Delete Article",
      deleteDescription: "Are you sure you want to delete this article? This action cannot be undone.",
      fields: {
        slug: "Slug",
        title: "Title",
        excerpt: "Excerpt",
        content: "Article Content",
        status: "Status",
        publishedAt: "Published At"
      },
      placeholders: {
        slug: "my-article",
        title: "Article title",
        excerpt: "Brief summary of the article...",
        content: "Write your article..."
      }
    },
    pages: {
      title: "Pages",
      description: "Manage website pages",
      new: "New Page",
      searchPlaceholder: "Search pages...",
      noResults: "No pages found",
      createTitle: "Create Page",
      createDescription: "Create a new website page",
      editTitle: "Edit Page",
      editDescription: "Update page details",
      deleteTitle: "Delete Page",
      deleteDescription: "Are you sure you want to delete this page? This action cannot be undone.",
      fields: {
        slug: "Slug",
        title: "Title",
        status: "Status",
        publishedAt: "Published At",
        content: "Content"
      },
      placeholders: {
        slug: "about-us",
        title: "About Us"
      }
    },
    navigation: {
      title: "Navigation",
      description: "Manage header and footer menus",
      new: "New Menu Item",
      searchPlaceholder: "Search menu items...",
      noResults: "No menu items found",
      createTitle: "Create Menu Item",
      createDescription: "Add a new menu item",
      editTitle: "Edit Menu Item",
      editDescription: "Update menu item details",
      deleteTitle: "Delete Menu Item",
      deleteDescription: "Are you sure you want to delete this menu item? This action cannot be undone.",
      fields: {
        label: "Label",
        url: "URL",
        parentMenu: "Parent Menu",
        sortOrder: "Sort Order",
        visible: "Visible",
        linkToPage: "Link to Page (Optional)",
        order: "Order"
      },
      placeholders: {
        selectPage: "Select a page...",
        label: "Home",
        url: "/home",
        parentNone: "None (Top Level)"
      }
    },
    events: {
      title: "Events",
      description: "Manage website events calendar",
      new: "New Event",
      searchPlaceholder: "Search events...",
      noResults: "No events found",
      createTitle: "Create Event",
      createDescription: "Create a new event",
      editTitle: "Edit Event",
      editDescription: "Update event details",
      deleteTitle: "Delete Event",
      deleteDescription: "Are you sure you want to delete this event? This action cannot be undone.",
      fields: {
        title: "Title",
        location: "Location",
        startsAt: "Starts At",
        endsAt: "Ends At",
        summary: "Summary",
        publicEvent: "Public Event"
      },
      placeholders: {
        title: "Event title",
        location: "Event location",
        summary: "Brief event summary..."
      }
    },
    domains: {
      title: "Domains",
      description: "Manage website domains",
      new: "Add Domain",
      searchPlaceholder: "Search domains...",
      noResults: "No domains found",
      createTitle: "Add Domain",
      createDescription: "Add a new domain",
      editTitle: "Edit Domain",
      editDescription: "Update domain details",
      deleteTitle: "Delete Domain",
      deleteDescription: "Are you sure you want to delete this domain? This action cannot be undone.",
      fields: {
        domain: "Domain",
        primary: "Primary Domain",
        verificationStatus: "Verification Status",
        sslStatus: "SSL Status"
      },
      placeholders: {
        domain: "example.com",
        selectStatus: "Select status"
      }
    },
    media: {
      title: "Media",
      description: "Manage website media library",
      new: "Upload Media",
      searchPlaceholder: "Search media...",
      noResults: "No media found",
      createTitle: "Add Media",
      createDescription: "Add a new media item to your library",
      editTitle: "Edit Media",
      editDescription: "Update media details",
      deleteTitle: "Delete Media",
      deleteDescription: "Are you sure you want to delete this media item? This action cannot be undone.",
      previewAlt: "Media preview",
      libraryPickerTitle: "Select from library",
      libraryPickerDescription: "Choose an existing image to use",
      noLibraryImages: "No images in library. Upload some first.",
      fields: {
        type: "Type",
        category: "Category",
        filePath: "File Path",
        fileName: "Title / File Name",
        altText: "Alt Text / Description"
      },
      placeholders: {
        search: "Search media...",
        selectCategory: "Select category",
        imageUrl: "https://... or path",
        videoUrl: "https://www.youtube.com/watch?v=...",
        documentUrl: "https://...",
        fileName: "My Great Photo",
        altText: "Brief description of the content"
      },
      helpers: {
        uploadOrSelect: "Upload or select image",
        uploadHint: "Upload (1 or many)",
        imageUrlHint: "Image URL or path (or use upload / library above)",
        videoHint: "Supports YouTube, Vimeo, or direct MP4 links.",
        categoryAppliesToAll: "{count} image(s) ready — category/alt below apply to all"
      },
      types: {
        image: "Image",
        video: "Video (YouTube/Link)",
        document: "Document"
      },
      uncategorized: "Uncategorized",
      selectFromLibrary: "Select from library",
      addFromLibrary: "Select from library"
    },
    fatwas: {
      title: "Questions & Fatwas",
      description: "Manage fatwas, categories, and questions",
      editTitle: "Edit Fatwa",
      editDescription: "Update fatwa details",
      editCategoryTitle: "Edit Category",
      editCategoryDescription: "Update category details",
      tabs: {
        fatwas: "Fatwas",
        categories: "Categories",
        questions: "Questions"
      },
      newFatwa: "New Fatwa",
      newCategory: "New Category",
      anonymous: "Anonymous",
      noFatwas: "No fatwas found",
      noCategories: "No categories found",
      noQuestions: "No questions found",
      searchFatwas: "Search fatwas...",
      searchQuestions: "Search questions...",
      fields: {
        slug: "Slug",
        title: "Title",
        category: "Category",
        question: "Question",
        answer: "Answer",
        status: "Status",
        featured: "Featured",
        publishedAt: "Published At",
        name: "Name",
        description: "Description",
        sortOrder: "Sort Order",
        active: "Active",
        assignedTo: "Assigned To",
        internalNotes: "Internal Notes",
        answerDraft: "Answer Draft"
      },
      placeholders: {
        slug: "fatwa-slug",
        title: "Fatwa title",
        question: "The question text...",
        answer: "The fatwa answer...",
        categorySlug: "category-slug",
        categoryName: "Category name",
        categoryDescription: "Category description...",
        assignedTo: "User ID or email",
        internalNotes: "Internal notes for moderation...",
        answerDraft: "Draft answer...",
        selectCategory: "Select category"
      },
      moderation: {
        title: "Moderate Question",
        description: "Update question status and assignment",
        submittedBy: "Submitted by",
        questionLabel: "Question"
      },
      delete: {
        titleFatwa: "Delete Fatwa",
        titleCategory: "Delete Category",
        descriptionFatwa: "Are you sure you want to delete this fatwa? This action cannot be undone.",
        descriptionCategory: "Are you sure you want to delete this category? This action cannot be undone."
      }
    },
    gallery: {
      title: "Gallery Categories",
      description: "Manage gallery categories and albums",
      new: "New Category",
      searchPlaceholder: "Search categories...",
      noResults: "No categories found",
      slugLabel: "Slug",
      sortLabel: "Sort Order",
      noDescription: "No description",
      createTitle: "Create Gallery Category",
      createDescription: "Add a new gallery category",
      editTitle: "Edit Gallery Category",
      editDescription: "Update gallery category details",
      deleteTitle: "Delete Gallery Category",
      deleteDescription: "Are you sure you want to delete this category? This action cannot be undone.",
      fields: {
        name: "Name",
        coverImage: "Cover Image"
      },
      placeholders: {
        name: "Category name",
        slug: "gallery-category",
        coverPath: "Image path or URL"
      },
      coverUploadCta: "Upload a cover image or choose from the library",
      coverPreviewAlt: "Gallery cover preview"
    },
    courses: {
      title: "Courses",
      description: "Manage public courses",
      new: "New Course",
      searchPlaceholder: "Search courses...",
      noResults: "No courses found",
      createTitle: "Create Course",
      createDescription: "Add a new course",
      editTitle: "Edit Course",
      editDescription: "Update course details",
      deleteTitle: "Delete Course",
      deleteDescription: "Are you sure you want to delete this course? This action cannot be undone.",
      fields: {
        title: "Title",
        instructor: "Instructor",
        duration: "Duration",
        level: "Level",
        enrollmentLink: "Enrollment Link",
        coverImage: "Cover Image"
      },
      placeholders: {
        title: "Course title",
        instructor: "Instructor name",
        duration: "e.g. 8 weeks",
        level: "Select level",
        enrollmentLink: "https://...",
        description: "Course description...",
        category: "Category"
      },
      levels: {
        beginner: "Beginner",
        intermediate: "Intermediate",
        advanced: "Advanced"
      },
      featured: "Featured",
      uploadImage: "Upload Cover",
      coverPreviewAlt: "Course cover preview",
      noImage: "No cover image",
      enrollmentHelp: "Paste the enrollment link or leave blank to hide button"
    },
    library: {
      title: "Library",
      description: "Manage public library books",
      new: "New Book",
      searchPlaceholder: "Search books...",
      noResults: "No books found",
      createTitle: "Add Book",
      createDescription: "Add a new book to the library",
      editTitle: "Edit Book",
      editDescription: "Update book details",
      deleteTitle: "Delete Book",
      deleteDescription: "Are you sure you want to delete this book? This action cannot be undone.",
      fields: {
        title: "Title",
        author: "Author",
        coverImage: "Cover Image",
        file: "PDF File",
        downloads: "Downloads"
      },
      placeholders: {
        title: "Book title",
        author: "Author name",
        category: "Category",
        description: "Book summary...",
        fileUrl: "https://...pdf"
      },
      uploadCover: "Upload Cover",
      uploadFile: "Upload File",
      featured: "Featured on homepage",
      coverPreviewAlt: "Book cover preview"
    },
    donations: {
      title: "Donations",
      description: "Manage public donation campaigns",
      new: "New Campaign",
      searchPlaceholder: "Search campaigns...",
      noResults: "No campaigns found",
      createTitle: "Create Campaign",
      createDescription: "Create a new donation campaign",
      editTitle: "Edit Campaign",
      editDescription: "Update campaign details",
      deleteTitle: "Delete Campaign",
      deleteDescription: "Are you sure you want to delete this campaign? This action cannot be undone.",
      fields: {
        fundName: "Fund Name",
        target: "Target Amount",
        raised: "Raised Amount",
        progress: "Progress",
        active: "Active"
      },
      placeholders: {
        fundName: "Fund name",
        target: "10000",
        raised: "2500",
        description: "Campaign description..."
      }
    },
    scholars: {
      title: "Scholars",
      description: "Manage public scholars directory",
      new: "New Scholar",
      searchPlaceholder: "Search scholars...",
      noResults: "No scholars found",
      createTitle: "Add Scholar",
      createDescription: "Add a scholar profile",
      editTitle: "Edit Scholar",
      editDescription: "Update scholar profile",
      deleteTitle: "Delete Scholar",
      deleteDescription: "Are you sure you want to delete this scholar? This action cannot be undone.",
      fields: {
        name: "Name",
        title: "Title",
        email: "Email",
        bio: "Bio",
        photo: "Photo"
      },
      placeholders: {
        name: "Full name",
        title: "Title or role",
        email: "name@example.com",
        bio: "Short biography..."
      },
      featured: "Featured on homepage",
      photoAfterCreate: "Photo will be uploaded after scholar is created.",
      uploadPhoto: "Upload photo"
    },
    graduates: {
      title: "Graduates & Alumni",
      description: "Showcase graduation cohorts and alumni",
      new: "New Graduate",
      searchPlaceholder: "Search graduates...",
      noResults: "No graduates found",
      createTitle: "Add Graduate",
      createDescription: "Add a new graduate to the alumni showcase",
      editTitle: "Edit Graduate",
      editDescription: "Update graduate details",
      deleteTitle: "Delete Graduate",
      deleteDescription: "Are you sure you want to delete this graduate?",
      fields: {
        name: "Name",
        program: "Program / Degree",
        year: "Graduation Year",
        bio: "Biography"
      },
      placeholders: {
        name: "Full name",
        program: "e.g. Islamic Studies",
        year: "2024",
        bio: "Brief biography..."
      },
      featured: "Featured on homepage"
    },
    admissions: {
      title: "Online Admissions",
      description: "Review and manage online admission submissions.",
      tabs: {
        applications: "Applications",
        fields: "Form Fields"
      },
      allStatuses: "All statuses",
      searchPlaceholder: "Search by name, guardian phone, or application number",
      applicationsTitle: "Applications",
      fieldsTitle: "Form Fields",
      columns: {
        applicationNo: "Application No",
        student: "Student",
        guardianPhone: "Guardian Phone",
        applyingGrade: "Applying Grade",
        submitted: "Submitted"
      },
      fieldColumns: {
        key: "Key",
        label: "Label",
        type: "Type",
        required: "Required",
        enabled: "Enabled",
        sort: "Sort"
      },
      loading: "Loading admissions...",
      noResults: "No admissions found.",
      actions: {
        view: "View",
        addField: "Add Field",
        accept: "Accept & Create Student",
        saveChanges: "Save Changes",
        confirmAcceptance: "Confirm Acceptance",
        editField: "Edit Field",
        newField: "New Field",
        saveField: "Save Field"
      },
      noFields: "No custom fields configured.",
      detailsTitle: "Admission Details",
      detailsDescription: "View and manage this online admission application.",
      loadingSingle: "Loading admission...",
      sections: {
        student: "Student",
        guardian: "Guardian",
        address: "Address",
        previousSchool: "Previous School",
        statusActions: "Status & Actions",
        documents: "Documents",
        extraFields: "Extra Fields"
      },
      labels: {
        father: "Father",
        applying: "Applying",
        guardian: "Guardian",
        origin: "Origin",
        current: "Current",
        grade: "Grade",
        year: "Year",
        notes: "Notes",
        internalNotes: "Internal Notes",
        rejectionReason: "Rejection Reason",
        field: "Field",
        download: "Download",
        admissionNoOptional: "Admission Number (optional)",
        admissionYearOptional: "Admission Year (optional)"
      },
      selectStatus: "Select status",
      placeholders: {
        internalNotes: "Internal notes...",
        rejectionReason: "Reason for rejection..."
      },
      noDocuments: "No documents uploaded.",
      noExtraFields: "No extra fields filled.",
      acceptTitle: "Accept Admission",
      acceptDescription: "Create a student record from this application. Optionally set admission number and year.",
      fieldDialog: {
        editDescription: "Update the admission form field.",
        newDescription: "Add a new field to the online admission form."
      },
      fieldForm: {
        key: "Key",
        label: "Label",
        type: "Field Type",
        selectType: "Select type",
        sortOrder: "Sort Order",
        options: "Options (comma separated)",
        placeholder: "Placeholder",
        helpText: "Help Text",
        required: "Required",
        enabled: "Enabled"
      },
      fieldTypes: {
        text: "Text",
        textarea: "Textarea",
        phone: "Phone",
        number: "Number",
        select: "Select",
        multiselect: "Multi-select",
        date: "Date",
        toggle: "Toggle",
        email: "Email",
        idNumber: "ID Number",
        address: "Address",
        photo: "Photo",
        file: "File"
      },
      statuses: {
        submitted: "Submitted",
        underReview: "Under Review",
        accepted: "Accepted",
        rejected: "Rejected",
        archived: "Archived"
      }
    },
    inbox: {
      title: "Inbox",
      description: "Contact form messages and inquiries",
      searchPlaceholder: "Search messages...",
      noResults: "No messages found",
      noSubject: "(No subject)",
      received: "Received",
      stats: {
        new: "New",
        read: "Read",
        replied: "Replied",
        total: "Total"
      },
      statuses: {
        new: "New",
        read: "Read",
        replied: "Replied",
        archived: "Archived"
      },
      actions: {
        markRead: "Mark as Read",
        markReplied: "Mark as Replied",
        archive: "Archive",
        delete: "Delete"
      },
      deleteTitle: "Delete Message",
      deleteDescription: "Are you sure you want to delete this message? This cannot be undone."
    },
    users: {
      title: "Website Users",
      description: "Invite and manage accounts that can access only the website tools.",
      helperTitle: "Website-only access",
      helperDescription: "Users with website roles see only the Website Manager menu unless other permissions are granted.",
      stats: {
        total: "Total users",
        active: "Active",
        inactive: "Inactive",
        roles: "Roles in use"
      },
      filters: {
        searchPlaceholder: "Search by name or email...",
        role: "Role",
        status: "Status",
        allRoles: "All roles",
        allStatuses: "All statuses"
      },
      table: {
        name: "Name",
        email: "Email",
        role: "Role",
        status: "Status",
        actions: "Actions"
      },
      empty: {
        title: "No website users yet",
        description: "Invite a website team member to get started."
      },
      dialogs: {
        createTitle: "Invite website user",
        createDescription: "Create a new account with website-only access.",
        editTitle: "Edit website user",
        editDescription: "Update contact details and access status.",
        deleteTitle: "Delete website user",
        deleteDescription: "This removes the account and revokes website access.",
        resetTitle: "Reset password",
        resetDescription: "Set a new password for this user."
      },
      form: {
        fullName: "Full name",
        email: "Email",
        password: "Temporary password",
        role: "Website role",
        phone: "Phone",
        defaultSchool: "Default school",
        selectSchool: "Select a school",
        noDefaultSchool: "No default school",
        active: "Active",
        activeHint: "Inactive users cannot sign in to manage the website."
      },
      status: {
        active: "Active",
        inactive: "Inactive"
      },
      actions: {
        invite: "Invite user",
        edit: "Edit",
        delete: "Delete",
        resetPassword: "Reset password"
      },
      roles: {
        website_admin: "Website Admin",
        website_editor: "Website Editor",
        website_media: "Media Manager"
      },
      noPermissionTitle: "Access denied",
      noPermissionDescription: "You do not have permission to manage users.",
      roleLocked: "Role changes are managed by administrators."
    },
    seo: {
      title: "SEO Tools",
      description: "Track metadata coverage, missing SEO fields, and content health.",
      tabs: {
        overview: "Overview",
        content: "Content health"
      },
      stats: {
        coverage: "SEO coverage",
        coverageHint: "Items with complete metadata",
        needsAttention: "Needs attention",
        needsAttentionHint: "Pages/posts missing SEO fields",
        total: "Total items",
        totalHint: "Pages and posts tracked"
      },
      checklist: {
        title: "SEO checklist",
        description: "Complete these essentials for stronger search visibility.",
        metaTitles: "Add unique SEO titles for every page and post.",
        metaDescriptions: "Write short descriptions that summarize each page.",
        socialImages: "Attach social images for share cards.",
        cleanUrls: "Keep slugs short, readable, and keyword-focused."
      },
      filters: {
        searchPlaceholder: "Search pages and posts...",
        type: "Content type",
        status: "Status",
        allTypes: "All types",
        pages: "Pages",
        posts: "Posts",
        allStatuses: "All statuses",
        needsAttention: "Needs attention",
        complete: "Complete"
      },
      table: {
        title: "Title",
        type: "Type",
        missing: "Missing",
        status: "Status",
        publishedAt: "Published At"
      },
      empty: "No SEO issues found for the selected filters.",
      missing: {
        title: "SEO title",
        description: "SEO description",
        image: "SEO image"
      },
      complete: "Complete",
      types: {
        page: "Page",
        post: "Post"
      },
      actions: {
        openManager: "Open manager"
      }
    },
    audit: {
      title: "Audit Logs",
      description: "See who created or edited website content.",
      searchPlaceholder: "Search by title or user...",
      noResults: "No audit entries found.",
      systemUser: "System",
      untitled: "Untitled",
      export: "Export CSV",
      refresh: "Refresh",
      summary: {
        total: "Total activity",
        created: "Created",
        updated: "Updated",
        uniqueUsers: "Active editors"
      },
      filters: {
        action: "Action",
        type: "Content type"
      },
      actions: {
        created: "Created",
        updated: "Updated"
      },
      columns: {
        activity: "Activity",
        action: "Action",
        user: "User",
        occurredAt: "Date",
        status: "Status"
      },
      types: {
        page: "Page",
        post: "Post",
        announcement: "Announcement",
        event: "Event",
        media: "Media",
        mediaCategory: "Media Category",
        menuLink: "Menu Link",
        domain: "Domain",
        fatwa: "Fatwa",
        publicBook: "Library Book",
        scholar: "Scholar",
        course: "Course",
        graduate: "Graduate",
        donation: "Donation"
      }
    }
  }
};
