/**
 * Shared ui translations (ar).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  ui: {
    breadcrumb: {
      label: "مسار التنقل"
    },
    carousel: {
      nextSlide: "الشريحة التالية"
    },
    sidebar: {
      toggle: "تبديل الشريط الجانبي"
    }
  }
};
