/**
 * Shared ui translations (fa).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  ui: {
    breadcrumb: {
      label: "مسیر"
    },
    carousel: {
      nextSlide: "اسلاید بعدی"
    },
    sidebar: {
      toggle: "تغییر نوار کناری"
    }
  }
};
