/**
 * Shared ui translations (fa).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  ui: {
    breadcrumb: {
      label: "breadcrumb"
    },
    carousel: {
      nextSlide: "Next slide"
    },
    sidebar: {
      toggle: "Toggle Sidebar"
    }
  }
};
