/**
 * Shared ui translations (ps).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  ui: {
    breadcrumb: {
      label: "ډوډۍ ټوټه"
    },
    carousel: {
      nextSlide: "بل سلایډ"
    },
    sidebar: {
      toggle: "اړخ پټه وتړئ/خلاص کړئ"
    }
  }
};
