/* eslint-disable max-len */
/**
 * Auto-generated by scripts/i18n/generate-permissions-management-catalog.mjs
 * Source: scripts/i18n/_permissions-meta.json (from PermissionSeeder.php via dump-permissions-meta.php)
 * Do not edit by hand — regenerate after backend permission changes.
 */
import type { PermissionsManagementCatalog } from './types';

export const permissionsManagementCatalogAr: PermissionsManagementCatalog = {
  "roles": {
    "admin": {
      "title": "مسؤول النظام (المدرسة)",
      "description": "وصول كامل لجميع ميزات النطاق المدرسي."
    },
    "organization_admin": {
      "title": "مسؤول المؤسسة",
      "description": "مسؤول المؤسسة بصلاحيات كاملة لجميع الميزات."
    },
    "staff": {
      "title": "موظف",
      "description": "صلاحيات محددة للمهام التشغيلية؛ المالية والرسوم للقراءة فقط ما لم يُمنح غير ذلك."
    },
    "teacher": {
      "title": "معلم",
      "description": "صلاحية المحتوى الأكاديمي ومعلومات الطلاب."
    },
    "exam_controller": {
      "title": "مسؤول الامتحانات",
      "description": "إدارة كاملة للامتحانات (حيث لا يوجد تقييد)."
    },
    "accountant": {
      "title": "محاسب",
      "description": "صلاحية كاملة للمالية والرسوم والعملات المتعددة."
    },
    "hostel_manager": {
      "title": "مسؤول السكن",
      "description": "تعيين الغرف والتقارير ذات الصلة."
    },
    "librarian": {
      "title": "أمين المكتبة",
      "description": "إعارة وإرجاع الكتب للطلاب والموظفين؛ المكتبة والوثائق."
    },
    "website_admin": {
      "title": "مسؤول الموقع",
      "description": "مسؤول الموقع — المحتوى والإعدادات بالكامل."
    },
    "website_editor": {
      "title": "محرر الموقع",
      "description": "تحرير الصفحات والمنشورات والفعاليات والقوائم."
    },
    "website_media": {
      "title": "مسؤول وسائط الموقع",
      "description": "إدارة مكتبة الوسائط فقط."
    },
    "organization_hr_admin": {
      "title": "مسؤول الموارد البشرية للمؤسسة",
      "description": "صلاحية كاملة للموارد البشرية والرواتب."
    },
    "hr_officer": {
      "title": "مسؤول موارد بشرية",
      "description": "إدارة الموظفين والتعيينات."
    },
    "payroll_officer": {
      "title": "مسؤول الرواتب",
      "description": "معالجة الرواتب والتقارير."
    },
    "principal": {
      "title": "مدير المدرسة",
      "description": "إشراف بصلاحية قراءة لبيانات الموارد البشرية والمدرسة."
    }
  },
  "featureSections": {
    "students": "الطلاب",
    "staff": "الموظفون",
    "classes": "الصفوف",
    "subjects": "المواد",
    "exams": "الامتحانات",
    "exams_full": "الامتحانات (كامل)",
    "grades": "الدرجات",
    "attendance": "الحضور",
    "finance": "المالية",
    "fees": "الرسوم",
    "multi_currency": "متعدد العملات",
    "dms": "إدارة المستندات",
    "events": "الفعاليات",
    "library": "المكتبة",
    "hostel": "السكن",
    "graduation": "التخرج",
    "id_cards": "بطاقات الهوية",
    "assets": "الأصول",
    "org_hr_core": "الموارد البشرية للمؤسسة",
    "org_hr_payroll": "رواتب المؤسسة",
    "org_hr_analytics": "تقارير الموارد البشرية",
    "org_finance": "مالية المؤسسة",
    "leave_management": "الإجازات",
    "other": "أخرى"
  },
  "permissions": {
    "academic_years.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — السنوات الدراسية"
    },
    "academic_years.delete": {
      "actionLabel": "حذف",
      "description": "حذف — السنوات الدراسية"
    },
    "academic_years.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — السنوات الدراسية"
    },
    "academic_years.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — السنوات الدراسية"
    },
    "activity_logs.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — سجل النشاط"
    },
    "asset_categories.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — فئات الأصول"
    },
    "asset_categories.delete": {
      "actionLabel": "حذف",
      "description": "حذف — فئات الأصول"
    },
    "asset_categories.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — فئات الأصول"
    },
    "asset_categories.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — فئات الأصول"
    },
    "assets.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — الأصول"
    },
    "assets.delete": {
      "actionLabel": "حذف",
      "description": "حذف — الأصول"
    },
    "assets.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — الأصول"
    },
    "assets.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — الأصول"
    },
    "attendance_sessions.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — جلسات الحضور"
    },
    "attendance_sessions.delete": {
      "actionLabel": "حذف",
      "description": "حذف — جلسات الحضور"
    },
    "attendance_sessions.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — جلسات الحضور"
    },
    "attendance_sessions.report": {
      "actionLabel": "تقرير",
      "description": "تقرير — جلسات الحضور"
    },
    "attendance_sessions.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — جلسات الحضور"
    },
    "buildings.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — المباني"
    },
    "buildings.delete": {
      "actionLabel": "حذف",
      "description": "حذف — المباني"
    },
    "buildings.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — المباني"
    },
    "buildings.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — المباني"
    },
    "certificate_templates.activate": {
      "actionLabel": "تفعيل",
      "description": "تفعيل — قوالب الشهادات"
    },
    "certificate_templates.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — قوالب الشهادات"
    },
    "certificate_templates.deactivate": {
      "actionLabel": "تعطيل",
      "description": "تعطيل — قوالب الشهادات"
    },
    "certificate_templates.delete": {
      "actionLabel": "حذف",
      "description": "حذف — قوالب الشهادات"
    },
    "certificate_templates.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — قوالب الشهادات"
    },
    "certificate_templates.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — قوالب الشهادات"
    },
    "certificates.issue": {
      "actionLabel": "إصدار",
      "description": "إصدار — الشهادات"
    },
    "certificates.print": {
      "actionLabel": "طباعة",
      "description": "طباعة — الشهادات"
    },
    "certificates.revoke": {
      "actionLabel": "إلغاء",
      "description": "إلغاء — الشهادات"
    },
    "classes.assign": {
      "actionLabel": "تعيين",
      "description": "تعيين — الصفوف"
    },
    "classes.copy": {
      "actionLabel": "نسخ",
      "description": "نسخ — الصفوف"
    },
    "classes.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — الصفوف"
    },
    "classes.delete": {
      "actionLabel": "حذف",
      "description": "حذف — الصفوف"
    },
    "classes.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — الصفوف"
    },
    "classes.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — الصفوف"
    },
    "course_attendance.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — حضور الدورة"
    },
    "course_attendance.delete": {
      "actionLabel": "حذف",
      "description": "حذف — حضور الدورة"
    },
    "course_attendance.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — حضور الدورة"
    },
    "course_attendance.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — حضور الدورة"
    },
    "course_documents.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — وثائق الدورة"
    },
    "course_documents.delete": {
      "actionLabel": "حذف",
      "description": "حذف — وثائق الدورة"
    },
    "course_documents.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — وثائق الدورة"
    },
    "course_documents.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — وثائق الدورة"
    },
    "course_student_discipline_records.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — سجلات الانضباط"
    },
    "course_student_discipline_records.delete": {
      "actionLabel": "حذف",
      "description": "حذف — سجلات الانضباط"
    },
    "course_student_discipline_records.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — سجلات الانضباط"
    },
    "course_student_discipline_records.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — سجلات الانضباط"
    },
    "course_students.copy_to_main": {
      "actionLabel": "نسخ إلى الرئيسي",
      "description": "نسخ إلى الرئيسي — طلاب الدورة"
    },
    "course_students.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — طلاب الدورة"
    },
    "course_students.delete": {
      "actionLabel": "حذف",
      "description": "حذف — طلاب الدورة"
    },
    "course_students.enroll_from_main": {
      "actionLabel": "تسجيل من الرئيسي",
      "description": "تسجيل من الرئيسي — طلاب الدورة"
    },
    "course_students.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — طلاب الدورة"
    },
    "course_students.report": {
      "actionLabel": "تقرير",
      "description": "تقرير — طلاب الدورة"
    },
    "course_students.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — طلاب الدورة"
    },
    "currencies.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — العملات"
    },
    "currencies.delete": {
      "actionLabel": "حذف",
      "description": "حذف — العملات"
    },
    "currencies.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — العملات"
    },
    "currencies.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — العملات"
    },
    "dms.archive.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — إدارة المستندات — الأرشيف"
    },
    "dms.archive.search": {
      "actionLabel": "بحث",
      "description": "بحث — إدارة المستندات — الأرشيف"
    },
    "dms.departments.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — إدارة المستندات — الأقسام"
    },
    "dms.departments.delete": {
      "actionLabel": "حذف",
      "description": "حذف — إدارة المستندات — الأقسام"
    },
    "dms.departments.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — إدارة المستندات — الأقسام"
    },
    "dms.departments.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — إدارة المستندات — الأقسام"
    },
    "dms.files.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — إدارة المستندات — الملفات"
    },
    "dms.files.delete": {
      "actionLabel": "حذف",
      "description": "حذف — إدارة المستندات — الملفات"
    },
    "dms.files.download": {
      "actionLabel": "تنزيل",
      "description": "تنزيل — إدارة المستندات — الملفات"
    },
    "dms.files.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — إدارة المستندات — الملفات"
    },
    "dms.files.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — إدارة المستندات — الملفات"
    },
    "dms.incoming.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — إدارة المستندات — الوارد"
    },
    "dms.incoming.delete": {
      "actionLabel": "حذف",
      "description": "حذف — إدارة المستندات — الوارد"
    },
    "dms.incoming.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — إدارة المستندات — الوارد"
    },
    "dms.incoming.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — إدارة المستندات — الوارد"
    },
    "dms.letter_types.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — إدارة المستندات — أنواع الخطابات"
    },
    "dms.letter_types.delete": {
      "actionLabel": "حذف",
      "description": "حذف — إدارة المستندات — أنواع الخطابات"
    },
    "dms.letter_types.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — إدارة المستندات — أنواع الخطابات"
    },
    "dms.letter_types.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — إدارة المستندات — أنواع الخطابات"
    },
    "dms.letterheads.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — إدارة المستندات — ترويسة الخطاب"
    },
    "dms.letterheads.delete": {
      "actionLabel": "حذف",
      "description": "حذف — إدارة المستندات — ترويسة الخطاب"
    },
    "dms.letterheads.manage": {
      "actionLabel": "إدارة",
      "description": "إدارة — إدارة المستندات — ترويسة الخطاب"
    },
    "dms.letterheads.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — إدارة المستندات — ترويسة الخطاب"
    },
    "dms.letterheads.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — إدارة المستندات — ترويسة الخطاب"
    },
    "dms.outgoing.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — إدارة المستندات — الصادر"
    },
    "dms.outgoing.delete": {
      "actionLabel": "حذف",
      "description": "حذف — إدارة المستندات — الصادر"
    },
    "dms.outgoing.generate_pdf": {
      "actionLabel": "إنشاء PDF",
      "description": "إنشاء PDF — إدارة المستندات — الصادر"
    },
    "dms.outgoing.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — إدارة المستندات — الصادر"
    },
    "dms.outgoing.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — إدارة المستندات — الصادر"
    },
    "dms.reports.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — إدارة المستندات — التقارير"
    },
    "dms.settings.manage": {
      "actionLabel": "إدارة",
      "description": "إدارة — إدارة المستندات — الإعدادات"
    },
    "dms.settings.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — إدارة المستندات — الإعدادات"
    },
    "dms.templates.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — إدارة المستندات — القوالب"
    },
    "dms.templates.delete": {
      "actionLabel": "حذف",
      "description": "حذف — إدارة المستندات — القوالب"
    },
    "dms.templates.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — إدارة المستندات — القوالب"
    },
    "dms.templates.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — إدارة المستندات — القوالب"
    },
    "donors.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — المتبرعون"
    },
    "donors.delete": {
      "actionLabel": "حذف",
      "description": "حذف — المتبرعون"
    },
    "donors.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — المتبرعون"
    },
    "donors.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — المتبرعون"
    },
    "event_checkins.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — تسجيل الحضور للفعالية"
    },
    "event_checkins.delete": {
      "actionLabel": "حذف",
      "description": "حذف — تسجيل الحضور للفعالية"
    },
    "event_checkins.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — تسجيل الحضور للفعالية"
    },
    "event_checkins.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — تسجيل الحضور للفعالية"
    },
    "event_guests.checkin": {
      "actionLabel": "تسجيل دخول",
      "description": "تسجيل دخول — ضيوف الفعالية"
    },
    "event_guests.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — ضيوف الفعالية"
    },
    "event_guests.delete": {
      "actionLabel": "حذف",
      "description": "حذف — ضيوف الفعالية"
    },
    "event_guests.import": {
      "actionLabel": "استيراد",
      "description": "استيراد — ضيوف الفعالية"
    },
    "event_guests.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — ضيوف الفعالية"
    },
    "event_guests.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — ضيوف الفعالية"
    },
    "event_types.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — أنواع الفعاليات"
    },
    "event_types.delete": {
      "actionLabel": "حذف",
      "description": "حذف — أنواع الفعاليات"
    },
    "event_types.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — أنواع الفعاليات"
    },
    "event_types.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — أنواع الفعاليات"
    },
    "events.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — الفعاليات"
    },
    "events.delete": {
      "actionLabel": "حذف",
      "description": "حذف — الفعاليات"
    },
    "events.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — الفعاليات"
    },
    "events.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — الفعاليات"
    },
    "exam_classes.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — صفوف الامتحان"
    },
    "exam_classes.delete": {
      "actionLabel": "حذف",
      "description": "حذف — صفوف الامتحان"
    },
    "exam_classes.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — صفوف الامتحان"
    },
    "exam_classes.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — صفوف الامتحان"
    },
    "exam_documents.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — وثائق الامتحان"
    },
    "exam_documents.delete": {
      "actionLabel": "حذف",
      "description": "حذف — وثائق الامتحان"
    },
    "exam_documents.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — وثائق الامتحان"
    },
    "exam_documents.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — وثائق الامتحان"
    },
    "exam_results.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — نتائج الامتحان"
    },
    "exam_results.delete": {
      "actionLabel": "حذف",
      "description": "حذف — نتائج الامتحان"
    },
    "exam_results.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — نتائج الامتحان"
    },
    "exam_results.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — نتائج الامتحان"
    },
    "exam_students.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — طلاب الامتحان"
    },
    "exam_students.delete": {
      "actionLabel": "حذف",
      "description": "حذف — طلاب الامتحان"
    },
    "exam_students.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — طلاب الامتحان"
    },
    "exam_students.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — طلاب الامتحان"
    },
    "exam_subjects.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — مواد الامتحان"
    },
    "exam_subjects.delete": {
      "actionLabel": "حذف",
      "description": "حذف — مواد الامتحان"
    },
    "exam_subjects.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — مواد الامتحان"
    },
    "exam_subjects.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — مواد الامتحان"
    },
    "exam_times.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — أوقات الامتحان"
    },
    "exam_times.delete": {
      "actionLabel": "حذف",
      "description": "حذف — أوقات الامتحان"
    },
    "exam_times.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — أوقات الامتحان"
    },
    "exam_times.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — أوقات الامتحان"
    },
    "exam_types.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — أنواع الامتحان"
    },
    "exam_types.delete": {
      "actionLabel": "حذف",
      "description": "حذف — أنواع الامتحان"
    },
    "exam_types.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — أنواع الامتحان"
    },
    "exam_types.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — أنواع الامتحان"
    },
    "exams.assign": {
      "actionLabel": "تعيين",
      "description": "تعيين — الامتحانات"
    },
    "exams.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — الامتحانات"
    },
    "exams.delete": {
      "actionLabel": "حذف",
      "description": "حذف — الامتحانات"
    },
    "exams.enroll_students": {
      "actionLabel": "تسجيل الطلاب",
      "description": "تسجيل الطلاب — الامتحانات"
    },
    "exams.enter_marks": {
      "actionLabel": "إدخال الدرجات",
      "description": "إدخال الدرجات — الامتحانات"
    },
    "exams.manage": {
      "actionLabel": "إدارة",
      "description": "إدارة — الامتحانات"
    },
    "exams.manage_attendance": {
      "actionLabel": "إدارة الحضور",
      "description": "إدارة الحضور — الامتحانات"
    },
    "exams.manage_timetable": {
      "actionLabel": "جدول الامتحان",
      "description": "جدول الامتحان — الامتحانات"
    },
    "exams.numbers.print": {
      "actionLabel": "طباعة الملصقات",
      "description": "طباعة الملصقات — الامتحانات"
    },
    "exams.papers.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — الامتحانات — أوراق الامتحان"
    },
    "exams.papers.delete": {
      "actionLabel": "حذف",
      "description": "حذف — الامتحانات — أوراق الامتحان"
    },
    "exams.papers.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — الامتحانات — أوراق الامتحان"
    },
    "exams.papers.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — الامتحانات — أوراق الامتحان"
    },
    "exams.questions.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — الامتحانات — بنك الأسئلة"
    },
    "exams.questions.delete": {
      "actionLabel": "حذف",
      "description": "حذف — الامتحانات — بنك الأسئلة"
    },
    "exams.questions.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — الامتحانات — بنك الأسئلة"
    },
    "exams.questions.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — الامتحانات — بنك الأسئلة"
    },
    "exams.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — الامتحانات"
    },
    "exams.roll_numbers.assign": {
      "actionLabel": "تعيين أرقام اللوح",
      "description": "تعيين أرقام اللوح — الامتحانات"
    },
    "exams.roll_numbers.read": {
      "actionLabel": "عرض أرقام اللوح",
      "description": "عرض أرقام اللوح — الامتحانات"
    },
    "exams.secret_numbers.assign": {
      "actionLabel": "تعيين الأرقام السرية",
      "description": "تعيين الأرقام السرية — الامتحانات"
    },
    "exams.secret_numbers.read": {
      "actionLabel": "عرض الأرقام السرية",
      "description": "عرض الأرقام السرية — الامتحانات"
    },
    "exams.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — الامتحانات"
    },
    "exams.view_attendance_reports": {
      "actionLabel": "تقرير الحضور",
      "description": "تقرير الحضور — الامتحانات"
    },
    "exams.view_class_reports": {
      "actionLabel": "تقرير الصف",
      "description": "تقرير الصف — الامتحانات"
    },
    "exams.view_consolidated_reports": {
      "actionLabel": "تقارير مجمعة",
      "description": "تقارير مجمعة — الامتحانات"
    },
    "exams.view_grade_cards": {
      "actionLabel": "بطاقات الدرجات",
      "description": "بطاقات الدرجات — الامتحانات"
    },
    "exams.view_reports": {
      "actionLabel": "عرض التقارير",
      "description": "عرض التقارير — الامتحانات"
    },
    "exams.view_student_reports": {
      "actionLabel": "تقرير الطالب",
      "description": "تقرير الطالب — الامتحانات"
    },
    "exchange_rates.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — أسعار الصرف"
    },
    "exchange_rates.delete": {
      "actionLabel": "حذف",
      "description": "حذف — أسعار الصرف"
    },
    "exchange_rates.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — أسعار الصرف"
    },
    "exchange_rates.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — أسعار الصرف"
    },
    "expense_categories.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — فئات المصروفات"
    },
    "expense_categories.delete": {
      "actionLabel": "حذف",
      "description": "حذف — فئات المصروفات"
    },
    "expense_categories.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — فئات المصروفات"
    },
    "expense_categories.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — فئات المصروفات"
    },
    "expense_entries.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — قيود المصروفات"
    },
    "expense_entries.delete": {
      "actionLabel": "حذف",
      "description": "حذف — قيود المصروفات"
    },
    "expense_entries.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — قيود المصروفات"
    },
    "expense_entries.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — قيود المصروفات"
    },
    "fees.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — الرسوم"
    },
    "fees.delete": {
      "actionLabel": "حذف",
      "description": "حذف — الرسوم"
    },
    "fees.exceptions.approve": {
      "actionLabel": "اعتماد",
      "description": "اعتماد — الرسوم — الاستثناءات"
    },
    "fees.exceptions.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — الرسوم — الاستثناءات"
    },
    "fees.payments.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — الرسوم — المدفوعات"
    },
    "fees.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — الرسوم"
    },
    "fees.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — الرسوم"
    },
    "finance_accounts.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — الحسابات المالية"
    },
    "finance_accounts.delete": {
      "actionLabel": "حذف",
      "description": "حذف — الحسابات المالية"
    },
    "finance_accounts.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — الحسابات المالية"
    },
    "finance_accounts.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — الحسابات المالية"
    },
    "finance_documents.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — الوثائق المالية"
    },
    "finance_documents.delete": {
      "actionLabel": "حذف",
      "description": "حذف — الوثائق المالية"
    },
    "finance_documents.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — الوثائق المالية"
    },
    "finance_documents.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — الوثائق المالية"
    },
    "finance_donors.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — متبرعو المالية"
    },
    "finance_donors.delete": {
      "actionLabel": "حذف",
      "description": "حذف — متبرعو المالية"
    },
    "finance_donors.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — متبرعو المالية"
    },
    "finance_donors.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — متبرعو المالية"
    },
    "finance_expense.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — المصروفات"
    },
    "finance_expense.delete": {
      "actionLabel": "حذف",
      "description": "حذف — المصروفات"
    },
    "finance_expense.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — المصروفات"
    },
    "finance_expense.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — المصروفات"
    },
    "finance_income.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — الإيرادات"
    },
    "finance_income.delete": {
      "actionLabel": "حذف",
      "description": "حذف — الإيرادات"
    },
    "finance_income.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — الإيرادات"
    },
    "finance_income.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — الإيرادات"
    },
    "finance_projects.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — المشاريع المالية"
    },
    "finance_projects.delete": {
      "actionLabel": "حذف",
      "description": "حذف — المشاريع المالية"
    },
    "finance_projects.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — المشاريع المالية"
    },
    "finance_projects.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — المشاريع المالية"
    },
    "finance_reports.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — التقارير المالية"
    },
    "grades.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — الدرجات"
    },
    "grades.delete": {
      "actionLabel": "حذف",
      "description": "حذف — الدرجات"
    },
    "grades.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — الدرجات"
    },
    "grades.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — الدرجات"
    },
    "graduation_batches.approve": {
      "actionLabel": "اعتماد",
      "description": "اعتماد — دفعات التخرج"
    },
    "graduation_batches.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — دفعات التخرج"
    },
    "graduation_batches.generate_students": {
      "actionLabel": "توليد قائمة الطلاب",
      "description": "توليد قائمة الطلاب — دفعات التخرج"
    },
    "graduation_batches.issue": {
      "actionLabel": "إصدار",
      "description": "إصدار — دفعات التخرج"
    },
    "graduation_batches.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — دفعات التخرج"
    },
    "help_center.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — مركز المساعدة"
    },
    "help_center.delete": {
      "actionLabel": "حذف",
      "description": "حذف — مركز المساعدة"
    },
    "help_center.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — مركز المساعدة"
    },
    "help_center.read_staff": {
      "actionLabel": "قراءة محتوى الموظفين",
      "description": "قراءة محتوى الموظفين — مركز المساعدة"
    },
    "help_center.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — مركز المساعدة"
    },
    "hostel.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — السكن"
    },
    "hostel.delete": {
      "actionLabel": "حذف",
      "description": "حذف — السكن"
    },
    "hostel.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — السكن"
    },
    "hostel.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — السكن"
    },
    "hr_assignments.approve": {
      "actionLabel": "اعتماد",
      "description": "اعتماد — تعيينات الموارد البشرية"
    },
    "hr_assignments.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — تعيينات الموارد البشرية"
    },
    "hr_assignments.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — تعيينات الموارد البشرية"
    },
    "hr_assignments.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — تعيينات الموارد البشرية"
    },
    "hr_payroll.approve": {
      "actionLabel": "اعتماد",
      "description": "اعتماد — الرواتب"
    },
    "hr_payroll.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — الرواتب"
    },
    "hr_payroll.export": {
      "actionLabel": "تصدير",
      "description": "تصدير — الرواتب"
    },
    "hr_payroll.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — الرواتب"
    },
    "hr_payroll.run": {
      "actionLabel": "تشغيل",
      "description": "تشغيل — الرواتب"
    },
    "hr_reports.export": {
      "actionLabel": "تصدير",
      "description": "تصدير — تقارير الموارد البشرية"
    },
    "hr_reports.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — تقارير الموارد البشرية"
    },
    "hr_staff.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — الموظفون (الموارد البشرية)"
    },
    "hr_staff.delete": {
      "actionLabel": "حذف",
      "description": "حذف — الموظفون (الموارد البشرية)"
    },
    "hr_staff.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — الموظفون (الموارد البشرية)"
    },
    "hr_staff.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — الموظفون (الموارد البشرية)"
    },
    "id_cards.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — بطاقات الهوية"
    },
    "id_cards.delete": {
      "actionLabel": "حذف",
      "description": "حذف — بطاقات الهوية"
    },
    "id_cards.export": {
      "actionLabel": "تصدير",
      "description": "تصدير — بطاقات الهوية"
    },
    "id_cards.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — بطاقات الهوية"
    },
    "id_cards.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — بطاقات الهوية"
    },
    "income_categories.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — فئات الإيرادات"
    },
    "income_categories.delete": {
      "actionLabel": "حذف",
      "description": "حذف — فئات الإيرادات"
    },
    "income_categories.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — فئات الإيرادات"
    },
    "income_categories.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — فئات الإيرادات"
    },
    "income_entries.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — قيود الإيرادات"
    },
    "income_entries.delete": {
      "actionLabel": "حذف",
      "description": "حذف — قيود الإيرادات"
    },
    "income_entries.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — قيود الإيرادات"
    },
    "income_entries.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — قيود الإيرادات"
    },
    "issued_certificates.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — الشهادات الصادرة"
    },
    "leave_requests.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — طلبات الإجازة"
    },
    "leave_requests.delete": {
      "actionLabel": "حذف",
      "description": "حذف — طلبات الإجازة"
    },
    "leave_requests.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — طلبات الإجازة"
    },
    "leave_requests.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — طلبات الإجازة"
    },
    "library_books.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — كتب المكتبة"
    },
    "library_books.delete": {
      "actionLabel": "حذف",
      "description": "حذف — كتب المكتبة"
    },
    "library_books.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — كتب المكتبة"
    },
    "library_books.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — كتب المكتبة"
    },
    "library_categories.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — فئات المكتبة"
    },
    "library_categories.delete": {
      "actionLabel": "حذف",
      "description": "حذف — فئات المكتبة"
    },
    "library_categories.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — فئات المكتبة"
    },
    "library_categories.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — فئات المكتبة"
    },
    "library_loans.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — إعارة الكتب"
    },
    "library_loans.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — إعارة الكتب"
    },
    "library_loans.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — إعارة الكتب"
    },
    "notifications.manage_preferences": {
      "actionLabel": "تفضيلات الإشعارات",
      "description": "تفضيلات الإشعارات — الإشعارات"
    },
    "notifications.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — الإشعارات"
    },
    "notifications.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — الإشعارات"
    },
    "org_finance.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — مالية المؤسسة"
    },
    "org_finance.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — مالية المؤسسة"
    },
    "organizations.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — المؤسسات"
    },
    "organizations.delete": {
      "actionLabel": "حذف",
      "description": "حذف — المؤسسات"
    },
    "organizations.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — المؤسسات"
    },
    "organizations.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — المؤسسات"
    },
    "permissions.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — الصلاحيات"
    },
    "permissions.delete": {
      "actionLabel": "حذف",
      "description": "حذف — الصلاحيات"
    },
    "permissions.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — الصلاحيات"
    },
    "permissions.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — الصلاحيات"
    },
    "phonebook.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — دليل الهاتف"
    },
    "profiles.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — الملفات الشخصية"
    },
    "profiles.delete": {
      "actionLabel": "حذف",
      "description": "حذف — الملفات الشخصية"
    },
    "profiles.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — الملفات الشخصية"
    },
    "profiles.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — الملفات الشخصية"
    },
    "report_templates.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — قوالب التقارير"
    },
    "report_templates.delete": {
      "actionLabel": "حذف",
      "description": "حذف — قوالب التقارير"
    },
    "report_templates.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — قوالب التقارير"
    },
    "report_templates.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — قوالب التقارير"
    },
    "reports.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — التقارير"
    },
    "residency_types.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — أنواع الإقامة"
    },
    "residency_types.delete": {
      "actionLabel": "حذف",
      "description": "حذف — أنواع الإقامة"
    },
    "residency_types.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — أنواع الإقامة"
    },
    "residency_types.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — أنواع الإقامة"
    },
    "roles.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — الأدوار"
    },
    "roles.delete": {
      "actionLabel": "حذف",
      "description": "حذف — الأدوار"
    },
    "roles.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — الأدوار"
    },
    "roles.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — الأدوار"
    },
    "rooms.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — الغرف"
    },
    "rooms.delete": {
      "actionLabel": "حذف",
      "description": "حذف — الغرف"
    },
    "rooms.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — الغرف"
    },
    "rooms.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — الغرف"
    },
    "schedule_slots.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — الفترات الزمنية"
    },
    "schedule_slots.delete": {
      "actionLabel": "حذف",
      "description": "حذف — الفترات الزمنية"
    },
    "schedule_slots.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — الفترات الزمنية"
    },
    "schedule_slots.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — الفترات الزمنية"
    },
    "school_branding.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — هوية المدرسة"
    },
    "school_branding.delete": {
      "actionLabel": "حذف",
      "description": "حذف — هوية المدرسة"
    },
    "school_branding.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — هوية المدرسة"
    },
    "school_branding.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — هوية المدرسة"
    },
    "schools.access_all": {
      "actionLabel": "الوصول لجميع المدارس",
      "description": "الوصول لجميع المدارس — المدارس"
    },
    "schools.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — المدارس"
    },
    "schools.delete": {
      "actionLabel": "حذف",
      "description": "حذف — المدارس"
    },
    "schools.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — المدارس"
    },
    "schools.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — المدارس"
    },
    "short_term_courses.close": {
      "actionLabel": "إغلاق",
      "description": "إغلاق — دورات قصيرة"
    },
    "short_term_courses.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — دورات قصيرة"
    },
    "short_term_courses.delete": {
      "actionLabel": "حذف",
      "description": "حذف — دورات قصيرة"
    },
    "short_term_courses.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — دورات قصيرة"
    },
    "short_term_courses.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — دورات قصيرة"
    },
    "staff.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — الموظفون"
    },
    "staff.delete": {
      "actionLabel": "حذف",
      "description": "حذف — الموظفون"
    },
    "staff.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — الموظفون"
    },
    "staff.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — الموظفون"
    },
    "staff_documents.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — وثائق الموظفين"
    },
    "staff_documents.delete": {
      "actionLabel": "حذف",
      "description": "حذف — وثائق الموظفين"
    },
    "staff_documents.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — وثائق الموظفين"
    },
    "staff_documents.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — وثائق الموظفين"
    },
    "staff_reports.export": {
      "actionLabel": "تصدير",
      "description": "تصدير — تقارير الموظفين"
    },
    "staff_reports.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — تقارير الموظفين"
    },
    "staff_types.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — أنواع الموظفين"
    },
    "staff_types.delete": {
      "actionLabel": "حذف",
      "description": "حذف — أنواع الموظفين"
    },
    "staff_types.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — أنواع الموظفين"
    },
    "staff_types.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — أنواع الموظفين"
    },
    "student_admissions.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — قبول الطلاب"
    },
    "student_admissions.delete": {
      "actionLabel": "حذف",
      "description": "حذف — قبول الطلاب"
    },
    "student_admissions.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — قبول الطلاب"
    },
    "student_admissions.report": {
      "actionLabel": "تقرير",
      "description": "تقرير — قبول الطلاب"
    },
    "student_admissions.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — قبول الطلاب"
    },
    "student_discipline_records.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — سجلات الانضباط"
    },
    "student_discipline_records.delete": {
      "actionLabel": "حذف",
      "description": "حذف — سجلات الانضباط"
    },
    "student_discipline_records.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — سجلات الانضباط"
    },
    "student_discipline_records.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — سجلات الانضباط"
    },
    "student_documents.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — وثائق الطلاب"
    },
    "student_documents.delete": {
      "actionLabel": "حذف",
      "description": "حذف — وثائق الطلاب"
    },
    "student_documents.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — وثائق الطلاب"
    },
    "student_documents.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — وثائق الطلاب"
    },
    "student_educational_history.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — السجل التعليمي"
    },
    "student_educational_history.delete": {
      "actionLabel": "حذف",
      "description": "حذف — السجل التعليمي"
    },
    "student_educational_history.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — السجل التعليمي"
    },
    "student_educational_history.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — السجل التعليمي"
    },
    "student_reports.export": {
      "actionLabel": "تصدير",
      "description": "تصدير — تقارير الطلاب"
    },
    "student_reports.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — تقارير الطلاب"
    },
    "students.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — الطلاب"
    },
    "students.delete": {
      "actionLabel": "حذف",
      "description": "حذف — الطلاب"
    },
    "students.import": {
      "actionLabel": "استيراد",
      "description": "استيراد — الطلاب"
    },
    "students.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — الطلاب"
    },
    "students.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — الطلاب"
    },
    "subjects.assign": {
      "actionLabel": "تعيين",
      "description": "تعيين — المواد"
    },
    "subjects.copy": {
      "actionLabel": "نسخ",
      "description": "نسخ — المواد"
    },
    "subjects.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — المواد"
    },
    "subjects.delete": {
      "actionLabel": "حذف",
      "description": "حذف — المواد"
    },
    "subjects.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — المواد"
    },
    "subjects.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — المواد"
    },
    "subscription.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — الاشتراك"
    },
    "teacher_subject_assignments.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — تعيين المعلمين للمواد"
    },
    "teacher_subject_assignments.delete": {
      "actionLabel": "حذف",
      "description": "حذف — تعيين المعلمين للمواد"
    },
    "teacher_subject_assignments.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — تعيين المعلمين للمواد"
    },
    "teacher_subject_assignments.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — تعيين المعلمين للمواد"
    },
    "teacher_timetable_preferences.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — تفضيلات الجدول"
    },
    "teacher_timetable_preferences.delete": {
      "actionLabel": "حذف",
      "description": "حذف — تفضيلات الجدول"
    },
    "teacher_timetable_preferences.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — تفضيلات الجدول"
    },
    "teacher_timetable_preferences.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — تفضيلات الجدول"
    },
    "teachers.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — المعلمون"
    },
    "teachers.delete": {
      "actionLabel": "حذف",
      "description": "حذف — المعلمون"
    },
    "teachers.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — المعلمون"
    },
    "teachers.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — المعلمون"
    },
    "timetables.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — الجداول"
    },
    "timetables.delete": {
      "actionLabel": "حذف",
      "description": "حذف — الجداول"
    },
    "timetables.export": {
      "actionLabel": "تصدير",
      "description": "تصدير — الجداول"
    },
    "timetables.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — الجداول"
    },
    "timetables.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — الجداول"
    },
    "users.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — المستخدمون"
    },
    "users.delete": {
      "actionLabel": "حذف",
      "description": "حذف — المستخدمون"
    },
    "users.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — المستخدمون"
    },
    "users.reset_password": {
      "actionLabel": "إعادة تعيين كلمة المرور",
      "description": "إعادة تعيين كلمة المرور — المستخدمون"
    },
    "users.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — المستخدمون"
    },
    "website_domains.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — نطاقات الموقع"
    },
    "website_domains.delete": {
      "actionLabel": "حذف",
      "description": "حذف — نطاقات الموقع"
    },
    "website_domains.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — نطاقات الموقع"
    },
    "website_domains.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — نطاقات الموقع"
    },
    "website_events.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — فعاليات الموقع"
    },
    "website_events.delete": {
      "actionLabel": "حذف",
      "description": "حذف — فعاليات الموقع"
    },
    "website_events.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — فعاليات الموقع"
    },
    "website_events.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — فعاليات الموقع"
    },
    "website_media.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — وسائط الموقع"
    },
    "website_media.delete": {
      "actionLabel": "حذف",
      "description": "حذف — وسائط الموقع"
    },
    "website_media.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — وسائط الموقع"
    },
    "website_media.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — وسائط الموقع"
    },
    "website_menus.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — قوائم الموقع"
    },
    "website_menus.delete": {
      "actionLabel": "حذف",
      "description": "حذف — قوائم الموقع"
    },
    "website_menus.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — قوائم الموقع"
    },
    "website_menus.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — قوائم الموقع"
    },
    "website_pages.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — صفحات الموقع"
    },
    "website_pages.delete": {
      "actionLabel": "حذف",
      "description": "حذف — صفحات الموقع"
    },
    "website_pages.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — صفحات الموقع"
    },
    "website_pages.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — صفحات الموقع"
    },
    "website_posts.create": {
      "actionLabel": "إنشاء",
      "description": "إنشاء — منشورات الموقع"
    },
    "website_posts.delete": {
      "actionLabel": "حذف",
      "description": "حذف — منشورات الموقع"
    },
    "website_posts.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — منشورات الموقع"
    },
    "website_posts.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — منشورات الموقع"
    },
    "website_settings.read": {
      "actionLabel": "قراءة",
      "description": "قراءة — إعدادات الموقع"
    },
    "website_settings.update": {
      "actionLabel": "تحديث",
      "description": "تحديث — إعدادات الموقع"
    }
  }
};
