/* eslint-disable max-len */
/**
 * Auto-generated by scripts/i18n/generate-permissions-management-catalog.mjs
 * Source: scripts/i18n/_permissions-meta.json (from PermissionSeeder.php via dump-permissions-meta.php)
 * Do not edit by hand — regenerate after backend permission changes.
 */
import type { PermissionsManagementCatalog } from './types';

export const permissionsManagementCatalogFa: PermissionsManagementCatalog = {
  "roles": {
    "admin": {
      "title": "مدیر مکتب",
      "description": "دسترسی کامل به همه ویژگی‌های محدود به مکتب."
    },
    "organization_admin": {
      "title": "مدیر سازمان",
      "description": "مدیر سازمان با دسترسی کامل به همه ویژگی‌های سازمان."
    },
    "staff": {
      "title": "کارمند",
      "description": "دسترسی محدود برای امور اداری؛ مالی و فیس فقط خواندنی مگر اجازه جداگانه داده شود."
    },
    "teacher": {
      "title": "معلم",
      "description": "دسترسی به محتوای تعلیمی و اطلاعات شاگردان."
    },
    "exam_controller": {
      "title": "مسئول امتحانات",
      "description": "مدیریت کامل امتحانات (جز جایی که محدود است)."
    },
    "accountant": {
      "title": "محاسب",
      "description": "دسترسی کامل به مالی، فیس و چند ارزی."
    },
    "hostel_manager": {
      "title": "مدیر لیلیه ",
      "description": "تعیین اتاق و گزارش‌های مرتبط."
    },
    "librarian": {
      "title": "کتابدار",
      "description": "اعطا و بازپس‌گیری کتاب به شاگردان و کارمندان؛ کتابخانه و اسناد."
    },
    "website_admin": {
      "title": "مدیر ویب‌سایت",
      "description": "مدیر ویب‌سایت — محتوا و تنظیمات کامل سایت عمومی."
    },
    "website_editor": {
      "title": "ویرایشگر ویب‌سایت",
      "description": "ویرایش صفحات، پست‌ها، رویدادها و منوها."
    },
    "website_media": {
      "title": "مدیر رسانه ویب",
      "description": "مدیریت کتابخانه رسانه‌ای فقط."
    },
    "organization_hr_admin": {
      "title": "مدیر منابع بشری سازمان",
      "description": "دسترسی کامل HR، معاش و امور مرتبط سازمان."
    },
    "hr_officer": {
      "title": "مسئول منابع بشری",
      "description": "مدیریت کارمندان و تخصیص‌ها."
    },
    "payroll_officer": {
      "title": "مسئول معاش",
      "description": "پردازش معاش و گزارش‌های مرتبط."
    },
    "principal": {
      "title": "مدیر مکتب (ناظر)",
      "description": "نظارت با دسترسی خواندنی به HR و داده‌های مکتب."
    }
  },
  "featureSections": {
    "students": "شاگردان",
    "staff": "کارمندان",
    "classes": "صنف‌ها",
    "subjects": "مضامین",
    "exams": "امتحانات",
    "exams_full": "امتحانات (کامل)",
    "grades": "درجات",
    "attendance": "حاضری",
    "finance": "مالی",
    "fees": "فیس",
    "multi_currency": "چند ارزی",
    "dms": "مدیریت اسناد",
    "events": "رویدادها",
    "library": "کتابخانه",
    "hostel": "لیلیه ",
    "graduation": "فراغت",
    "id_cards": "کارت‌های شناسایی",
    "assets": "دارایی‌ها",
    "org_hr_core": "منابع بشری سازمان",
    "org_hr_payroll": "معاش سازمان",
    "org_hr_analytics": "گزارش‌های منابع بشری",
    "org_finance": "مالی سازمان",
    "leave_management": "رخصتی",
    "other": "سایر"
  },
  "permissions": {
    "academic_years.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — سال‌های تعلیمی"
    },
    "academic_years.delete": {
      "actionLabel": "حذف",
      "description": "حذف — سال‌های تعلیمی"
    },
    "academic_years.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — سال‌های تعلیمی"
    },
    "academic_years.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — سال‌های تعلیمی"
    },
    "activity_logs.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — یادداشت فعالیت"
    },
    "asset_categories.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — دسته‌بندی دارایی"
    },
    "asset_categories.delete": {
      "actionLabel": "حذف",
      "description": "حذف — دسته‌بندی دارایی"
    },
    "asset_categories.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — دسته‌بندی دارایی"
    },
    "asset_categories.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — دسته‌بندی دارایی"
    },
    "assets.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — دارایی‌ها"
    },
    "assets.delete": {
      "actionLabel": "حذف",
      "description": "حذف — دارایی‌ها"
    },
    "assets.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — دارایی‌ها"
    },
    "assets.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — دارایی‌ها"
    },
    "attendance_sessions.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — جلسات حاضری"
    },
    "attendance_sessions.delete": {
      "actionLabel": "حذف",
      "description": "حذف — جلسات حاضری"
    },
    "attendance_sessions.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — جلسات حاضری"
    },
    "attendance_sessions.report": {
      "actionLabel": "گزارش",
      "description": "گزارش — جلسات حاضری"
    },
    "attendance_sessions.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — جلسات حاضری"
    },
    "buildings.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — ساختمان‌ها"
    },
    "buildings.delete": {
      "actionLabel": "حذف",
      "description": "حذف — ساختمان‌ها"
    },
    "buildings.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — ساختمان‌ها"
    },
    "buildings.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — ساختمان‌ها"
    },
    "certificate_templates.activate": {
      "actionLabel": "فعال‌سازی",
      "description": "فعال‌سازی — قالب‌های گواهی"
    },
    "certificate_templates.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — قالب‌های گواهی"
    },
    "certificate_templates.deactivate": {
      "actionLabel": "غیرفعال",
      "description": "غیرفعال — قالب‌های گواهی"
    },
    "certificate_templates.delete": {
      "actionLabel": "حذف",
      "description": "حذف — قالب‌های گواهی"
    },
    "certificate_templates.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — قالب‌های گواهی"
    },
    "certificate_templates.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — قالب‌های گواهی"
    },
    "certificates.issue": {
      "actionLabel": "صدور",
      "description": "صدور — گواهی‌ها"
    },
    "certificates.print": {
      "actionLabel": "چاپ",
      "description": "چاپ — گواهی‌ها"
    },
    "certificates.revoke": {
      "actionLabel": "لغو",
      "description": "لغو — گواهی‌ها"
    },
    "classes.assign": {
      "actionLabel": "تخصیص",
      "description": "تخصیص — صنف‌ها"
    },
    "classes.copy": {
      "actionLabel": "رونوشت",
      "description": "رونوشت — صنف‌ها"
    },
    "classes.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — صنف‌ها"
    },
    "classes.delete": {
      "actionLabel": "حذف",
      "description": "حذف — صنف‌ها"
    },
    "classes.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — صنف‌ها"
    },
    "classes.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — صنف‌ها"
    },
    "course_attendance.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — حاضری کورس"
    },
    "course_attendance.delete": {
      "actionLabel": "حذف",
      "description": "حذف — حاضری کورس"
    },
    "course_attendance.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — حاضری کورس"
    },
    "course_attendance.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — حاضری کورس"
    },
    "course_documents.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — اسناد کورس"
    },
    "course_documents.delete": {
      "actionLabel": "حذف",
      "description": "حذف — اسناد کورس"
    },
    "course_documents.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — اسناد کورس"
    },
    "course_documents.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — اسناد کورس"
    },
    "course_student_discipline_records.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — انضباط شاگردان کورس"
    },
    "course_student_discipline_records.delete": {
      "actionLabel": "حذف",
      "description": "حذف — انضباط شاگردان کورس"
    },
    "course_student_discipline_records.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — انضباط شاگردان کورس"
    },
    "course_student_discipline_records.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — انضباط شاگردان کورس"
    },
    "course_students.copy_to_main": {
      "actionLabel": "رونوشت به اصلی",
      "description": "رونوشت به اصلی — شاگردان کورس"
    },
    "course_students.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — شاگردان کورس"
    },
    "course_students.delete": {
      "actionLabel": "حذف",
      "description": "حذف — شاگردان کورس"
    },
    "course_students.enroll_from_main": {
      "actionLabel": "ثبت‌نام از اصلی",
      "description": "ثبت‌نام از اصلی — شاگردان کورس"
    },
    "course_students.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — شاگردان کورس"
    },
    "course_students.report": {
      "actionLabel": "گزارش",
      "description": "گزارش — شاگردان کورس"
    },
    "course_students.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — شاگردان کورس"
    },
    "currencies.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — ارزها"
    },
    "currencies.delete": {
      "actionLabel": "حذف",
      "description": "حذف — ارزها"
    },
    "currencies.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — ارزها"
    },
    "currencies.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — ارزها"
    },
    "dms.archive.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — مدیریت اسناد — بایگانی"
    },
    "dms.archive.search": {
      "actionLabel": "جستجو",
      "description": "جستجو — مدیریت اسناد — بایگانی"
    },
    "dms.departments.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — مدیریت اسناد — بخش‌ها"
    },
    "dms.departments.delete": {
      "actionLabel": "حذف",
      "description": "حذف — مدیریت اسناد — بخش‌ها"
    },
    "dms.departments.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — مدیریت اسناد — بخش‌ها"
    },
    "dms.departments.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — مدیریت اسناد — بخش‌ها"
    },
    "dms.files.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — مدیریت اسناد — فایل‌ها"
    },
    "dms.files.delete": {
      "actionLabel": "حذف",
      "description": "حذف — مدیریت اسناد — فایل‌ها"
    },
    "dms.files.download": {
      "actionLabel": "بارگیری",
      "description": "بارگیری — مدیریت اسناد — فایل‌ها"
    },
    "dms.files.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — مدیریت اسناد — فایل‌ها"
    },
    "dms.files.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — مدیریت اسناد — فایل‌ها"
    },
    "dms.incoming.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — مدیریت اسناد — وارده"
    },
    "dms.incoming.delete": {
      "actionLabel": "حذف",
      "description": "حذف — مدیریت اسناد — وارده"
    },
    "dms.incoming.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — مدیریت اسناد — وارده"
    },
    "dms.incoming.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — مدیریت اسناد — وارده"
    },
    "dms.letter_types.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — مدیریت اسناد — انواع نامه"
    },
    "dms.letter_types.delete": {
      "actionLabel": "حذف",
      "description": "حذف — مدیریت اسناد — انواع نامه"
    },
    "dms.letter_types.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — مدیریت اسناد — انواع نامه"
    },
    "dms.letter_types.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — مدیریت اسناد — انواع نامه"
    },
    "dms.letterheads.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — مدیریت اسناد — سربرگ"
    },
    "dms.letterheads.delete": {
      "actionLabel": "حذف",
      "description": "حذف — مدیریت اسناد — سربرگ"
    },
    "dms.letterheads.manage": {
      "actionLabel": "مدیریت",
      "description": "مدیریت — مدیریت اسناد — سربرگ"
    },
    "dms.letterheads.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — مدیریت اسناد — سربرگ"
    },
    "dms.letterheads.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — مدیریت اسناد — سربرگ"
    },
    "dms.outgoing.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — مدیریت اسناد — صادره"
    },
    "dms.outgoing.delete": {
      "actionLabel": "حذف",
      "description": "حذف — مدیریت اسناد — صادره"
    },
    "dms.outgoing.generate_pdf": {
      "actionLabel": "ایجاد PDF",
      "description": "ایجاد PDF — مدیریت اسناد — صادره"
    },
    "dms.outgoing.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — مدیریت اسناد — صادره"
    },
    "dms.outgoing.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — مدیریت اسناد — صادره"
    },
    "dms.reports.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — مدیریت اسناد — گزارشات"
    },
    "dms.settings.manage": {
      "actionLabel": "مدیریت",
      "description": "مدیریت — مدیریت اسناد — تنظیمات"
    },
    "dms.settings.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — مدیریت اسناد — تنظیمات"
    },
    "dms.templates.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — مدیریت اسناد — قالب‌ها"
    },
    "dms.templates.delete": {
      "actionLabel": "حذف",
      "description": "حذف — مدیریت اسناد — قالب‌ها"
    },
    "dms.templates.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — مدیریت اسناد — قالب‌ها"
    },
    "dms.templates.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — مدیریت اسناد — قالب‌ها"
    },
    "donors.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — اهدا کنندگان"
    },
    "donors.delete": {
      "actionLabel": "حذف",
      "description": "حذف — اهدا کنندگان"
    },
    "donors.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — اهدا کنندگان"
    },
    "donors.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — اهدا کنندگان"
    },
    "event_checkins.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — ورود رویداد"
    },
    "event_checkins.delete": {
      "actionLabel": "حذف",
      "description": "حذف — ورود رویداد"
    },
    "event_checkins.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — ورود رویداد"
    },
    "event_checkins.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — ورود رویداد"
    },
    "event_guests.checkin": {
      "actionLabel": "ورود",
      "description": "ورود — مهمانان رویداد"
    },
    "event_guests.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — مهمانان رویداد"
    },
    "event_guests.delete": {
      "actionLabel": "حذف",
      "description": "حذف — مهمانان رویداد"
    },
    "event_guests.import": {
      "actionLabel": "ورود",
      "description": "ورود — مهمانان رویداد"
    },
    "event_guests.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — مهمانان رویداد"
    },
    "event_guests.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — مهمانان رویداد"
    },
    "event_types.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — انواع رویداد"
    },
    "event_types.delete": {
      "actionLabel": "حذف",
      "description": "حذف — انواع رویداد"
    },
    "event_types.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — انواع رویداد"
    },
    "event_types.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — انواع رویداد"
    },
    "events.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — رویدادها"
    },
    "events.delete": {
      "actionLabel": "حذف",
      "description": "حذف — رویدادها"
    },
    "events.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — رویدادها"
    },
    "events.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — رویدادها"
    },
    "exam_classes.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — صنف‌های امتحان"
    },
    "exam_classes.delete": {
      "actionLabel": "حذف",
      "description": "حذف — صنف‌های امتحان"
    },
    "exam_classes.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — صنف‌های امتحان"
    },
    "exam_classes.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — صنف‌های امتحان"
    },
    "exam_documents.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — اسناد امتحان"
    },
    "exam_documents.delete": {
      "actionLabel": "حذف",
      "description": "حذف — اسناد امتحان"
    },
    "exam_documents.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — اسناد امتحان"
    },
    "exam_documents.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — اسناد امتحان"
    },
    "exam_results.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — نتایج امتحان"
    },
    "exam_results.delete": {
      "actionLabel": "حذف",
      "description": "حذف — نتایج امتحان"
    },
    "exam_results.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — نتایج امتحان"
    },
    "exam_results.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — نتایج امتحان"
    },
    "exam_students.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — شاگردان امتحان"
    },
    "exam_students.delete": {
      "actionLabel": "حذف",
      "description": "حذف — شاگردان امتحان"
    },
    "exam_students.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — شاگردان امتحان"
    },
    "exam_students.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — شاگردان امتحان"
    },
    "exam_subjects.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — مضامین امتحان"
    },
    "exam_subjects.delete": {
      "actionLabel": "حذف",
      "description": "حذف — مضامین امتحان"
    },
    "exam_subjects.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — مضامین امتحان"
    },
    "exam_subjects.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — مضامین امتحان"
    },
    "exam_times.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — اوقات امتحان"
    },
    "exam_times.delete": {
      "actionLabel": "حذف",
      "description": "حذف — اوقات امتحان"
    },
    "exam_times.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — اوقات امتحان"
    },
    "exam_times.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — اوقات امتحان"
    },
    "exam_types.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — انواع امتحان"
    },
    "exam_types.delete": {
      "actionLabel": "حذف",
      "description": "حذف — انواع امتحان"
    },
    "exam_types.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — انواع امتحان"
    },
    "exam_types.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — انواع امتحان"
    },
    "exams.assign": {
      "actionLabel": "تخصیص",
      "description": "تخصیص — امتحانات"
    },
    "exams.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — امتحانات"
    },
    "exams.delete": {
      "actionLabel": "حذف",
      "description": "حذف — امتحانات"
    },
    "exams.enroll_students": {
      "actionLabel": "ثبت‌نام شاگردان",
      "description": "ثبت‌نام شاگردان — امتحانات"
    },
    "exams.enter_marks": {
      "actionLabel": "ثبت نمرات",
      "description": "ثبت نمرات — امتحانات"
    },
    "exams.manage": {
      "actionLabel": "مدیریت",
      "description": "مدیریت — امتحانات"
    },
    "exams.manage_attendance": {
      "actionLabel": "مدیریت حاضری",
      "description": "مدیریت حاضری — امتحانات"
    },
    "exams.manage_timetable": {
      "actionLabel": "جدول امتحان",
      "description": "جدول امتحان — امتحانات"
    },
    "exams.numbers.print": {
      "actionLabel": "چاپ برچسب‌ها",
      "description": "چاپ برچسب‌ها — امتحانات"
    },
    "exams.papers.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — امتحانات — کاغذهای امتحان"
    },
    "exams.papers.delete": {
      "actionLabel": "حذف",
      "description": "حذف — امتحانات — کاغذهای امتحان"
    },
    "exams.papers.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — امتحانات — کاغذهای امتحان"
    },
    "exams.papers.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — امتحانات — کاغذهای امتحان"
    },
    "exams.questions.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — امتحانات — بانک سوال"
    },
    "exams.questions.delete": {
      "actionLabel": "حذف",
      "description": "حذف — امتحانات — بانک سوال"
    },
    "exams.questions.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — امتحانات — بانک سوال"
    },
    "exams.questions.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — امتحانات — بانک سوال"
    },
    "exams.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — امتحانات"
    },
    "exams.roll_numbers.assign": {
      "actionLabel": "تخصیص شماره رول",
      "description": "تخصیص شماره رول — امتحانات"
    },
    "exams.roll_numbers.read": {
      "actionLabel": "مشاهده شماره رول",
      "description": "مشاهده شماره رول — امتحانات"
    },
    "exams.secret_numbers.assign": {
      "actionLabel": "تخصیص شماره محرمانه",
      "description": "تخصیص شماره محرمانه — امتحانات"
    },
    "exams.secret_numbers.read": {
      "actionLabel": "مشاهده شماره محرمانه",
      "description": "مشاهده شماره محرمانه — امتحانات"
    },
    "exams.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — امتحانات"
    },
    "exams.view_attendance_reports": {
      "actionLabel": "گزارش حاضری",
      "description": "گزارش حاضری — امتحانات"
    },
    "exams.view_class_reports": {
      "actionLabel": "گزارش صنف",
      "description": "گزارش صنف — امتحانات"
    },
    "exams.view_consolidated_reports": {
      "actionLabel": "گزارش‌های تجمیعی",
      "description": "گزارش‌های تجمیعی — امتحانات"
    },
    "exams.view_grade_cards": {
      "actionLabel": "کارت نمرات",
      "description": "کارت نمرات — امتحانات"
    },
    "exams.view_reports": {
      "actionLabel": "مشاهده گزارش‌ها",
      "description": "مشاهده گزارش‌ها — امتحانات"
    },
    "exams.view_student_reports": {
      "actionLabel": "گزارش شاگرد",
      "description": "گزارش شاگرد — امتحانات"
    },
    "exchange_rates.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — نرخ ارز"
    },
    "exchange_rates.delete": {
      "actionLabel": "حذف",
      "description": "حذف — نرخ ارز"
    },
    "exchange_rates.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — نرخ ارز"
    },
    "exchange_rates.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — نرخ ارز"
    },
    "expense_categories.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — دسته مصارف"
    },
    "expense_categories.delete": {
      "actionLabel": "حذف",
      "description": "حذف — دسته مصارف"
    },
    "expense_categories.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — دسته مصارف"
    },
    "expense_categories.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — دسته مصارف"
    },
    "expense_entries.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — ثبت مصارف"
    },
    "expense_entries.delete": {
      "actionLabel": "حذف",
      "description": "حذف — ثبت مصارف"
    },
    "expense_entries.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — ثبت مصارف"
    },
    "expense_entries.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — ثبت مصارف"
    },
    "fees.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — فیس"
    },
    "fees.delete": {
      "actionLabel": "حذف",
      "description": "حذف — فیس"
    },
    "fees.exceptions.approve": {
      "actionLabel": "تأیید",
      "description": "تأیید — فیس — استثناها"
    },
    "fees.exceptions.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — فیس — استثناها"
    },
    "fees.payments.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — فیس — پرداخت‌ها"
    },
    "fees.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — فیس"
    },
    "fees.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — فیس"
    },
    "finance_accounts.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — حساب‌های مالی"
    },
    "finance_accounts.delete": {
      "actionLabel": "حذف",
      "description": "حذف — حساب‌های مالی"
    },
    "finance_accounts.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — حساب‌های مالی"
    },
    "finance_accounts.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — حساب‌های مالی"
    },
    "finance_documents.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — اسناد مالی"
    },
    "finance_documents.delete": {
      "actionLabel": "حذف",
      "description": "حذف — اسناد مالی"
    },
    "finance_documents.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — اسناد مالی"
    },
    "finance_documents.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — اسناد مالی"
    },
    "finance_donors.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — اهدا کنندگان مالی"
    },
    "finance_donors.delete": {
      "actionLabel": "حذف",
      "description": "حذف — اهدا کنندگان مالی"
    },
    "finance_donors.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — اهدا کنندگان مالی"
    },
    "finance_donors.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — اهدا کنندگان مالی"
    },
    "finance_expense.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — مصارف"
    },
    "finance_expense.delete": {
      "actionLabel": "حذف",
      "description": "حذف — مصارف"
    },
    "finance_expense.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — مصارف"
    },
    "finance_expense.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — مصارف"
    },
    "finance_income.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — عواید"
    },
    "finance_income.delete": {
      "actionLabel": "حذف",
      "description": "حذف — عواید"
    },
    "finance_income.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — عواید"
    },
    "finance_income.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — عواید"
    },
    "finance_projects.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — پروژه‌های مالی"
    },
    "finance_projects.delete": {
      "actionLabel": "حذف",
      "description": "حذف — پروژه‌های مالی"
    },
    "finance_projects.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — پروژه‌های مالی"
    },
    "finance_projects.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — پروژه‌های مالی"
    },
    "finance_reports.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — گزارشات مالی"
    },
    "grades.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — درجات"
    },
    "grades.delete": {
      "actionLabel": "حذف",
      "description": "حذف — درجات"
    },
    "grades.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — درجات"
    },
    "grades.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — درجات"
    },
    "graduation_batches.approve": {
      "actionLabel": "تأیید",
      "description": "تأیید — دسته‌های فراغت"
    },
    "graduation_batches.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — دسته‌های فراغت"
    },
    "graduation_batches.generate_students": {
      "actionLabel": "تولید فهرست شاگردان",
      "description": "تولید فهرست شاگردان — دسته‌های فراغت"
    },
    "graduation_batches.issue": {
      "actionLabel": "صدور",
      "description": "صدور — دسته‌های فراغت"
    },
    "graduation_batches.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — دسته‌های فراغت"
    },
    "help_center.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — مرکز کمک"
    },
    "help_center.delete": {
      "actionLabel": "حذف",
      "description": "حذف — مرکز کمک"
    },
    "help_center.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — مرکز کمک"
    },
    "help_center.read_staff": {
      "actionLabel": "خواندن مطالب کارکنان",
      "description": "خواندن مطالب کارکنان — مرکز کمک"
    },
    "help_center.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — مرکز کمک"
    },
    "hostel.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — لیلیه "
    },
    "hostel.delete": {
      "actionLabel": "حذف",
      "description": "حذف — لیلیه "
    },
    "hostel.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — لیلیه "
    },
    "hostel.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — لیلیه "
    },
    "hr_assignments.approve": {
      "actionLabel": "تأیید",
      "description": "تأیید — تخصیص‌های منابع بشری"
    },
    "hr_assignments.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — تخصیص‌های منابع بشری"
    },
    "hr_assignments.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — تخصیص‌های منابع بشری"
    },
    "hr_assignments.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — تخصیص‌های منابع بشری"
    },
    "hr_payroll.approve": {
      "actionLabel": "تأیید",
      "description": "تأیید — معاش"
    },
    "hr_payroll.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — معاش"
    },
    "hr_payroll.export": {
      "actionLabel": "صدور",
      "description": "صدور — معاش"
    },
    "hr_payroll.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — معاش"
    },
    "hr_payroll.run": {
      "actionLabel": "اجرای",
      "description": "اجرای — معاش"
    },
    "hr_reports.export": {
      "actionLabel": "صدور",
      "description": "صدور — گزارش‌های منابع بشری"
    },
    "hr_reports.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — گزارش‌های منابع بشری"
    },
    "hr_staff.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — کارمندان (منابع بشری)"
    },
    "hr_staff.delete": {
      "actionLabel": "حذف",
      "description": "حذف — کارمندان (منابع بشری)"
    },
    "hr_staff.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — کارمندان (منابع بشری)"
    },
    "hr_staff.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — کارمندان (منابع بشری)"
    },
    "id_cards.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — کارت شناسایی"
    },
    "id_cards.delete": {
      "actionLabel": "حذف",
      "description": "حذف — کارت شناسایی"
    },
    "id_cards.export": {
      "actionLabel": "صدور",
      "description": "صدور — کارت شناسایی"
    },
    "id_cards.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — کارت شناسایی"
    },
    "id_cards.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — کارت شناسایی"
    },
    "income_categories.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — دسته عواید"
    },
    "income_categories.delete": {
      "actionLabel": "حذف",
      "description": "حذف — دسته عواید"
    },
    "income_categories.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — دسته عواید"
    },
    "income_categories.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — دسته عواید"
    },
    "income_entries.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — ثبت عواید"
    },
    "income_entries.delete": {
      "actionLabel": "حذف",
      "description": "حذف — ثبت عواید"
    },
    "income_entries.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — ثبت عواید"
    },
    "income_entries.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — ثبت عواید"
    },
    "issued_certificates.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — گواهی‌های صادر شده"
    },
    "leave_requests.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — درخواست رخصتی"
    },
    "leave_requests.delete": {
      "actionLabel": "حذف",
      "description": "حذف — درخواست رخصتی"
    },
    "leave_requests.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — درخواست رخصتی"
    },
    "leave_requests.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — درخواست رخصتی"
    },
    "library_books.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — کتاب‌های کتابخانه"
    },
    "library_books.delete": {
      "actionLabel": "حذف",
      "description": "حذف — کتاب‌های کتابخانه"
    },
    "library_books.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — کتاب‌های کتابخانه"
    },
    "library_books.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — کتاب‌های کتابخانه"
    },
    "library_categories.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — دسته‌های کتابخانه"
    },
    "library_categories.delete": {
      "actionLabel": "حذف",
      "description": "حذف — دسته‌های کتابخانه"
    },
    "library_categories.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — دسته‌های کتابخانه"
    },
    "library_categories.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — دسته‌های کتابخانه"
    },
    "library_loans.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — امانت کتاب"
    },
    "library_loans.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — امانت کتاب"
    },
    "library_loans.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — امانت کتاب"
    },
    "notifications.manage_preferences": {
      "actionLabel": "تنظیم ترجیحات",
      "description": "تنظیم ترجیحات — اعلان‌ها"
    },
    "notifications.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — اعلان‌ها"
    },
    "notifications.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — اعلان‌ها"
    },
    "org_finance.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — مالی سازمان"
    },
    "org_finance.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — مالی سازمان"
    },
    "organizations.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — سازمان‌ها"
    },
    "organizations.delete": {
      "actionLabel": "حذف",
      "description": "حذف — سازمان‌ها"
    },
    "organizations.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — سازمان‌ها"
    },
    "organizations.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — سازمان‌ها"
    },
    "permissions.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — اجازه‌ها"
    },
    "permissions.delete": {
      "actionLabel": "حذف",
      "description": "حذف — اجازه‌ها"
    },
    "permissions.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — اجازه‌ها"
    },
    "permissions.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — اجازه‌ها"
    },
    "phonebook.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — دفتر تلفن"
    },
    "profiles.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — پروفایل‌ها"
    },
    "profiles.delete": {
      "actionLabel": "حذف",
      "description": "حذف — پروفایل‌ها"
    },
    "profiles.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — پروفایل‌ها"
    },
    "profiles.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — پروفایل‌ها"
    },
    "report_templates.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — قالب گزارش"
    },
    "report_templates.delete": {
      "actionLabel": "حذف",
      "description": "حذف — قالب گزارش"
    },
    "report_templates.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — قالب گزارش"
    },
    "report_templates.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — قالب گزارش"
    },
    "reports.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — گزارشات"
    },
    "residency_types.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — انواع اقامت"
    },
    "residency_types.delete": {
      "actionLabel": "حذف",
      "description": "حذف — انواع اقامت"
    },
    "residency_types.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — انواع اقامت"
    },
    "residency_types.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — انواع اقامت"
    },
    "roles.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — نقش‌ها"
    },
    "roles.delete": {
      "actionLabel": "حذف",
      "description": "حذف — نقش‌ها"
    },
    "roles.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — نقش‌ها"
    },
    "roles.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — نقش‌ها"
    },
    "rooms.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — اتاق‌ها"
    },
    "rooms.delete": {
      "actionLabel": "حذف",
      "description": "حذف — اتاق‌ها"
    },
    "rooms.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — اتاق‌ها"
    },
    "rooms.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — اتاق‌ها"
    },
    "schedule_slots.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — زمان‌بندی"
    },
    "schedule_slots.delete": {
      "actionLabel": "حذف",
      "description": "حذف — زمان‌بندی"
    },
    "schedule_slots.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — زمان‌بندی"
    },
    "schedule_slots.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — زمان‌بندی"
    },
    "school_branding.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — برندینگ مکتب"
    },
    "school_branding.delete": {
      "actionLabel": "حذف",
      "description": "حذف — برندینگ مکتب"
    },
    "school_branding.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — برندینگ مکتب"
    },
    "school_branding.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — برندینگ مکتب"
    },
    "schools.access_all": {
      "actionLabel": "دسترسی به همه مکتب‌ها",
      "description": "دسترسی به همه مکتب‌ها — مکتب‌ها"
    },
    "schools.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — مکتب‌ها"
    },
    "schools.delete": {
      "actionLabel": "حذف",
      "description": "حذف — مکتب‌ها"
    },
    "schools.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — مکتب‌ها"
    },
    "schools.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — مکتب‌ها"
    },
    "short_term_courses.close": {
      "actionLabel": "بستن",
      "description": "بستن — کورس‌های کوتاه‌مدت"
    },
    "short_term_courses.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — کورس‌های کوتاه‌مدت"
    },
    "short_term_courses.delete": {
      "actionLabel": "حذف",
      "description": "حذف — کورس‌های کوتاه‌مدت"
    },
    "short_term_courses.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — کورس‌های کوتاه‌مدت"
    },
    "short_term_courses.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — کورس‌های کوتاه‌مدت"
    },
    "staff.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — کارمندان"
    },
    "staff.delete": {
      "actionLabel": "حذف",
      "description": "حذف — کارمندان"
    },
    "staff.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — کارمندان"
    },
    "staff.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — کارمندان"
    },
    "staff_documents.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — اسناد کارمندان"
    },
    "staff_documents.delete": {
      "actionLabel": "حذف",
      "description": "حذف — اسناد کارمندان"
    },
    "staff_documents.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — اسناد کارمندان"
    },
    "staff_documents.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — اسناد کارمندان"
    },
    "staff_reports.export": {
      "actionLabel": "صدور",
      "description": "صدور — گزارش کارمندان"
    },
    "staff_reports.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — گزارش کارمندان"
    },
    "staff_types.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — انواع کارمند"
    },
    "staff_types.delete": {
      "actionLabel": "حذف",
      "description": "حذف — انواع کارمند"
    },
    "staff_types.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — انواع کارمند"
    },
    "staff_types.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — انواع کارمند"
    },
    "student_admissions.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — پذیرش شاگردان"
    },
    "student_admissions.delete": {
      "actionLabel": "حذف",
      "description": "حذف — پذیرش شاگردان"
    },
    "student_admissions.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — پذیرش شاگردان"
    },
    "student_admissions.report": {
      "actionLabel": "گزارش",
      "description": "گزارش — پذیرش شاگردان"
    },
    "student_admissions.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — پذیرش شاگردان"
    },
    "student_discipline_records.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — سوابق انضباطی"
    },
    "student_discipline_records.delete": {
      "actionLabel": "حذف",
      "description": "حذف — سوابق انضباطی"
    },
    "student_discipline_records.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — سوابق انضباطی"
    },
    "student_discipline_records.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — سوابق انضباطی"
    },
    "student_documents.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — اسناد شاگردان"
    },
    "student_documents.delete": {
      "actionLabel": "حذف",
      "description": "حذف — اسناد شاگردان"
    },
    "student_documents.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — اسناد شاگردان"
    },
    "student_documents.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — اسناد شاگردان"
    },
    "student_educational_history.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — سابقه تحصیلی"
    },
    "student_educational_history.delete": {
      "actionLabel": "حذف",
      "description": "حذف — سابقه تحصیلی"
    },
    "student_educational_history.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — سابقه تحصیلی"
    },
    "student_educational_history.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — سابقه تحصیلی"
    },
    "student_reports.export": {
      "actionLabel": "صدور",
      "description": "صدور — گزارش شاگردان"
    },
    "student_reports.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — گزارش شاگردان"
    },
    "students.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — شاگردان"
    },
    "students.delete": {
      "actionLabel": "حذف",
      "description": "حذف — شاگردان"
    },
    "students.import": {
      "actionLabel": "ورود",
      "description": "ورود — شاگردان"
    },
    "students.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — شاگردان"
    },
    "students.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — شاگردان"
    },
    "subjects.assign": {
      "actionLabel": "تخصیص",
      "description": "تخصیص — مضامین"
    },
    "subjects.copy": {
      "actionLabel": "رونوشت",
      "description": "رونوشت — مضامین"
    },
    "subjects.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — مضامین"
    },
    "subjects.delete": {
      "actionLabel": "حذف",
      "description": "حذف — مضامین"
    },
    "subjects.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — مضامین"
    },
    "subjects.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — مضامین"
    },
    "subscription.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — اشتراک"
    },
    "teacher_subject_assignments.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — تخصیص معلم به مضمون"
    },
    "teacher_subject_assignments.delete": {
      "actionLabel": "حذف",
      "description": "حذف — تخصیص معلم به مضمون"
    },
    "teacher_subject_assignments.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — تخصیص معلم به مضمون"
    },
    "teacher_subject_assignments.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — تخصیص معلم به مضمون"
    },
    "teacher_timetable_preferences.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — ترجیحات جدول معلم"
    },
    "teacher_timetable_preferences.delete": {
      "actionLabel": "حذف",
      "description": "حذف — ترجیحات جدول معلم"
    },
    "teacher_timetable_preferences.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — ترجیحات جدول معلم"
    },
    "teacher_timetable_preferences.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — ترجیحات جدول معلم"
    },
    "teachers.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — معلمان"
    },
    "teachers.delete": {
      "actionLabel": "حذف",
      "description": "حذف — معلمان"
    },
    "teachers.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — معلمان"
    },
    "teachers.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — معلمان"
    },
    "timetables.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — جداول زمانی"
    },
    "timetables.delete": {
      "actionLabel": "حذف",
      "description": "حذف — جداول زمانی"
    },
    "timetables.export": {
      "actionLabel": "صدور",
      "description": "صدور — جداول زمانی"
    },
    "timetables.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — جداول زمانی"
    },
    "timetables.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — جداول زمانی"
    },
    "users.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — کاربران"
    },
    "users.delete": {
      "actionLabel": "حذف",
      "description": "حذف — کاربران"
    },
    "users.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — کاربران"
    },
    "users.reset_password": {
      "actionLabel": "بازنشانی رمز",
      "description": "بازنشانی رمز — کاربران"
    },
    "users.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — کاربران"
    },
    "website_domains.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — دامنه‌های وب"
    },
    "website_domains.delete": {
      "actionLabel": "حذف",
      "description": "حذف — دامنه‌های وب"
    },
    "website_domains.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — دامنه‌های وب"
    },
    "website_domains.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — دامنه‌های وب"
    },
    "website_events.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — رویدادهای وب"
    },
    "website_events.delete": {
      "actionLabel": "حذف",
      "description": "حذف — رویدادهای وب"
    },
    "website_events.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — رویدادهای وب"
    },
    "website_events.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — رویدادهای وب"
    },
    "website_media.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — رسانه وب"
    },
    "website_media.delete": {
      "actionLabel": "حذف",
      "description": "حذف — رسانه وب"
    },
    "website_media.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — رسانه وب"
    },
    "website_media.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — رسانه وب"
    },
    "website_menus.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — منوهای وب"
    },
    "website_menus.delete": {
      "actionLabel": "حذف",
      "description": "حذف — منوهای وب"
    },
    "website_menus.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — منوهای وب"
    },
    "website_menus.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — منوهای وب"
    },
    "website_pages.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — صفحات وب"
    },
    "website_pages.delete": {
      "actionLabel": "حذف",
      "description": "حذف — صفحات وب"
    },
    "website_pages.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — صفحات وب"
    },
    "website_pages.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — صفحات وب"
    },
    "website_posts.create": {
      "actionLabel": "ایجاد",
      "description": "ایجاد — پست‌های وب"
    },
    "website_posts.delete": {
      "actionLabel": "حذف",
      "description": "حذف — پست‌های وب"
    },
    "website_posts.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — پست‌های وب"
    },
    "website_posts.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — پست‌های وب"
    },
    "website_settings.read": {
      "actionLabel": "خواندن",
      "description": "خواندن — تنظیمات وب"
    },
    "website_settings.update": {
      "actionLabel": "ویرایش",
      "description": "ویرایش — تنظیمات وب"
    }
  }
};
