/* eslint-disable max-len */
/**
 * Auto-generated by scripts/i18n/generate-permissions-management-catalog.mjs
 * Source: scripts/i18n/_permissions-meta.json (from PermissionSeeder.php via dump-permissions-meta.php)
 * Do not edit by hand — regenerate after backend permission changes.
 */
import type { PermissionsManagementCatalog } from './types';

export const permissionsManagementCatalogPs: PermissionsManagementCatalog = {
  "roles": {
    "admin": {
      "title": "Administrator",
      "description": "د ټولو ښوونیزو ځانګړتیاوو بشپړ لاسرسی لري (د ښوونځي کچې)."
    },
    "organization_admin": {
      "title": "د سازمان Administrator",
      "description": "د سازمان لپاره د ټولو ځانګړتیاوو بشپړ Administrator."
    },
    "staff": {
      "title": "کارکوونکی",
      "description": "د دفتري چارو محدود لاسرسی؛ مالي او فیس یوازې د لوستلو لپاره تر هغه چې جلا اجازه ورکړل شي."
    },
    "teacher": {
      "title": "ښوونکی",
      "description": "د تعلیمي منځپانګې او د زده‌کوونکو معلوماتو لاسرسی."
    },
    "exam_controller": {
      "title": "د ازموینې کنټرولر",
      "description": "د ازموینو بشپړ مدیریت (چیرې چې محدودیت شته)."
    },
    "accountant": {
      "title": "محاسب",
      "description": "بشپړ مالي، فیس او څو اسعارو لاسرسی."
    },
    "hostel_manager": {
      "title": "د لیلې مدیر",
      "description": "د خونو ټاکلو او راپورونو مدیریت."
    },
    "librarian": {
      "title": "کتابتونچی",
      "description": "زده‌کوونکو او کارکوونکو ته کتاب ورکړه او بیرته اخیستل؛ کتابتون او اسناد."
    },
    "website_admin": {
      "title": "د ویب پاڼې Administrator",
      "description": "د عامه ویب پاڼې بشپړ منځپانګه او تنظیمات."
    },
    "website_editor": {
      "title": "د ویب پاڼې سمونګر",
      "description": "مخونه، پوسټونه، پیښې او مینو سمول."
    },
    "website_media": {
      "title": "د ویب رسنیو مدیر",
      "description": "یوازې د رسنیو کتابتون مدیریت."
    },
    "organization_hr_admin": {
      "title": "د سازمان د بشري سرچینو Administrator",
      "description": "بشپړ HR، معاش او اړونده سازماني لاسرسی."
    },
    "hr_officer": {
      "title": "د بشري سرچینو افسر",
      "description": "کارکوونکي او د دندو ټاکنې مدیریت."
    },
    "payroll_officer": {
      "title": "د معاش افسر",
      "description": "د معاش پروسې او راپورونه."
    },
    "principal": {
      "title": "مشر",
      "description": "د HR او ښوونیزو ډیټا لوستل یوازې."
    }
  },
  "featureSections": {
    "students": "زده‌کوونکي",
    "staff": "کارکوونکي",
    "classes": "ټولګي",
    "subjects": "مضامین",
    "exams": "ازموینې",
    "exams_full": "ازموینې (بشپړ)",
    "grades": "درجې",
    "attendance": "حاضري",
    "finance": "مالي",
    "fees": "فیس",
    "multi_currency": "څو اسعاره",
    "dms": "د اسنادو مدیریت",
    "events": "پیښې",
    "library": "کتابتون",
    "hostel": "لیله",
    "graduation": "فراغت",
    "id_cards": "پېژند پاڼې",
    "assets": "شتمنۍ",
    "org_hr_core": "د سازمان بشري سرچینې",
    "org_hr_payroll": "د سازمان معاش",
    "org_hr_analytics": "د بشري سرچینو راپورونه",
    "org_finance": "د سازمان مالي",
    "leave_management": "رخصتۍ",
    "other": "نور"
  },
  "permissions": {
    "academic_years.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — تعلیمي کلونه"
    },
    "academic_years.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — تعلیمي کلونه"
    },
    "academic_years.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — تعلیمي کلونه"
    },
    "academic_years.update": {
      "actionLabel": "سمول",
      "description": "سمول — تعلیمي کلونه"
    },
    "activity_logs.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — د فعالیت یادښتونه"
    },
    "asset_categories.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — د شتمنۍ کټګورۍ"
    },
    "asset_categories.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — د شتمنۍ کټګورۍ"
    },
    "asset_categories.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — د شتمنۍ کټګورۍ"
    },
    "asset_categories.update": {
      "actionLabel": "سمول",
      "description": "سمول — د شتمنۍ کټګورۍ"
    },
    "assets.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — شتمنۍ"
    },
    "assets.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — شتمنۍ"
    },
    "assets.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — شتمنۍ"
    },
    "assets.update": {
      "actionLabel": "سمول",
      "description": "سمول — شتمنۍ"
    },
    "attendance_sessions.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — د حاضرۍ ناستې"
    },
    "attendance_sessions.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — د حاضرۍ ناستې"
    },
    "attendance_sessions.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — د حاضرۍ ناستې"
    },
    "attendance_sessions.report": {
      "actionLabel": "راپور",
      "description": "راپور — د حاضرۍ ناستې"
    },
    "attendance_sessions.update": {
      "actionLabel": "سمول",
      "description": "سمول — د حاضرۍ ناستې"
    },
    "buildings.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — ودانۍ"
    },
    "buildings.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — ودانۍ"
    },
    "buildings.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — ودانۍ"
    },
    "buildings.update": {
      "actionLabel": "سمول",
      "description": "سمول — ودانۍ"
    },
    "certificate_templates.activate": {
      "actionLabel": "فعالول",
      "description": "فعالول — د سند قالبونه"
    },
    "certificate_templates.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — د سند قالبونه"
    },
    "certificate_templates.deactivate": {
      "actionLabel": "غیرفعالول",
      "description": "غیرفعالول — د سند قالبونه"
    },
    "certificate_templates.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — د سند قالبونه"
    },
    "certificate_templates.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — د سند قالبونه"
    },
    "certificate_templates.update": {
      "actionLabel": "سمول",
      "description": "سمول — د سند قالبونه"
    },
    "certificates.issue": {
      "actionLabel": "صادرول",
      "description": "صادرول — سندونه"
    },
    "certificates.print": {
      "actionLabel": "چاپ",
      "description": "چاپ — سندونه"
    },
    "certificates.revoke": {
      "actionLabel": "لغوه",
      "description": "لغوه — سندونه"
    },
    "classes.assign": {
      "actionLabel": "ټاکل",
      "description": "ټاکل — ټولګي"
    },
    "classes.copy": {
      "actionLabel": "کاپي",
      "description": "کاپي — ټولګي"
    },
    "classes.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — ټولګي"
    },
    "classes.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — ټولګي"
    },
    "classes.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — ټولګي"
    },
    "classes.update": {
      "actionLabel": "سمول",
      "description": "سمول — ټولګي"
    },
    "course_attendance.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — د کورس حاضري"
    },
    "course_attendance.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — د کورس حاضري"
    },
    "course_attendance.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — د کورس حاضري"
    },
    "course_attendance.update": {
      "actionLabel": "سمول",
      "description": "سمول — د کورس حاضري"
    },
    "course_documents.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — د کورس اسناد"
    },
    "course_documents.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — د کورس اسناد"
    },
    "course_documents.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — د کورس اسناد"
    },
    "course_documents.update": {
      "actionLabel": "سمول",
      "description": "سمول — د کورس اسناد"
    },
    "course_student_discipline_records.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — د کورس زده‌کوونکو انضباط"
    },
    "course_student_discipline_records.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — د کورس زده‌کوونکو انضباط"
    },
    "course_student_discipline_records.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — د کورس زده‌کوونکو انضباط"
    },
    "course_student_discipline_records.update": {
      "actionLabel": "سمول",
      "description": "سمول — د کورس زده‌کوونکو انضباط"
    },
    "course_students.copy_to_main": {
      "actionLabel": "اصلي ته کاپي",
      "description": "اصلي ته کاپي — د کورس زده‌کوونکي"
    },
    "course_students.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — د کورس زده‌کوونکي"
    },
    "course_students.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — د کورس زده‌کوونکي"
    },
    "course_students.enroll_from_main": {
      "actionLabel": "اصلي څخه نوم لیکنه",
      "description": "اصلي څخه نوم لیکنه — د کورس زده‌کوونکي"
    },
    "course_students.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — د کورس زده‌کوونکي"
    },
    "course_students.report": {
      "actionLabel": "راپور",
      "description": "راپور — د کورس زده‌کوونکي"
    },
    "course_students.update": {
      "actionLabel": "سمول",
      "description": "سمول — د کورس زده‌کوونکي"
    },
    "currencies.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — اسعار"
    },
    "currencies.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — اسعار"
    },
    "currencies.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — اسعار"
    },
    "currencies.update": {
      "actionLabel": "سمول",
      "description": "سمول — اسعار"
    },
    "dms.archive.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — DMS — ارشیف"
    },
    "dms.archive.search": {
      "actionLabel": "لټون",
      "description": "لټون — DMS — ارشیف"
    },
    "dms.departments.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — DMS — برخې"
    },
    "dms.departments.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — DMS — برخې"
    },
    "dms.departments.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — DMS — برخې"
    },
    "dms.departments.update": {
      "actionLabel": "سمول",
      "description": "سمول — DMS — برخې"
    },
    "dms.files.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — DMS — فایلونه"
    },
    "dms.files.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — DMS — فایلونه"
    },
    "dms.files.download": {
      "actionLabel": "ډاونلوډ",
      "description": "ډاونلوډ — DMS — فایلونه"
    },
    "dms.files.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — DMS — فایلونه"
    },
    "dms.files.update": {
      "actionLabel": "سمول",
      "description": "سمول — DMS — فایلونه"
    },
    "dms.incoming.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — DMS — راغلي لیکنې"
    },
    "dms.incoming.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — DMS — راغلي لیکنې"
    },
    "dms.incoming.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — DMS — راغلي لیکنې"
    },
    "dms.incoming.update": {
      "actionLabel": "سمول",
      "description": "سمول — DMS — راغلي لیکنې"
    },
    "dms.letter_types.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — DMS — د لیک ډولونه"
    },
    "dms.letter_types.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — DMS — د لیک ډولونه"
    },
    "dms.letter_types.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — DMS — د لیک ډولونه"
    },
    "dms.letter_types.update": {
      "actionLabel": "سمول",
      "description": "سمول — DMS — د لیک ډولونه"
    },
    "dms.letterheads.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — DMS — لترهدونه"
    },
    "dms.letterheads.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — DMS — لترهدونه"
    },
    "dms.letterheads.manage": {
      "actionLabel": "مدیریت",
      "description": "مدیریت — DMS — لترهدونه"
    },
    "dms.letterheads.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — DMS — لترهدونه"
    },
    "dms.letterheads.update": {
      "actionLabel": "سمول",
      "description": "سمول — DMS — لترهدونه"
    },
    "dms.outgoing.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — DMS — وتونکي لیکنې"
    },
    "dms.outgoing.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — DMS — وتونکي لیکنې"
    },
    "dms.outgoing.generate_pdf": {
      "actionLabel": "PDF جوړول",
      "description": "PDF جوړول — DMS — وتونکي لیکنې"
    },
    "dms.outgoing.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — DMS — وتونکي لیکنې"
    },
    "dms.outgoing.update": {
      "actionLabel": "سمول",
      "description": "سمول — DMS — وتونکي لیکنې"
    },
    "dms.reports.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — DMS — راپورونه"
    },
    "dms.settings.manage": {
      "actionLabel": "مدیریت",
      "description": "مدیریت — DMS — تنظیمات"
    },
    "dms.settings.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — DMS — تنظیمات"
    },
    "dms.templates.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — DMS — قالبونه"
    },
    "dms.templates.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — DMS — قالبونه"
    },
    "dms.templates.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — DMS — قالبونه"
    },
    "dms.templates.update": {
      "actionLabel": "سمول",
      "description": "سمول — DMS — قالبونه"
    },
    "donors.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — بسپنه ورکوونکي"
    },
    "donors.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — بسپنه ورکوونکي"
    },
    "donors.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — بسپنه ورکوونکي"
    },
    "donors.update": {
      "actionLabel": "سمول",
      "description": "سمول — بسپنه ورکوونکي"
    },
    "event_checkins.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — د پیښې ننوت"
    },
    "event_checkins.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — د پیښې ننوت"
    },
    "event_checkins.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — د پیښې ننوت"
    },
    "event_checkins.update": {
      "actionLabel": "سمول",
      "description": "سمول — د پیښې ننوت"
    },
    "event_guests.checkin": {
      "actionLabel": "ننوت",
      "description": "ننوت — مېلمان"
    },
    "event_guests.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — مېلمان"
    },
    "event_guests.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — مېلمان"
    },
    "event_guests.import": {
      "actionLabel": "واردول",
      "description": "واردول — مېلمان"
    },
    "event_guests.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — مېلمان"
    },
    "event_guests.update": {
      "actionLabel": "سمول",
      "description": "سمول — مېلمان"
    },
    "event_types.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — د پیښې ډولونه"
    },
    "event_types.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — د پیښې ډولونه"
    },
    "event_types.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — د پیښې ډولونه"
    },
    "event_types.update": {
      "actionLabel": "سمول",
      "description": "سمول — د پیښې ډولونه"
    },
    "events.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — پیښې"
    },
    "events.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — پیښې"
    },
    "events.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — پیښې"
    },
    "events.update": {
      "actionLabel": "سمول",
      "description": "سمول — پیښې"
    },
    "exam_classes.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — د ازموینې ټولګي"
    },
    "exam_classes.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — د ازموینې ټولګي"
    },
    "exam_classes.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — د ازموینې ټولګي"
    },
    "exam_classes.update": {
      "actionLabel": "سمول",
      "description": "سمول — د ازموینې ټولګي"
    },
    "exam_documents.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — د ازموینې اسناد"
    },
    "exam_documents.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — د ازموینې اسناد"
    },
    "exam_documents.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — د ازموینې اسناد"
    },
    "exam_documents.update": {
      "actionLabel": "سمول",
      "description": "سمول — د ازموینې اسناد"
    },
    "exam_results.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — د ازموینې پایلې"
    },
    "exam_results.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — د ازموینې پایلې"
    },
    "exam_results.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — د ازموینې پایلې"
    },
    "exam_results.update": {
      "actionLabel": "سمول",
      "description": "سمول — د ازموینې پایلې"
    },
    "exam_students.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — د ازموینې زده‌کوونکي"
    },
    "exam_students.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — د ازموینې زده‌کوونکي"
    },
    "exam_students.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — د ازموینې زده‌کوونکي"
    },
    "exam_students.update": {
      "actionLabel": "سمول",
      "description": "سمول — د ازموینې زده‌کوونکي"
    },
    "exam_subjects.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — د ازموینې مضامین"
    },
    "exam_subjects.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — د ازموینې مضامین"
    },
    "exam_subjects.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — د ازموینې مضامین"
    },
    "exam_subjects.update": {
      "actionLabel": "سمول",
      "description": "سمول — د ازموینې مضامین"
    },
    "exam_times.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — د ازموینې وختونه"
    },
    "exam_times.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — د ازموینې وختونه"
    },
    "exam_times.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — د ازموینې وختونه"
    },
    "exam_times.update": {
      "actionLabel": "سمول",
      "description": "سمول — د ازموینې وختونه"
    },
    "exam_types.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — د ازموینې ډولونه"
    },
    "exam_types.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — د ازموینې ډولونه"
    },
    "exam_types.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — د ازموینې ډولونه"
    },
    "exam_types.update": {
      "actionLabel": "سمول",
      "description": "سمول — د ازموینې ډولونه"
    },
    "exams.assign": {
      "actionLabel": "ټاکل",
      "description": "ټاکل — ازموینې"
    },
    "exams.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — ازموینې"
    },
    "exams.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — ازموینې"
    },
    "exams.enroll_students": {
      "actionLabel": "زده‌کوونکي نوم لیکنه",
      "description": "زده‌کوونکي نوم لیکنه — ازموینې"
    },
    "exams.enter_marks": {
      "actionLabel": "نمرې ثبت",
      "description": "نمرې ثبت — ازموینې"
    },
    "exams.manage": {
      "actionLabel": "مدیریت",
      "description": "مدیریت — ازموینې"
    },
    "exams.manage_attendance": {
      "actionLabel": "حاضري مدیریت",
      "description": "حاضري مدیریت — ازموینې"
    },
    "exams.manage_timetable": {
      "actionLabel": "مهالویش",
      "description": "مهالویش — ازموینې"
    },
    "exams.numbers.print": {
      "actionLabel": "شمېرې چاپ",
      "description": "شمېرې چاپ — ازموینې"
    },
    "exams.papers.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — ازموینې — کاغذونه/تستونه"
    },
    "exams.papers.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — ازموینې — کاغذونه/تستونه"
    },
    "exams.papers.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — ازموینې — کاغذونه/تستونه"
    },
    "exams.papers.update": {
      "actionLabel": "سمول",
      "description": "سمول — ازموینې — کاغذونه/تستونه"
    },
    "exams.questions.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — ازموینې — پوښتنې"
    },
    "exams.questions.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — ازموینې — پوښتنې"
    },
    "exams.questions.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — ازموینې — پوښتنې"
    },
    "exams.questions.update": {
      "actionLabel": "سمول",
      "description": "سمول — ازموینې — پوښتنې"
    },
    "exams.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — ازموینې"
    },
    "exams.roll_numbers.assign": {
      "actionLabel": "د رول نمبر ټاکل",
      "description": "د رول نمبر ټاکل — ازموینې"
    },
    "exams.roll_numbers.read": {
      "actionLabel": "د رول نمبر لوستل",
      "description": "د رول نمبر لوستل — ازموینې"
    },
    "exams.secret_numbers.assign": {
      "actionLabel": "د پټ نمبر ټاکل",
      "description": "د پټ نمبر ټاکل — ازموینې"
    },
    "exams.secret_numbers.read": {
      "actionLabel": "د پټ نمبر لوستل",
      "description": "د پټ نمبر لوستل — ازموینې"
    },
    "exams.update": {
      "actionLabel": "سمول",
      "description": "سمول — ازموینې"
    },
    "exams.view_attendance_reports": {
      "actionLabel": "د حاضرۍ راپورونه",
      "description": "د حاضرۍ راپورونه — ازموینې"
    },
    "exams.view_class_reports": {
      "actionLabel": "د ټولګي راپورونه",
      "description": "د ټولګي راپورونه — ازموینې"
    },
    "exams.view_consolidated_reports": {
      "actionLabel": "ګډ راپورونه",
      "description": "ګډ راپورونه — ازموینې"
    },
    "exams.view_grade_cards": {
      "actionLabel": "درجې کارتونه",
      "description": "درجې کارتونه — ازموینې"
    },
    "exams.view_reports": {
      "actionLabel": "راپورونه",
      "description": "راپورونه — ازموینې"
    },
    "exams.view_student_reports": {
      "actionLabel": "د زده‌کوونکي راپورونه",
      "description": "د زده‌کوونکي راپورونه — ازموینې"
    },
    "exchange_rates.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — د اسعارو نرخونه"
    },
    "exchange_rates.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — د اسعارو نرخونه"
    },
    "exchange_rates.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — د اسعارو نرخونه"
    },
    "exchange_rates.update": {
      "actionLabel": "سمول",
      "description": "سمول — د اسعارو نرخونه"
    },
    "expense_categories.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — د لګښت کټګورۍ"
    },
    "expense_categories.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — د لګښت کټګورۍ"
    },
    "expense_categories.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — د لګښت کټګورۍ"
    },
    "expense_categories.update": {
      "actionLabel": "سمول",
      "description": "سمول — د لګښت کټګورۍ"
    },
    "expense_entries.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — د لګښت ثبتونه"
    },
    "expense_entries.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — د لګښت ثبتونه"
    },
    "expense_entries.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — د لګښت ثبتونه"
    },
    "expense_entries.update": {
      "actionLabel": "سمول",
      "description": "سمول — د لګښت ثبتونه"
    },
    "fees.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — فیس"
    },
    "fees.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — فیس"
    },
    "fees.exceptions.approve": {
      "actionLabel": "تصویب",
      "description": "تصویب — فیس — استثناوې"
    },
    "fees.exceptions.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — فیس — استثناوې"
    },
    "fees.payments.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — فیس — تادیات"
    },
    "fees.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — فیس"
    },
    "fees.update": {
      "actionLabel": "سمول",
      "description": "سمول — فیس"
    },
    "finance_accounts.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — مالي حسابونه"
    },
    "finance_accounts.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — مالي حسابونه"
    },
    "finance_accounts.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — مالي حسابونه"
    },
    "finance_accounts.update": {
      "actionLabel": "سمول",
      "description": "سمول — مالي حسابونه"
    },
    "finance_documents.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — مالي اسناد"
    },
    "finance_documents.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — مالي اسناد"
    },
    "finance_documents.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — مالي اسناد"
    },
    "finance_documents.update": {
      "actionLabel": "سمول",
      "description": "سمول — مالي اسناد"
    },
    "finance_donors.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — مالي بسپنه ورکوونکي"
    },
    "finance_donors.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — مالي بسپنه ورکوونکي"
    },
    "finance_donors.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — مالي بسپنه ورکوونکي"
    },
    "finance_donors.update": {
      "actionLabel": "سمول",
      "description": "سمول — مالي بسپنه ورکوونکي"
    },
    "finance_expense.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — لګښت"
    },
    "finance_expense.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — لګښت"
    },
    "finance_expense.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — لګښت"
    },
    "finance_expense.update": {
      "actionLabel": "سمول",
      "description": "سمول — لګښت"
    },
    "finance_income.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — عاید"
    },
    "finance_income.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — عاید"
    },
    "finance_income.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — عاید"
    },
    "finance_income.update": {
      "actionLabel": "سمول",
      "description": "سمول — عاید"
    },
    "finance_projects.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — مالي پروژې"
    },
    "finance_projects.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — مالي پروژې"
    },
    "finance_projects.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — مالي پروژې"
    },
    "finance_projects.update": {
      "actionLabel": "سمول",
      "description": "سمول — مالي پروژې"
    },
    "finance_reports.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — مالي راپورونه"
    },
    "grades.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — درجې"
    },
    "grades.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — درجې"
    },
    "grades.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — درجې"
    },
    "grades.update": {
      "actionLabel": "سمول",
      "description": "سمول — درجې"
    },
    "graduation_batches.approve": {
      "actionLabel": "تصویب",
      "description": "تصویب — د فراغت ډلې"
    },
    "graduation_batches.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — د فراغت ډلې"
    },
    "graduation_batches.generate_students": {
      "actionLabel": "زده‌کوونکي تولید",
      "description": "زده‌کوونکي تولید — د فراغت ډلې"
    },
    "graduation_batches.issue": {
      "actionLabel": "صادرول",
      "description": "صادرول — د فراغت ډلې"
    },
    "graduation_batches.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — د فراغت ډلې"
    },
    "help_center.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — مرکز مرستې"
    },
    "help_center.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — مرکز مرستې"
    },
    "help_center.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — مرکز مرستې"
    },
    "help_center.read_staff": {
      "actionLabel": "د کارکوونکو لوستل",
      "description": "د کارکوونکو لوستل — مرکز مرستې"
    },
    "help_center.update": {
      "actionLabel": "سمول",
      "description": "سمول — مرکز مرستې"
    },
    "hostel.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — لیله"
    },
    "hostel.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — لیله"
    },
    "hostel.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — لیله"
    },
    "hostel.update": {
      "actionLabel": "سمول",
      "description": "سمول — لیله"
    },
    "hr_assignments.approve": {
      "actionLabel": "تصویب",
      "description": "تصویب — د بشري سرچینو ټاکنې"
    },
    "hr_assignments.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — د بشري سرچینو ټاکنې"
    },
    "hr_assignments.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — د بشري سرچینو ټاکنې"
    },
    "hr_assignments.update": {
      "actionLabel": "سمول",
      "description": "سمول — د بشري سرچینو ټاکنې"
    },
    "hr_payroll.approve": {
      "actionLabel": "تصویب",
      "description": "تصویب — معاش"
    },
    "hr_payroll.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — معاش"
    },
    "hr_payroll.export": {
      "actionLabel": "صادرول",
      "description": "صادرول — معاش"
    },
    "hr_payroll.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — معاش"
    },
    "hr_payroll.run": {
      "actionLabel": "پلي کول",
      "description": "پلي کول — معاش"
    },
    "hr_reports.export": {
      "actionLabel": "صادرول",
      "description": "صادرول — د بشري سرچینو راپورونه"
    },
    "hr_reports.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — د بشري سرچینو راپورونه"
    },
    "hr_staff.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — بشري سرچینې"
    },
    "hr_staff.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — بشري سرچینې"
    },
    "hr_staff.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — بشري سرچینې"
    },
    "hr_staff.update": {
      "actionLabel": "سمول",
      "description": "سمول — بشري سرچینې"
    },
    "id_cards.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — پېژند پاڼې"
    },
    "id_cards.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — پېژند پاڼې"
    },
    "id_cards.export": {
      "actionLabel": "صادرول",
      "description": "صادرول — پېژند پاڼې"
    },
    "id_cards.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — پېژند پاڼې"
    },
    "id_cards.update": {
      "actionLabel": "سمول",
      "description": "سمول — پېژند پاڼې"
    },
    "income_categories.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — د عاید کټګورۍ"
    },
    "income_categories.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — د عاید کټګورۍ"
    },
    "income_categories.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — د عاید کټګورۍ"
    },
    "income_categories.update": {
      "actionLabel": "سمول",
      "description": "سمول — د عاید کټګورۍ"
    },
    "income_entries.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — د عاید ثبتونه"
    },
    "income_entries.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — د عاید ثبتونه"
    },
    "income_entries.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — د عاید ثبتونه"
    },
    "income_entries.update": {
      "actionLabel": "سمول",
      "description": "سمول — د عاید ثبتونه"
    },
    "issued_certificates.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — صادر شوي سندونه"
    },
    "leave_requests.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — د رخصتۍ غوښتنې"
    },
    "leave_requests.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — د رخصتۍ غوښتنې"
    },
    "leave_requests.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — د رخصتۍ غوښتنې"
    },
    "leave_requests.update": {
      "actionLabel": "سمول",
      "description": "سمول — د رخصتۍ غوښتنې"
    },
    "library_books.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — کتابتون کتابونه"
    },
    "library_books.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — کتابتون کتابونه"
    },
    "library_books.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — کتابتون کتابونه"
    },
    "library_books.update": {
      "actionLabel": "سمول",
      "description": "سمول — کتابتون کتابونه"
    },
    "library_categories.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — د کتابتون کټګورۍ"
    },
    "library_categories.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — د کتابتون کټګورۍ"
    },
    "library_categories.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — د کتابتون کټګورۍ"
    },
    "library_categories.update": {
      "actionLabel": "سمول",
      "description": "سمول — د کتابتون کټګورۍ"
    },
    "library_loans.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — د کتابونو قرضې"
    },
    "library_loans.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — د کتابونو قرضې"
    },
    "library_loans.update": {
      "actionLabel": "سمول",
      "description": "سمول — د کتابونو قرضې"
    },
    "notifications.manage_preferences": {
      "actionLabel": "غوره توبونه",
      "description": "غوره توبونه — خبرتیاوې"
    },
    "notifications.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — خبرتیاوې"
    },
    "notifications.update": {
      "actionLabel": "سمول",
      "description": "سمول — خبرتیاوې"
    },
    "org_finance.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — د سازمان مالي"
    },
    "org_finance.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — د سازمان مالي"
    },
    "organizations.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — سازمانونه"
    },
    "organizations.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — سازمانونه"
    },
    "organizations.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — سازمانونه"
    },
    "organizations.update": {
      "actionLabel": "سمول",
      "description": "سمول — سازمانونه"
    },
    "permissions.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — اجازې"
    },
    "permissions.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — اجازې"
    },
    "permissions.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — اجازې"
    },
    "permissions.update": {
      "actionLabel": "سمول",
      "description": "سمول — اجازې"
    },
    "phonebook.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — د تلیفون کتاب"
    },
    "profiles.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — پروفایلونه"
    },
    "profiles.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — پروفایلونه"
    },
    "profiles.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — پروفایلونه"
    },
    "profiles.update": {
      "actionLabel": "سمول",
      "description": "سمول — پروفایلونه"
    },
    "report_templates.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — د راپور قالبونه"
    },
    "report_templates.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — د راپور قالبونه"
    },
    "report_templates.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — د راپور قالبونه"
    },
    "report_templates.update": {
      "actionLabel": "سمول",
      "description": "سمول — د راپور قالبونه"
    },
    "reports.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — راپورونه"
    },
    "residency_types.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — د اوسیدو ډولونه"
    },
    "residency_types.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — د اوسیدو ډولونه"
    },
    "residency_types.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — د اوسیدو ډولونه"
    },
    "residency_types.update": {
      "actionLabel": "سمول",
      "description": "سمول — د اوسیدو ډولونه"
    },
    "roles.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — رولونه"
    },
    "roles.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — رولونه"
    },
    "roles.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — رولونه"
    },
    "roles.update": {
      "actionLabel": "سمول",
      "description": "سمول — رولونه"
    },
    "rooms.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — خونې"
    },
    "rooms.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — خونې"
    },
    "rooms.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — خونې"
    },
    "rooms.update": {
      "actionLabel": "سمول",
      "description": "سمول — خونې"
    },
    "schedule_slots.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — د مهالویش ځایونه"
    },
    "schedule_slots.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — د مهالویش ځایونه"
    },
    "schedule_slots.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — د مهالویش ځایونه"
    },
    "schedule_slots.update": {
      "actionLabel": "سمول",
      "description": "سمول — د مهالویش ځایونه"
    },
    "school_branding.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — د ښوونځي برانډینګ"
    },
    "school_branding.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — د ښوونځي برانډینګ"
    },
    "school_branding.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — د ښوونځي برانډینګ"
    },
    "school_branding.update": {
      "actionLabel": "سمول",
      "description": "سمول — د ښوونځي برانډینګ"
    },
    "schools.access_all": {
      "actionLabel": "ټولو ته لاسرسی",
      "description": "ټولو ته لاسرسی — ښوونځي"
    },
    "schools.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — ښوونځي"
    },
    "schools.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — ښوونځي"
    },
    "schools.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — ښوونځي"
    },
    "schools.update": {
      "actionLabel": "سمول",
      "description": "سمول — ښوونځي"
    },
    "short_term_courses.close": {
      "actionLabel": "تړل",
      "description": "تړل — لنډ مهاله کورسونه"
    },
    "short_term_courses.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — لنډ مهاله کورسونه"
    },
    "short_term_courses.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — لنډ مهاله کورسونه"
    },
    "short_term_courses.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — لنډ مهاله کورسونه"
    },
    "short_term_courses.update": {
      "actionLabel": "سمول",
      "description": "سمول — لنډ مهاله کورسونه"
    },
    "staff.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — کارکوونکي"
    },
    "staff.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — کارکوونکي"
    },
    "staff.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — کارکوونکي"
    },
    "staff.update": {
      "actionLabel": "سمول",
      "description": "سمول — کارکوونکي"
    },
    "staff_documents.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — د کارکوونکو اسناد"
    },
    "staff_documents.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — د کارکوونکو اسناد"
    },
    "staff_documents.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — د کارکوونکو اسناد"
    },
    "staff_documents.update": {
      "actionLabel": "سمول",
      "description": "سمول — د کارکوونکو اسناد"
    },
    "staff_reports.export": {
      "actionLabel": "صادرول",
      "description": "صادرول — د کارکوونکو راپورونه"
    },
    "staff_reports.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — د کارکوونکو راپورونه"
    },
    "staff_types.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — د کارکوونکو ډولونه"
    },
    "staff_types.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — د کارکوونکو ډولونه"
    },
    "staff_types.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — د کارکوونکو ډولونه"
    },
    "staff_types.update": {
      "actionLabel": "سمول",
      "description": "سمول — د کارکوونکو ډولونه"
    },
    "student_admissions.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — د زده‌کوونکو ثبت"
    },
    "student_admissions.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — د زده‌کوونکو ثبت"
    },
    "student_admissions.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — د زده‌کوونکو ثبت"
    },
    "student_admissions.report": {
      "actionLabel": "راپور",
      "description": "راپور — د زده‌کوونکو ثبت"
    },
    "student_admissions.update": {
      "actionLabel": "سمول",
      "description": "سمول — د زده‌کوونکو ثبت"
    },
    "student_discipline_records.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — د انضباط یادښتونه"
    },
    "student_discipline_records.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — د انضباط یادښتونه"
    },
    "student_discipline_records.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — د انضباط یادښتونه"
    },
    "student_discipline_records.update": {
      "actionLabel": "سمول",
      "description": "سمول — د انضباط یادښتونه"
    },
    "student_documents.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — د زده‌کوونکو اسناد"
    },
    "student_documents.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — د زده‌کوونکو اسناد"
    },
    "student_documents.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — د زده‌کوونکو اسناد"
    },
    "student_documents.update": {
      "actionLabel": "سمول",
      "description": "سمول — د زده‌کوونکو اسناد"
    },
    "student_educational_history.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — تعلیمي پېښې"
    },
    "student_educational_history.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — تعلیمي پېښې"
    },
    "student_educational_history.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — تعلیمي پېښې"
    },
    "student_educational_history.update": {
      "actionLabel": "سمول",
      "description": "سمول — تعلیمي پېښې"
    },
    "student_reports.export": {
      "actionLabel": "صادرول",
      "description": "صادرول — د زده‌کوونکو راپورونه"
    },
    "student_reports.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — د زده‌کوونکو راپورونه"
    },
    "students.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — زده‌کوونکي"
    },
    "students.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — زده‌کوونکي"
    },
    "students.import": {
      "actionLabel": "واردول",
      "description": "واردول — زده‌کوونکي"
    },
    "students.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — زده‌کوونکي"
    },
    "students.update": {
      "actionLabel": "سمول",
      "description": "سمول — زده‌کوونکي"
    },
    "subjects.assign": {
      "actionLabel": "ټاکل",
      "description": "ټاکل — مضامین"
    },
    "subjects.copy": {
      "actionLabel": "کاپي",
      "description": "کاپي — مضامین"
    },
    "subjects.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — مضامین"
    },
    "subjects.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — مضامین"
    },
    "subjects.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — مضامین"
    },
    "subjects.update": {
      "actionLabel": "سمول",
      "description": "سمول — مضامین"
    },
    "subscription.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — اشتراک"
    },
    "teacher_subject_assignments.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — د ښوونکي مضمون ټاکنې"
    },
    "teacher_subject_assignments.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — د ښوونکي مضمون ټاکنې"
    },
    "teacher_subject_assignments.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — د ښوونکي مضمون ټاکنې"
    },
    "teacher_subject_assignments.update": {
      "actionLabel": "سمول",
      "description": "سمول — د ښوونکي مضمون ټاکنې"
    },
    "teacher_timetable_preferences.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — د مهالویش غوره توبونه"
    },
    "teacher_timetable_preferences.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — د مهالویش غوره توبونه"
    },
    "teacher_timetable_preferences.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — د مهالویش غوره توبونه"
    },
    "teacher_timetable_preferences.update": {
      "actionLabel": "سمول",
      "description": "سمول — د مهالویش غوره توبونه"
    },
    "teachers.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — ښوونکي"
    },
    "teachers.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — ښوونکي"
    },
    "teachers.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — ښوونکي"
    },
    "teachers.update": {
      "actionLabel": "سمول",
      "description": "سمول — ښوونکي"
    },
    "timetables.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — مهالویشونه"
    },
    "timetables.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — مهالویشونه"
    },
    "timetables.export": {
      "actionLabel": "صادرول",
      "description": "صادرول — مهالویشونه"
    },
    "timetables.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — مهالویشونه"
    },
    "timetables.update": {
      "actionLabel": "سمول",
      "description": "سمول — مهالویشونه"
    },
    "users.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — کارونکي"
    },
    "users.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — کارونکي"
    },
    "users.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — کارونکي"
    },
    "users.reset_password": {
      "actionLabel": "پټنوم بیا تنظیم",
      "description": "پټنوم بیا تنظیم — کارونکي"
    },
    "users.update": {
      "actionLabel": "سمول",
      "description": "سمول — کارونکي"
    },
    "website_domains.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — د ویب شپونې"
    },
    "website_domains.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — د ویب شپونې"
    },
    "website_domains.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — د ویب شپونې"
    },
    "website_domains.update": {
      "actionLabel": "سمول",
      "description": "سمول — د ویب شپونې"
    },
    "website_events.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — د ویب پیښې"
    },
    "website_events.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — د ویب پیښې"
    },
    "website_events.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — د ویب پیښې"
    },
    "website_events.update": {
      "actionLabel": "سمول",
      "description": "سمول — د ویب پیښې"
    },
    "website_media.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — ویب رسنۍ"
    },
    "website_media.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — ویب رسنۍ"
    },
    "website_media.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — ویب رسنۍ"
    },
    "website_media.update": {
      "actionLabel": "سمول",
      "description": "سمول — ویب رسنۍ"
    },
    "website_menus.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — ویب مینو"
    },
    "website_menus.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — ویب مینو"
    },
    "website_menus.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — ویب مینو"
    },
    "website_menus.update": {
      "actionLabel": "سمول",
      "description": "سمول — ویب مینو"
    },
    "website_pages.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — ویب مخونه"
    },
    "website_pages.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — ویب مخونه"
    },
    "website_pages.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — ویب مخونه"
    },
    "website_pages.update": {
      "actionLabel": "سمول",
      "description": "سمول — ویب مخونه"
    },
    "website_posts.create": {
      "actionLabel": "جوړول",
      "description": "جوړول — ویب پوسټونه"
    },
    "website_posts.delete": {
      "actionLabel": "ړنګول",
      "description": "ړنګول — ویب پوسټونه"
    },
    "website_posts.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — ویب پوسټونه"
    },
    "website_posts.update": {
      "actionLabel": "سمول",
      "description": "سمول — ویب پوسټونه"
    },
    "website_settings.read": {
      "actionLabel": "لوستل",
      "description": "لوستل — د ویب تنظیمات"
    },
    "website_settings.update": {
      "actionLabel": "سمول",
      "description": "سمول — د ویب تنظیمات"
    }
  }
};
