/**
 * help-center page translations (en).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  helpCenter: {
    subtitle: "Find answers to your questions and learn how to use Nazim SMS",
    allArticles: "All Articles",
    allCategories: "All Categories",
    articleFound: "Here is the help article for this page",
    articleNotFound: "Article not found",
    articleNotFoundDescription: "The article you are looking for does not exist or has been removed.",
    articles: "Articles",
    articlesFound: "articles found",
    backToHelpCenter: "Back to Help Center",
    browseHelpCenter: "Browse Help Center",
    contextualHelp: "Get help",
    errorLoading: "Error loading help article",
    errorLoadingArticles: "Error loading articles",
    errorLoadingCategories: "Error loading categories",
    featuredArticles: "Featured Articles",
    linkCopied: "Link copied to clipboard!",
    noArticleFound: "No specific help article found for this page",
    noArticlesDescription: "Try adjusting your search or filters",
    noArticlesFound: "No articles found",
    popularArticles: "Popular Articles",
    relatedArticles: "Related Articles",
    share: "Share",
    thankYou: "Thank you for your feedback!",
    filters: "Filters",
    browseCategories: "Browse Categories",
    sortBy: "Sort by",
    sortRecent: "Most recent",
    sortPopular: "Most popular",
    sortAZ: "A → Z",
    categoryHint: "Pick a category to narrow results.",
    scanHint: "Browse articles, or search to jump straight to an answer.",
    needMoreHelp: "Need more help?",
    needMoreHelpDesc: "If you can't find what you need, contact support or ask your admin.",
    resetSearch: "Reset search",
    contactSupport: "Contact support",
    continueReading: "Continue reading",
    topMatches: "Top matches",
    tipEnter: "Enter to open • ↑↓ to navigate",
    activeFilters: "Active filters:",
    category: "Category",
    search: "Search",
    browseAll: "Browse all",
    minRead: "min",
    title: {
      helpCenterManagement: "Help Center Management"
    },
    viewFullArticle: "View Full Article",
    views: "views",
    wasThisHelpful: "Was this article helpful?",
    showingPage: "Showing page",
    of: "of",
    totalArticles: "Total articles",
    startSchoolSetupTour: "Start School Setup Tour",
    schoolSetupTourDescription: "Complete guide to setting up your school: school details, academic years, classes, and subjects"
  }
};
