/**
 * help-center page translations (fa).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  helpCenter: {
    subtitle: "پاسخ سوالات خود را بیابید و نحوه استفاده از نظام سیستم مدیریت مکتب را یاد بگیرید",
    allArticles: "همه مقالات",
    allCategories: "همه دسته‌بندی‌ها",
    articleFound: "مقاله یافت شد",
    articleNotFound: "مقاله یافت نشد",
    articleNotFoundDescription: "مقاله‌ای که به دنبال آن هستید وجود ندارد یا حذف شده است.",
    articles: "مقالات",
    articlesFound: "مقاله یافت شد",
    backToHelpCenter: "بازگشت به مرکز کمک",
    browseHelpCenter: "مرور مرکز کمک",
    contextualHelp: "دریافت کمک",
    errorLoading: "خطا در بارگذاری مقاله راهنما",
    errorLoadingArticles: "خطا در بارگذاری مقالات",
    errorLoadingCategories: "خطا در بارگذاری دسته‌بندی‌ها",
    featuredArticles: "مقالات ویژه",
    linkCopied: "لینک کاپی شد!",
    noArticleFound: "هیچ مقاله راهنمای خاصی برای این صفحه یافت نشد",
    noArticlesDescription: "سعی کنید جستجو یا فیلترهای خود را تغییر دهید",
    noArticlesFound: "هیچ مقاله‌ای یافت نشد",
    popularArticles: "مقالات محبوب",
    relatedArticles: "مقالات مرتبط",
    share: "اشتراک‌گذاری",
    thankYou: "تشکر از بازخورد شما!",
    filters: "فیلترها",
    browseCategories: "مرور دسته‌بندی‌ها",
    sortBy: "مرتب‌سازی بر اساس",
    sortRecent: "جدیدترین",
    sortPopular: "محبوب‌ترین",
    sortAZ: "الف → ی",
    categoryHint: "یک دسته‌بندی را برای محدود کردن نتایج انتخاب کنید.",
    scanHint: "مقالات را مرور کنید یا برای یافتن مستقیم پاسخ جستجو کنید.",
    needMoreHelp: "به کمک بیشتری نیاز دارید؟",
    needMoreHelpDesc: "اگر آنچه نیاز دارید را پیدا نکردید، با پشتیبانی تماس بگیرید یا از مدیر خود بپرسید.",
    resetSearch: "بازنشانی جستجو",
    contactSupport: "تماس با پشتیبانی",
    continueReading: "ادامه خواندن",
    topMatches: "بهترین مطابقت‌ها",
    tipEnter: "Enter برای باز کردن • ↑↓ برای پیمایش",
    activeFilters: "فیلترهای فعال:",
    category: "دسته‌بندی",
    search: "جستجو",
    browseAll: "مرور همه",
    minRead: "دقیقه",
    title: {
      helpCenterManagement: "مدیریت مرکز کمک"
    },
    viewFullArticle: "مشاهده کامل مقاله",
    views: "بازدید",
    wasThisHelpful: "آیا این مقاله مفید بود؟",
    showingPage: "نمایش صفحه",
    of: "از",
    totalArticles: "کل مقالات",
    startSchoolSetupTour: "شروع راهنمای تنظیم مکتب",
    schoolSetupTourDescription: "راهنمای کامل برای تنظیم مکتب شما: جزئیات مکتب، سال‌های تحصیلی، کلاس‌ها و مضامین"
  }
};
