/**
 * auth page translations (ar).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  auth: {
    confirmPassword: "Confirm Password",
    email: "Email",
    enterEmail: "Please enter your email address",
    enterEmailAndPassword: "Please enter both email and password",
    loggedInSuccessfully: "Logged in successfully!",
    noOrganizationsFound: "No organizations found. Please contact an administrator.",
    organization: "Organization",
    password: "Password",
    phone: "Phone",
    role: "الدور",
    selectRole: "اختر دورك",
    signInFailed: "Sign in failed. Please try again.",
    rateLimited: "محاولات تسجيل دخول كثيرة. يرجى المحاولة لاحقاً.",
    accountLocked: "الحساب مقفل. استخدم نسيت كلمة المرور لإعادة التعيين.",
    subtitle: "Access your school management system",
    title: "School Management System"
  }
};
