/**
 * auth page translations (en).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  auth: {
    confirmPassword: "Confirm Password",
    email: "Email",
    enterEmail: "Please enter your email address",
    enterEmailAndPassword: "Please enter both email and password",
    loggedInSuccessfully: "Logged in successfully!",
    noOrganizationsFound: "No organizations found. Please contact an administrator.",
    organization: "Organization",
    password: "Password",
    phone: "Phone",
    role: "Role",
    selectRole: "Select your role",
    signInFailed: "Sign in failed. Please try again.",
    rateLimited: "Too many login attempts. Please try again later.",
    accountLocked: "Account locked. Use Forgot password to reset.",
    subtitle: "Access your school management system",
    title: "School Management System"
  }
};
