/**
 * auth page translations (ps).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  auth: {
    confirmPassword: "پاسورډ تایید کړئ",
    email: "برېښنالیک",
    enterEmail: "مهرباني وکړئ خپل د برېښنالیک پته ولیکئ",
    enterEmailAndPassword: "مهرباني وکړئ برېښنالیک او پاسورډ دواړه ولیکئ",
    loggedInSuccessfully: "په بریالیتوب سره ننوتلاست!",
    noOrganizationsFound: "هیڅ اداره ونه موندل شوه. مهرباني وکړئ له مدیر سره اړیکه ونیسئ.",
    organization: "سازمان",
    password: "پاسورډ",
    phone: "ټیلیفون",
    role: "رول",
    selectRole: "خپل رول وټاکئ",
    signInFailed: "ننوتل ناکام شول. مهرباني وکړئ بیا هڅه وکړئ.",
    rateLimited: "ډیرې ننوتنې هڅې شوې. مهرباني وکړئ وروسته بیا هڅه وکړئ.",
    accountLocked: "حساب د ډیرو ناکامو ننوتنو له امله قفل شوی. په څو دقیقو کې بیا هڅه وکړئ، یا د پاسورډ ری سیټ لپاره «پاسورډ هېر شوی» وکاروئ.",
    subtitle: "خپل ناظم د دیني مدارسو د مالي او اداري چارو د تنظیم سیستم  ته لاسرسی ومومئ",
    title: "د ناظم د دیني مدارسو د مالي او اداري چارو د تنظیم سیستم"
  }
};
