/**
 * Shared termsOfService translations (en).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  termsOfService: {
    title: "Terms of Service",
    lastUpdated: "Last Updated: January 2026",
    introduction: {
      title: "Introduction",
      content: "These Terms explain how you may use Nazim Web (the “Platform”). By using the Platform, you agree to these Terms. If you do not agree, do not use the Platform."
    },
    acceptance: {
      title: "Acceptance of Terms",
      content: "By accessing or using the Platform, you confirm you understand and accept these Terms. If you are using the Platform for a school or organization, you confirm you have authority to accept these Terms on its behalf."
    },
    account: {
      title: "Account & Access",
      intro: "To use the Platform, you agree to:",
      accurate: "Provide correct and up-to-date account and school information",
      maintain: "Keep your login details safe and not share them publicly",
      notify: "Tell us quickly if you suspect unauthorized access",
      responsible: "Accept responsibility for actions taken from your account (including by staff users)"
    },
    use: {
      title: "Using the Platform",
      permitted: {
        title: "Permitted Use",
        content: "You may use the Platform only for lawful school, madrassa, educational, and administrative operations. You must follow applicable laws, school policies, and student privacy rules."
      },
      prohibited: {
        title: "Not Allowed",
        unauthorized: "Trying to access other schools’ data or restricted areas",
        malicious: "Uploading malware, harmful code, or doing security attacks",
        interfere: "Disrupting the Platform, servers, or network performance",
        violate: "Using the Platform for illegal activity, harassment, or abuse"
      }
    },
    subscription: {
      title: "Subscription, Billing & Cancellation",
      content: "Subscriptions are billed in advance (monthly or yearly). You will see pricing and limits inside the Platform or your invoice. If we change prices, we will provide notice before the change takes effect.",
      cancellation: "You can cancel anytime. Your access continues until the end of the current billing period. We do not provide refunds for unused time, except where required by law."
    },
    intellectualProperty: {
      title: "Intellectual Property",
      content: "We own the Platform, its design, and its software. You receive a limited right to use it during your subscription. You may not copy, resell, reverse engineer, or distribute the Platform without written permission."
    },
    liability: {
      title: "Limitations of Liability",
      content: "We work hard to keep the Platform reliable, but no online service is perfect. To the maximum extent allowed by law, we are not liable for indirect or consequential losses (such as lost profit, lost data, or business interruption). Our total liability is limited to the amount you paid to us in the 12 months before the claim."
    },
    termination: {
      title: "Suspension & Termination",
      content: "We may suspend or terminate access if you seriously violate these Terms, misuse the Platform, or do not pay overdue invoices. If access is terminated, your right to use the Platform ends immediately."
    },
    changes: {
      title: "Changes to Terms",
      content: "We may update these Terms as the Platform grows. If changes are important, we will notify you by email or inside the Platform. Continuing to use the Platform after the effective date means you accept the updated Terms."
    },
    contact: {
      title: "Contact Us",
      content: "Questions about these Terms? Contact us at support@nazimapp.com or through our contact form."
    }
  }
};
