/**
 * Shared termsOfService translations (ar).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  termsOfService: {
    acceptance: {
      content: "By accessing or using our platform, you acknowledge that you have read, understood, and agree to be bound by these Terms. If you do not agree to these Terms, you may not use our services.",
      title: "Acceptance of Terms"
    },
    account: {
      accurate: "Provide accurate and complete information",
      intro: "To use our services, you must:",
      maintain: "Maintain the security of your account credentials",
      notify: "Notify us immediately of any unauthorized access",
      responsible: "Be responsible for all activities under your account",
      title: "Account Registration"
    },
    changes: {
      content: "We may modify these Terms at any time. We will notify you of any material changes by email or through the platform. Your continued use of the platform after such changes constitutes acceptance of the modified Terms.",
      title: "Changes to Terms"
    },
    contact: {
      content: "If you have any questions about these Terms of Service, please contact us at support@nazimapp.com or through our contact form.",
      title: "Contact Us"
    },
    intellectualProperty: {
      content: "All content, features, and functionality of the platform are owned by Nazim School Management System and are protected by copyright, trademark, and other intellectual property laws. You may not copy, modify, or distribute any part of the platform without our written permission.",
      title: "Intellectual Property"
    },
    introduction: {
      content: "These Terms of Service (\"Terms\") govern your access to and use of the Nazim School Management System platform. By using our services, you agree to be bound by these Terms. Please read them carefully.",
      title: "Introduction"
    },
    lastUpdated: "Last Updated: January 2026",
    liability: {
      content: "To the maximum extent permitted by law, Nazim School Management System shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the platform. Our total liability shall not exceed the amount you paid for the services in the 12 months preceding the claim.",
      title: "Limitation of Liability"
    },
    subscription: {
      cancellation: "You may cancel your subscription at any time. Cancellation will take effect at the end of your current billing period.",
      content: "Subscription fees are billed in advance on a monthly or annual basis. All fees are non-refundable except as required by law. We reserve the right to change our pricing with 30 days notice.",
      title: "Subscription and Payment"
    },
    termination: {
      content: "We reserve the right to suspend or terminate your account at any time for violation of these Terms or for any other reason. Upon termination, your right to use the platform will immediately cease.",
      title: "Termination"
    },
    title: "Terms of Service",
    use: {
      permitted: {
        content: "You may use our services for lawful educational and administrative purposes only. You agree to use the platform in accordance with all applicable laws and regulations.",
        title: "Permitted Use"
      },
      prohibited: {
        interfere: "Interference with the platform's operation",
        malicious: "Introduction of viruses, malware, or harmful code",
        title: "Prohibited Activities",
        unauthorized: "Unauthorized access to other accounts or systems",
        violate: "Violation of any applicable laws or regulations"
      },
      title: "Use of Services"
    }
  }
};
