/**
 * guards page translations (ar).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  guards: {
    accessDenied: "تم رفض الوصول",
    checkingPermissions: "جارٍ التحقق من الصلاحيات...",
    loading: "جارٍ التحميل...",
    organizationRequiredMessage: "يجب تعيين حسابك إلى منظمة للوصول إلى هذا المورد. يرجى الاتصال بمدير.",
    requiredPermission: "الإذن المطلوب:"
  }
};
