/**
 * guards page translations (fa).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  guards: {
    accessDenied: "دسترسی رد شد",
    checkingPermissions: "در حال بررسی مجوزها...",
    loading: "در حال بارگذاری...",
    organizationRequiredMessage: "حساب شما باید به یک سازمان اختصاص داده شود تا به این منبع دسترسی داشته باشید. لطفاً با مدیر تماس بگیرید.",
    requiredPermission: "مجوز مورد نیاز:"
  }
};
