/**
 * guards page translations (ps).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  guards: {
    accessDenied: "لاسرسی رد شو",
    checkingPermissions: "د اجازې چک کول...",
    loading: "ترلاسه کیږي....",
    organizationRequiredMessage: "ستاسو حساب باید یوې ادارې ته ځانګړی شوی وي. مهرباني وکړئ له مدیر سره اړیکه ونیسئ.",
    requiredPermission: "اړینه اجازه:"
  }
};
