<?php

namespace Database\Factories;

use App\Models\Organization;
use App\Models\SchoolBranding;
use App\Models\Staff;
use App\Models\StaffType;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Str;

class StaffFactory extends Factory
{
    protected $model = Staff::class;

    public function definition(): array
    {
        $organization = Organization::factory();

        return [
            'id' => (string) Str::uuid(),
            'organization_id' => $organization,
            'school_id' => SchoolBranding::factory()->for($organization),
            'employee_id' => fake()->unique()->numerify('EMP-####'),
            'staff_code' => null, // Auto-generated by model
            'staff_type' => 'teacher',
            'staff_type_id' => StaffType::factory()->state(function (array $attributes) {
                return [
                    'organization_id' => $attributes['organization_id'],
                    'school_id' => $attributes['school_id'],
                ];
            }),
            'first_name' => fake()->firstName(),
            'father_name' => fake()->firstNameMale(),
            'grandfather_name' => fake()->firstNameMale(),
            'tazkira_number' => fake()->numerify('##########'),
            'birth_year' => (string) fake()->numberBetween(1970, 2000),
            'birth_date' => fake()->date(),
            'phone_number' => fake()->phoneNumber(),
            'email' => fake()->unique()->safeEmail(),
            'home_address' => fake()->address(),
            'origin_province' => fake()->state(),
            'origin_district' => fake()->city(),
            'origin_village' => fake()->streetName(),
            'current_province' => fake()->state(),
            'current_district' => fake()->city(),
            'current_village' => fake()->streetName(),
            'religious_education' => fake()->randomElement(['bachelors', 'masters']),
            'religious_university' => fake()->company(),
            'religious_graduation_year' => (string) fake()->numberBetween(1990, 2020),
            'religious_department' => fake()->word(),
            'modern_education' => fake()->randomElement(['bachelors', 'masters']),
            'modern_school_university' => fake()->company(),
            'modern_graduation_year' => (string) fake()->numberBetween(1990, 2020),
            'modern_department' => fake()->word(),
            'teaching_section' => fake()->randomElement(['primary', 'secondary']),
            'position' => fake()->jobTitle(),
            'duty' => fake()->randomElement(['full_time', 'part_time']),
            'salary' => (string) fake()->numberBetween(10000, 50000),
            'status' => 'active',
            'picture_url' => null,
            'document_urls' => [],
            'notes' => null,
        ];
    }

    public function teacher(): static
    {
        return $this->state(function (array $attributes) {
            $staffType = StaffType::firstOrCreate([
                'code' => 'teacher',
                'organization_id' => $attributes['organization_id'],
                'school_id' => $attributes['school_id'],
            ], [
                'name' => 'Teacher',
            ]);

            return [
                'staff_type' => 'teacher',
                'staff_type_id' => $staffType->id,
            ];
        });
    }

    public function inactive(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => 'inactive',
        ]);
    }
}
