<?php

namespace Database\Factories;

use App\Models\Organization;
use App\Models\Student;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Str;

class StudentFactory extends Factory
{
    protected $model = Student::class;

    public function definition(): array
    {
        return [
            'id' => (string) Str::uuid(),
            'organization_id' => Organization::factory(),
            'school_id' => null,
            'card_number' => fake()->unique()->numerify('########'),
            'admission_no' => fake()->unique()->numerify('ADM####'),
            'student_code' => null, // Auto-generated by model
            'full_name' => fake()->name(),
            'father_name' => fake()->name('male'),
            'grandfather_name' => fake()->name('male'),
            'mother_name' => fake()->name('female'),
            'gender' => fake()->randomElement(['male', 'female']),
            'birth_year' => fake()->numberBetween(2000, 2015),
            'birth_date' => fake()->date(),
            'age' => fake()->numberBetween(5, 20),
            'admission_year' => now()->year,
            'orig_province' => fake()->state(),
            'orig_district' => fake()->city(),
            'orig_village' => fake()->streetName(),
            'curr_province' => fake()->state(),
            'curr_district' => fake()->city(),
            'curr_village' => fake()->streetName(),
            'nationality' => 'Afghan',
            'preferred_language' => 'en',
            'previous_school' => fake()->company(),
            'guardian_name' => fake()->name(),
            'guardian_relation' => fake()->randomElement(['father', 'mother', 'uncle', 'aunt']),
            'guardian_phone' => fake()->phoneNumber(),
            'guardian_tazkira' => fake()->numerify('##########'),
            'guardian_picture_path' => null,
            'home_address' => fake()->address(),
            'zamin_name' => fake()->name(),
            'zamin_phone' => fake()->phoneNumber(),
            'zamin_tazkira' => fake()->numerify('##########'),
            'zamin_address' => fake()->address(),
            'applying_grade' => fake()->numberBetween(1, 12),
            'is_orphan' => fake()->boolean(20),
            'admission_fee_status' => 'paid',
            'student_status' => 'active',
            'disability_status' => null,
            'emergency_contact_name' => fake()->name(),
            'emergency_contact_phone' => fake()->phoneNumber(),
            'family_income' => fake()->numberBetween(5000, 50000),
            'picture_path' => null,
        ];
    }

    public function orphan(): static
    {
        return $this->state(fn (array $attributes) => [
            'is_orphan' => true,
        ]);
    }

    public function inactive(): static
    {
        return $this->state(fn (array $attributes) => [
            'student_status' => 'inactive',
        ]);
    }

    public function graduated(): static
    {
        return $this->state(fn (array $attributes) => [
            'student_status' => 'graduated',
        ]);
    }
}
