/**
 * Shared pagination translations (ar).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  pagination: {
    entries: "إدخال",
    noEntries: "لا توجد إدخالات",
    of: "من",
    rowsPerPage: "صفوف في الصفحة",
    showing: "عرض",
    to: "إلى",
    total: "المجموع",
    filtered: "filtered"
  }
};
