/**
 * Shared pagination translations (fa).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  pagination: {
    entries: "مدخل‌ها",
    noEntries: "هیچ مدخلی نیست",
    of: "از",
    rowsPerPage: "ردیف در صفحه",
    showing: "نمایش",
    to: "تا",
    total: "مجموع",
    filtered: "فیلتر شده"
  }
};
