/**
 * maintenance page translations (ps).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  maintenance: {
    affectedServices: "اغیزمن شوي خدمتونه",
    autoRefresh: "دا پاڼه به په هرو ۳۰ ثانیو کې تازه کیږي",
    defaultMessage: "موږ د سیسټم په ساتنه بوخت یو. ژر بېرته راګرځو!",
    info: "د خنډ له امله بخښنه غواړو. زموږ ټیم د سیسټم په فعالولو کار کوي. ستاسو له صبر څخه مننه.",
    inProgress: "ترمیم جریان لري",
    progress: "د پرمختګ کچه",
    refresh: "پاڼه تازه کړئ",
    remaining: "پاتې",
    retry: "بیا نښلول",
    retryAfter: "تاسو کولی شئ بیا هڅه وکړئ په",
    scheduledEnd: "د بشپړېدو اټکلي وخت",
    seconds: "ثانیو کې",
    startedAt: "پیلیږی په",
    teamWorking: "زموږ ټیم د ستونزې په حل کولو بوخت دی",
    title: "سیسټم تر ترمیم لاندې دی"
  }
};
