/**
 * maintenance page translations (fa - Dari).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  maintenance: {
    affectedServices: "خدمات متأثر",
    autoRefresh: "این صفحه هر ۳۰ ثانیه به طور خودکار به‌روز می‌شود",
    defaultMessage: "در حال انجام نگهداری برنامه‌ریزی‌شده هستیم. به زودی برمی‌گردیم!",
    info: "از هرگونه ناراحتی عذر می‌خواهیم. تیم ما برای بازگرداندن سرویس در اسرع وقت تلاش می‌کند. از شکیبایی شما سپاسگزاریم.",
    inProgress: "نگهداری در حال انجام",
    progress: "پیشرفت نگهداری",
    refresh: "به‌روزرسانی صفحه",
    remaining: "باقی‌مانده",
    retry: "تلاش مجدد برای اتصال",
    retryAfter: "می‌توانید دوباره تلاش کنید بعد از",
    scheduledEnd: "تکمیل برنامه‌ریزی‌شده",
    seconds: "ثانیه",
    startedAt: "شروع نگهداری",
    teamWorking: "تیم ما برای بازگرداندن سرویس تلاش می‌کند",
    title: "سیستم تحت نگهداری"
  }
};
