/**
 * maintenance page translations (ar).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  maintenance: {
    affectedServices: "الخدمات المتأثرة",
    autoRefresh: "ستتم إعادة تحميل هذه الصفحة تلقائياً كل 30 ثانية",
    defaultMessage: "نقوم بإجراء صيانة مجدولة. سنعود قريباً!",
    info: "نعتذر عن أي إزعاج. يعمل فريقنا بجد لاستعادة الخدمة في أسرع وقت ممكن. شكراً لصبركم.",
    inProgress: "الصيانة قيد التنفيذ",
    progress: "تقدم الصيانة",
    refresh: "تحديث الصفحة",
    remaining: "متبقي",
    retry: "إعادة الاتصال",
    retryAfter: "يمكنك المحاولة مرة أخرى خلال",
    scheduledEnd: "وقت الإكمال المجدول",
    seconds: "ثانية",
    startedAt: "بدأت الصيانة",
    teamWorking: "يعمل فريقنا بجد لاستعادة الخدمة",
    title: "النظام قيد الصيانة"
  }
};
