/**
 * maintenance page translations (fa).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  maintenance: {
    affectedServices: "Affected Services",
    autoRefresh: "This page will automatically refresh every 30 seconds",
    defaultMessage: "We are performing scheduled maintenance. We'll be back soon!",
    info: "We apologize for any inconvenience. Our team is working hard to restore service as quickly as possible. Thank you for your patience.",
    inProgress: "Maintenance in Progress",
    progress: "Maintenance Progress",
    refresh: "Refresh Page",
    remaining: "remaining",
    retry: "Retry Connection",
    retryAfter: "You can try again in",
    scheduledEnd: "Scheduled Completion",
    seconds: "seconds",
    startedAt: "Maintenance Started",
    teamWorking: "Our team is working hard to restore service",
    title: "System Under Maintenance"
  }
};
