/**
 * platform page translations (en).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  platform: {
    loginAudit: {
      title: 'Login Audit',
      description: 'View and manage login attempts, locked accounts, and security alerts.',
      alerts: 'Brute-force alerts',
      alertsEmpty: 'No alerts in the last hour.',
      alertsLastHour: 'IP/email in last hour',
      lockedAccounts: 'Locked accounts',
      lockedAccountsDescription: 'Due to failed attempts',
      lockedEmpty: 'No locked accounts.',
      unlock: 'Unlock',
      mainTable: 'Login attempts',
      filters: {
        dateRange: 'Date range',
        status: 'Status',
        statusAll: 'All',
        statusSuccess: 'Success',
        statusFailure: 'Failure',
        email: 'Email',
        organization: 'Organization',
        ipAddress: 'IP address',
        context: 'Login context',
        contextMain: 'Main app',
        contextPlatform: 'Platform admin',
      },
      columns: {
        dateTime: 'Date/Time',
        email: 'Email',
        status: 'Status',
        failureReason: 'Failure reason',
        organization: 'Organization',
        school: 'School',
        ip: 'IP',
        context: 'Context',
        userAgent: 'User agent',
      },
      failureReasons: {
        user_not_found: 'User not found',
        invalid_password: 'Invalid password',
        account_inactive: 'Account inactive',
        account_locked: 'Account locked',
        token_creation_failed: 'Token creation failed',
        rate_limited: 'Rate limited',
        validation_failed: 'Invalid email format or missing fields',
      },
      viewInTable: 'View in table',
      export: 'Export CSV',
      exportSuccess: 'Export started',
      exportFailed: 'Export failed',
      unlockSuccess: 'Account unlocked successfully',
      unlockFailed: 'Failed to unlock account',
    },
    restoreType: {
      label: "Restore Type",
      databaseOnly: "Database Only (Preserve Current Files)",
      databaseAndFiles: "Database + Files (Complete Restore)",
      databaseOnlyDescription: "This will replace only the database data. Current storage files will be preserved.",
      databaseAndFilesDescription: "This will replace ALL current data in your database and storage with the data from this backup."
    }
  },
  platformLandingOffers: {
    title: "Landing Page Offers",
    subtitle: "Highlight discount codes on the public pricing page and control offer countdowns.",
    columns: {
      code: "Code",
      plan: "Plan",
      discount: "Discount",
      validity: "Validity",
      landing: "Landing",
      actions: "Actions"
    },
    live: "Live",
    allPlans: "All Plans",
    specificPlan: "Specific Plan",
    ends: "Ends",
    noExpiry: "No expiry",
    visible: "Visible",
    hidden: "Hidden",
    configure: "Configure",
    empty: "No discount codes found.",
    loading: "Loading discount codes...",
    expired: "Expired",
    saveSettings: "Save Settings",
    dialog: {
      title: "Landing Offer Settings",
      description: "Control how this discount appears on the public pricing cards.",
      showTitle: "Show on landing page",
      showDescription: "Enables the badge, discounted price, and countdown timer.",
      badgeLabel: "Landing Badge Label",
      badgePlaceholder: "Limited Offer",
      messageLabel: "Landing Message",
      messagePlaceholder: "Short highlight for the offer",
      validFrom: "Valid From",
      validUntil: "Valid Until",
      noStartDate: "No start date",
      noExpiryDate: "No expiry date"
    }
  }
};
