/**
 * platform page translations (fa).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  platform: {
    loginAudit: {
      title: 'دسترسی ورود',
      description: 'تلاش‌های ورود، حساب‌های قفل شده و هشدارهای امنیتی را مشاهده کنید.',
      alerts: 'هشدارهای حمله',
      alertsEmpty: 'هیچ هشداری در ساعت گذشته نیست.',
      alertsLastHour: 'IP/ایمیل در ساعت گذشته',
      lockedAccounts: 'حساب‌های قفل شده',
      lockedAccountsDescription: 'به دلیل تلاش‌های ناموفق',
      lockedEmpty: 'حسابی قفل نشده است.',
      unlock: 'باز کردن',
      mainTable: 'تلاش‌های ورود',
      filters: {
        dateRange: 'بازه تاریخ',
        status: 'وضعیت',
        statusAll: 'همه',
        statusSuccess: 'موفق',
        statusFailure: 'ناموفق',
        email: 'ایمیل',
        organization: 'سازمان',
        ipAddress: 'آدرس IP',
        context: 'زمینه ورود',
        contextMain: 'برنامه اصلی',
        contextPlatform: 'مدیر پلتفرم',
      },
      columns: {
        dateTime: 'تاریخ/زمان',
        email: 'ایمیل',
        status: 'وضعیت',
        failureReason: 'دلیل شکست',
        organization: 'سازمان',
        school: 'مدرسه',
        ip: 'IP',
        context: 'زمینه',
        userAgent: 'کاربر ایجنت',
      },
      failureReasons: {
        user_not_found: 'کاربر یافت نشد',
        invalid_password: 'رمز عبور نامعتبر',
        account_inactive: 'حساب غیرفعال',
        account_locked: 'حساب قفل شده',
        token_creation_failed: 'ایجاد توکن ناموفق',
        rate_limited: 'محدودیت تعداد',
        validation_failed: 'فرمت ایمیل نامعتبر یا فیلدهای خالی',
      },
      viewInTable: 'مشاهده در جدول',
      export: 'برون‌بری CSV',
      exportSuccess: 'برون‌بری شروع شد',
      exportFailed: 'برون‌بری ناموفق',
      unlockSuccess: 'حساب با موفقیت باز شد',
      unlockFailed: 'باز کردن حساب ناموفق',
    },
    restoreType: {
      label: "نوع بازیابی",
      databaseOnly: "فقط پایگاه داده (حفظ فایل‌های فعلی)",
      databaseAndFiles: "پایگاه داده + فایل‌ها (بازیابی کامل)",
      databaseOnlyDescription: "این فقط داده‌های پایگاه داده را جایگزین می‌کند. فایل‌های ذخیره‌سازی فعلی حفظ خواهند شد.",
      databaseAndFilesDescription: "این تمام داده‌های فعلی در پایگاه داده و ذخیره‌سازی شما را با داده‌های این بکاپ جایگزین می‌کند."
    }
  }
};
