/**
 * platform page translations (fa).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  platform: {
    loginAudit: {
      title: 'دسترسی ورود',
      description: 'تلاش‌های ورود، حساب‌های قفل شده و هشدارهای امنیتی را مشاهده کنید.',
      alerts: 'هشدارهای حمله',
      alertsEmpty: 'هیچ هشداری در ساعت گذشته نیست.',
      alertsLastHour: 'IP/ایمیل در ساعت گذشته',
      lockedAccounts: 'حساب‌های قفل شده',
      lockedAccountsDescription: 'به دلیل تلاش‌های ناموفق',
      lockedEmpty: 'حسابی قفل نشده است.',
      unlock: 'باز کردن',
      mainTable: 'تلاش‌های ورود',
      filters: {
        dateRange: 'بازه تاریخ',
        status: 'وضعیت',
        statusAll: 'همه',
        statusSuccess: 'موفق',
        statusFailure: 'ناموفق',
        email: 'ایمیل',
        organization: 'سازمان',
        ipAddress: 'آدرس IP',
        context: 'زمینه ورود',
        contextMain: 'برنامه اصلی',
        contextPlatform: 'مدیر پلتفرم',
      },
      columns: {
        dateTime: 'تاریخ/زمان',
        email: 'ایمیل',
        status: 'وضعیت',
        failureReason: 'دلیل شکست',
        organization: 'سازمان',
        school: 'مدرسه',
        ip: 'آدرس IP',
        context: 'زمینه',
        userAgent: 'کاربر ایجنت',
      },
      failureReasons: {
        user_not_found: 'کاربر یافت نشد',
        invalid_password: 'رمز عبور نامعتبر',
        account_inactive: 'حساب غیرفعال',
        account_locked: 'حساب قفل شده',
        token_creation_failed: 'ایجاد توکن ناموفق',
        rate_limited: 'محدودیت تعداد',
        validation_failed: 'فرمت ایمیل نامعتبر یا فیلدهای خالی',
      },
      viewInTable: 'مشاهده در جدول',
      export: 'برون‌بری CSV',
      exportSuccess: 'برون‌بری شروع شد',
      exportFailed: 'برون‌بری ناموفق',
      unlockSuccess: 'حساب با موفقیت باز شد',
      unlockFailed: 'باز کردن حساب ناموفق',
    },
    restoreType: {
      label: "نوع بازیابی",
      databaseOnly: "فقط پایگاه داده (حفظ فایل‌های فعلی)",
      databaseAndFiles: "پایگاه داده + فایل‌ها (بازیابی کامل)",
      databaseOnlyDescription: "این فقط داده‌های پایگاه داده را جایگزین می‌کند. فایل‌های ذخیره‌سازی فعلی حفظ خواهند شد.",
      databaseAndFilesDescription: "این تمام داده‌های فعلی در پایگاه داده و ذخیره‌سازی شما را با داده‌های این بکاپ جایگزین می‌کند."
    }
  },
  platformLandingOffers: {
    title: "پیشنهادات صفحه فرود",
    subtitle: "کدهای تخفیف را در صفحه قیمت‌گذاری عمومی برجسته کنید و شمارش معکوس پیشنهادها را کنترل کنید.",
    columns: {
      code: "کد",
      plan: "پلان",
      discount: "تخفیف",
      validity: "اعتبار",
      landing: "فرود",
      actions: "اقدامات"
    },
    live: "زنده",
    allPlans: "همه پلان‌ها",
    specificPlan: "پلان مشخص",
    ends: "پایان",
    noExpiry: "بدون انقضا",
    visible: "قابل مشاهده",
    hidden: "مخفی",
    configure: "تنظیم",
    empty: "هیچ کد تخفیفی یافت نشد.",
    loading: "در حال بارگذاری کدهای تخفیف...",
    expired: "منقضی شده",
    saveSettings: "ذخیره تنظیمات",
    dialog: {
      title: "تنظیمات پیشنهاد فرود",
      description: "کنترل کنید این تخفیف چگونه روی کارت‌های قیمت‌گذاری عمومی نمایش داده شود.",
      showTitle: "نمایش در صفحه فرود",
      showDescription: "نشان، قیمت تخفیف‌خورده و زمان‌سنج شمارش معکوس را فعال می‌کند.",
      badgeLabel: "برچسب فرود",
      badgePlaceholder: "پیشنهاد محدود",
      messageLabel: "پیام فرود",
      messagePlaceholder: "نکته کوتاه برای پیشنهاد",
      validFrom: "معتبر از",
      validUntil: "معتبر تا",
      noStartDate: "بدون تاریخ شروع",
      noExpiryDate: "بدون تاریخ انقضا"
    }
  }
};
