/**
 * platform page translations (fa).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  platform: {
    restoreType: {
      label: "نوع بازیابی",
      databaseOnly: "فقط پایگاه داده (حفظ فایل‌های فعلی)",
      databaseAndFiles: "پایگاه داده + فایل‌ها (بازیابی کامل)",
      databaseOnlyDescription: "این فقط داده‌های پایگاه داده را جایگزین می‌کند. فایل‌های ذخیره‌سازی فعلی حفظ خواهند شد.",
      databaseAndFilesDescription: "این تمام داده‌های فعلی در پایگاه داده و ذخیره‌سازی شما را با داده‌های این بکاپ جایگزین می‌کند."
    }
  }
};
