/**
 * platform page translations (ps).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  platform: {
    loginAudit: {
      title: 'د ننوتلو معاینه',
      description: 'د ننوتلو هڅې، قفل شوي حسابونه او امنیتي خبرتیاوې وګورئ.',
      alerts: 'د بروټ فورس خبرتیاوې',
      alertsEmpty: 'په تیره ساعت کې هیڅ خبرتیا نشته.',
      alertsLastHour: 'IP/بریښنالیک په تیره ساعت کې',
      lockedAccounts: 'قفل شوي حسابونه',
      lockedAccountsDescription: 'د ناکامو هڅو له امله',
      lockedEmpty: 'قفل شوي حسابونه نشته.',
      unlock: 'خلاصول',
      mainTable: 'د ننوتلو هڅې',
      filters: {
        dateRange: 'د نیټې برخه',
        status: 'حالت',
        statusAll: 'ټول',
        statusSuccess: 'بریالی',
        statusFailure: 'ناکام',
        email: 'بریښنالیک',
        organization: 'ټولنه',
        ipAddress: 'IP پته',
        context: 'د ننوتلو سیاق',
        contextMain: 'اصلي اپلیکیشن',
        contextPlatform: 'پلیټفارم ادمین',
      },
      columns: {
        dateTime: 'نیټه/وخت',
        email: 'بریښنالیک',
        status: 'حالت',
        failureReason: 'د ناکامۍ دلیل',
        organization: 'ټولنه',
        school: 'ښوونځی',
        ip: 'IP',
        context: 'سیاق',
        userAgent: 'کارن ایجنټ',
      },
      failureReasons: {
        user_not_found: 'کارن ونه موندل شو',
        invalid_password: 'غلط پټنوم',
        account_inactive: 'حساب غیرفعال',
        account_locked: 'حساب قفل شوی',
        token_creation_failed: 'د ټوکن جوړول ناکام',
        rate_limited: 'د کچه محدودیت',
        validation_failed: 'د بریښنالیک بڼه غلطه یا غوښتنې ساحې ورک دي',
      },
      viewInTable: 'په جدول کې وګورئ',
      export: 'CSV صادرول',
      exportSuccess: 'صادرات پیل شو',
      exportFailed: 'صادرات ناکام شو',
      unlockSuccess: 'حساب په بریالیتوب سره خلاص شو',
      unlockFailed: 'حساب خلاصول ناکام شو',
    },
    restoreType: {
      label: "د بېرته راګرځولو ډول",
      databaseOnly: "یوازې ډیټابیس (اوسنۍ فایلونه وساتل)",
      databaseAndFiles: "ډیټابیس + فایلونه (بشپړ بېرته راګرځول)",
      databaseOnlyDescription: "دا به یوازې د ډیټابیس ډیټا بدل کړي. اوسنۍ ذخیره فایلونه به وساتل شي.",
      databaseAndFilesDescription: "دا به د بیک اپ څخه د ډیټابیس او ذخیره کولو ټول اوسنۍ ډیټا بدل کړي."
    }
  },
  platformLandingOffers: {
    title: "د لینډ پاڼې وړاندیزونه",
    subtitle: "په عامه نرخ پاڼه کې د تخفیف کوډونه وښایاست او د وړاندیز شمار معکوس کنټرول کړئ.",
    columns: {
      code: "کوډ",
      plan: "پلان",
      discount: "تخفیف",
      validity: "اعتبار",
      landing: "لینډ",
      actions: "کړنې"
    },
    live: "ژوندی",
    allPlans: "ټول پلانونه",
    specificPlan: "ځانګړی پلان",
    ends: "ختمیږي",
    noExpiry: "بې پای",
    visible: "ښکاره",
    hidden: "پټ",
    configure: "تنظیم",
    empty: "تخفیف کوډونه ونه موندل شول.",
    loading: "تخفیف کوډونه ترلاسه کیږي...",
    expired: "ختم شوی",
    saveSettings: "تنظیمات خوندي کړئ",
    dialog: {
      title: "د لینډ وړاندیز تنظیمات",
      description: "کنټرول کړئ چې دا تخفیف په عامه نرخ کارټونو کې څنګه ښکاره شي.",
      showTitle: "په لینډ پاڼه کې ښکاره کړئ",
      showDescription: "باډج، تخفیفي نرخ او شمار معکوس وخت نښه فعالوي.",
      badgeLabel: "د لینډ باډج لیبل",
      badgePlaceholder: "محدود وړاندیز",
      messageLabel: "د وړاندیز خبرتیا",
      messagePlaceholder: "د وړاندیز لپاره لنډه ښکارېدنه",
      validFrom: "له نیټې اعتبار لري",
      validUntil: "تر نیټې اعتبار لري",
      noStartDate: "د پیل نیټه نشته",
      noExpiryDate: "د پای نیټه نشته"
    }
  }
};
