import type * as Api from '@/types/api/courseStudent';
import type { CourseStudent } from '@/types/domain/courseStudent';

export const mapCourseStudentApiToDomain = (student: Api.CourseStudent): CourseStudent => ({
  id: student.id,
  organizationId: student.organization_id,
  courseId: student.course_id,
  mainStudentId: student.main_student_id ?? null,
  admissionNo: student.admission_no,
  registrationDate: student.registration_date,
  completionStatus: student.completion_status,
  completionDate: student.completion_date ?? null,
  grade: student.grade ?? null,
  certificateIssued: student.certificate_issued,
  certificateIssuedDate: student.certificate_issued_date ?? null,
  feePaid: student.fee_paid,
  feePaidDate: student.fee_paid_date ?? null,
  feeAmount: student.fee_amount ?? null,
  fullName: student.full_name,
  fatherName: student.father_name ?? null,
  grandfatherName: student.grandfather_name ?? null,
  motherName: student.mother_name ?? null,
  gender: student.gender ?? null,
  birthYear: student.birth_year ?? null,
  birthDate: student.birth_date ?? null,
  age: student.age ?? null,
  origProvince: student.orig_province ?? null,
  origDistrict: student.orig_district ?? null,
  origVillage: student.orig_village ?? null,
  currProvince: student.curr_province ?? null,
  currDistrict: student.curr_district ?? null,
  currVillage: student.curr_village ?? null,
  nationality: student.nationality ?? null,
  preferredLanguage: student.preferred_language ?? null,
  guardianName: student.guardian_name ?? null,
  guardianRelation: student.guardian_relation ?? null,
  guardianPhone: student.guardian_phone ?? null,
  homeAddress: student.home_address ?? null,
  picturePath: student.picture_path ?? null,
  isOrphan: student.is_orphan ?? null,
  disabilityStatus: student.disability_status ?? null,
  createdAt: student.created_at,
  updatedAt: student.updated_at,
});

export const mapCourseStudentDomainToInsert = (student: Partial<CourseStudent>): Api.CourseStudentInsert => ({
  organization_id: student.organizationId!,
  course_id: student.courseId!,
  admission_no: student.admissionNo && student.admissionNo.trim() !== '' ? student.admissionNo : null, // Allow null/undefined for auto-generation
  registration_date: student.registrationDate!,
  completion_status: student.completionStatus,
  fee_paid: student.feePaid,
  fee_amount: student.feeAmount ?? null,
  full_name: student.fullName!,
  guardian_name: student.guardianName ?? null,
  guardian_phone: student.guardianPhone ?? null,
  home_address: student.homeAddress ?? null,
});

export const mapCourseStudentDomainToUpdate = (
  student: Partial<CourseStudent>,
): Api.CourseStudentUpdate => ({
  course_id: student.courseId,
  admission_no: student.admissionNo,
  registration_date: student.registrationDate,
  completion_status: student.completionStatus,
  completion_date: student.completionDate,
  grade: student.grade,
  certificate_issued: student.certificateIssued,
  certificate_issued_date: student.certificateIssuedDate,
  fee_paid: student.feePaid,
  fee_paid_date: student.feePaidDate,
  fee_amount: student.feeAmount,
  full_name: student.fullName,
  guardian_name: student.guardianName,
  guardian_phone: student.guardianPhone,
  home_address: student.homeAddress,
});
