/**
 * profile-management page translations (ps).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  profileManagement: {
    allProfiles: "ټول پروفایلونه",
    editMyProfile: "زما پروفایل سم کړئ",
    editProfile: "پروفایل سم کړئ",
    fullNameRequired: "بشپړ نوم اړین دی",
    loadingProfile: "پروفایل ترلاسه کیږي...",
    loadingProfiles: "پروفایلونه ترلاسه کیږي...",
    loadingRoles: "رولونه ترلاسه کیږي...",
    noEmail: "بریښنالیک نشته",
    noName: "نوم نشته",
    noProfilesFound: "پروفایل ونه موندل شو.",
    phoneMaxLength: "د ټیلیفون شمېره باید ۵۰ توري یا کم وي",
    superAdmin: "سپر اډمین",
    unknownOrg: "نامعلوم سازمان",
    updateOwnProfileDescription: "خپل د پروفایل معلومات لاندې تازه کړئ.",
    updateProfileDescription: "د پروفایل معلومات لاندې تازه کړئ."
  }
};
