/**
 * profile-management page translations (fa).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  profileManagement: {
    allProfiles: "All Profiles",
    editMyProfile: "Edit My Profile",
    editProfile: "Edit Profile",
    fullNameRequired: "Full name is required",
    loadingProfile: "Loading profile...",
    loadingProfiles: "Loading profiles...",
    loadingRoles: "Loading roles...",
    noEmail: "No email",
    noName: "No name",
    noProfilesFound: "No profiles found.",
    phoneMaxLength: "Phone number must be 50 characters or less",
    superAdmin: "Super Admin",
    unknownOrg: "Unknown Org",
    updateOwnProfileDescription: "Update your profile information below.",
    updateProfileDescription: "Update the profile information below."
  }
};
