/**
 * profile-management page translations (ar).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  profileManagement: {
    allProfiles: "جميع الملفات الشخصية",
    editMyProfile: "تعديل ملفي الشخصي",
    editProfile: "تعديل الملف الشخصي",
    fullNameRequired: "الاسم الكامل مطلوب",
    loadingProfile: "جاري تحميل الملف الشخصي...",
    loadingProfiles: "جاري تحميل الملفات الشخصية...",
    loadingRoles: "جاري تحميل الأدوار...",
    noEmail: "لا يوجد بريد إلكتروني",
    noName: "لا يوجد اسم",
    noProfilesFound: "لم يتم العثور على ملفات شخصية.",
    phoneMaxLength: "يجب أن يكون رقم الهاتف 50 حرفًا أو أقل",
    superAdmin: "مدير عام",
    unknownOrg: "منظمة غير معروفة",
    updateOwnProfileDescription: "قم بتحديث معلومات ملفك الشخصي أدناه.",
    updateProfileDescription: "قم بتحديث معلومات الملف الشخصي أدناه."
  }
};
