/**
 * Shared footer translations (fa).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  footer: {
    aboutUs: "درباره ما",
    apiDocumentation: undefined,
    careers: "Careers",
    company: "Company",
    contactSupport: "Contact Support",
    cookiePolicy: "Cookie Policy",
    copyright: "© 2026 Nazim School Management System. All rights reserved.",
    features: "Features",
    helpCenter: "Help Center",
    integrations: undefined,
    pricing: "Pricing",
    privacyPolicy: "سیاست حفظ حریم خصوصی",
    product: "Product",
    releaseNotes: "Release Notes",
    security: "Security",
    support: "Support",
    systemStatus: "System Status",
    tagline: "Empowering educational institutions with modern technology solutions for better learning outcomes.",
    termsOfService: "شرایط خدمات",
    trainingVideos: "Training Videos"
  }
};
