/**
 * Shared footer translations (ps).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  footer: {
    aboutUs: "زموږ په اړه",
    careers: "دندې",
    company: "شرکت",
    contactSupport: "د ملاتړ ټیم سره اړیکه",
    cookiePolicy: "د کوکي تګلاره",
    copyright: "© 2026ناظم د دیني مدارسو د مالي او اداري چارو د تنظیم سیستم . ټول حقونه خوندي دي.",
    features: "ځانګړتیاوې",
    helpCenter: "د مرستې مرکز",
    integrations: "تړل شوي سیسټمونه (Integrations)",
    pricing: "بیې",
    privacyPolicy: "د محرمیت تګلاره",
    product: "محصول",
    releaseNotes: "د تازه بدلونونو یادښت",
    security: "امنیت",
    support: "ملاتړ (Support)",
    systemStatus: "د سیسټم حالت",
    tagline: "د غوره زده کړې پایلو لپاره ښوونیز بنسټونه په عصري ټیکنالوژۍ سمبالول.",
    termsOfService: "د خدمت شرایط",
    trainingVideos: "روزنیزې ویډیوګانې"
  }
};
