/**
 * Shared footer translations (en).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  footer: {
    aboutUs: "About Us",
    careers: "Careers",
    company: "Company",
    contactSupport: "Contact Support",
    cookiePolicy: "Cookie Policy",
    copyright: "© 2026 Nazim School Management System. All rights reserved.",
    features: "Features",
    helpCenter: "Help Center",
    integrations: "Integrations",
    pricing: "Pricing",
    privacyPolicy: "Privacy Policy",
    product: "Product",
    releaseNotes: "Release Notes",
    security: "Security",
    support: "Support",
    systemStatus: "System Status",
    tagline: "Empowering educational institutions with modern technology solutions for better learning outcomes.",
    termsOfService: "Terms of Service",
    trainingVideos: "Training Videos"
  }
};
