/**
 * Shared footer translations (fa).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  footer: {
    aboutUs: "درباره ما",
    careers: "مشاغل",
    company: "شرکت",
    contactSupport: "تماس با پشتیبانی",
    cookiePolicy: "سیاست کوکی",
    copyright: "© ۲۰۲۶ نظام سیستم مدیریت مکتب. تمامی حقوق محفوظ است.",
    features: "ویژگی‌ها",
    helpCenter: "مرکز راهنما",
    integrations: "یکپارچه‌سازی",
    pricing: "قیمت‌گذاری",
    privacyPolicy: "سیاست حفظ حریم خصوصی",
    product: "محصول",
    releaseNotes: "یادداشت‌های انتشار",
    security: "امنیت",
    support: "پشتیبانی",
    systemStatus: "وضعیت سیستم",
    tagline: "توانمندسازی نهادهای تعلیمی با راهکارهای تکنالوژی نوین برای نتایج بهتر تعلیمی.",
    termsOfService: "شرایط خدمات",
    trainingVideos: "ویدیوهای آموزشی"
  }
};
