/**
 * organizations page translations (fa).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  organizations: {
    actions: "Actions",
    addNewOrganization: "Add New Organization",
    addOrganization: "Add Organization",
    buildings: "Buildings",
    cancel: "Cancel",
    classes: "Classes",
    close: "Close",
    create: "Create",
    delete: "Delete",
    deleteConfirmDescription: "This action cannot be undone. This will permanently delete the organization",
    deleteConfirmTitle: "Are you sure?",
    edit: "Edit",
    editOrganization: "Edit Organization",
    editOrganizationButton: "Edit Organization",
    enterOrganizationDetails: "Enter organization details below",
    id: "ID",
    loadingOrganizations: "Loading organizations...",
    name: "Name",
    noOrganizationsMessage: "No organizations found. Add your first organization.",
    noSettingsConfigured: "No settings configured",
    organizationDetails: "Organization Details",
    rooms: "Rooms",
    schools: "Schools",
    settings: "Settings",
    settingsTitle: "Settings",
    slug: "Slug",
    staff: "Staff",
    statistics: "Statistics",
    students: "Students",
    subtitle: "Manage organizations in your multi-tenant system",
    title: "Organizations Management",
    update: "Update",
    updateOrganizationInfo: "Update organization information",
    users: "Users",
    viewCompleteInfo: "View complete organization information"
  }
};
