/**
 * organizations page translations (ar).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  organizations: {
    actions: "الإجراءات",
    addNewOrganization: "إضافة منظمة جديدة",
    addOrganization: "إضافة منظمة",
    buildings: "المباني",
    cancel: "إلغاء",
    classes: "الفصول",
    close: "إغلاق",
    create: "إنشاء",
    delete: "حذف",
    deleteConfirmDescription: "لا يمكن التراجع عن هذا الإجراء. سيحذف هذا المنظمة بشكل دائم",
    deleteConfirmTitle: "هل أنت متأكد؟",
    edit: "تعديل",
    editOrganization: "تعديل المنظمة",
    editOrganizationButton: "تعديل المنظمة",
    enterOrganizationDetails: "أدخل تفاصيل المنظمة أدناه",
    id: "المعرف",
    loadingOrganizations: "جاري تحميل المنظمات...",
    name: "الاسم",
    noOrganizationsMessage: "لم يتم العثور على منظمات. أضف منظمتك الأولى.",
    noSettingsConfigured: "لم يتم تكوين أي إعدادات",
    organizationDetails: "تفاصيل المنظمة",
    rooms: "الغرف",
    schools: "المدارس",
    settings: "الإعدادات",
    settingsTitle: "الإعدادات",
    slug: "المعرف",
    staff: "الموظفون",
    statistics: "الإحصائيات",
    students: "الطلاب",
    subtitle: "إدارة المنظمات في نظامك متعدد المستأجرين",
    title: "إدارة المنظمات",
    update: "تحديث",
    updateOrganizationInfo: "تحديث معلومات المنظمة",
    users: "المستخدمون",
    viewCompleteInfo: "عرض معلومات المنظمة الكاملة"
  }
};
