/**
 * organizations page translations (ps).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  organizations: {
    actions: "کړنې",
    addNewOrganization: "نوی اداره اضافه کړئ",
    addOrganization: "اداره اضافه کړئ",
    buildings: "ودانۍ",
    cancel: "لغوه",
    classes: "ټولګي",
    close: "بندول",
    create: "جوړ کړئ",
    delete: "پاک کړئ",
    deleteConfirmDescription: "دا عمل بېرته نه ګرځیدونکی دی. دا به اداره په دایمي توګه پاک کړي.",
    deleteConfirmTitle: "ایا ډاډه یاست؟",
    edit: "سم کړئ",
    editOrganization: "اداره سم کړئ",
    editOrganizationButton: "اداره سم کړئ",
    enterOrganizationDetails: "د اداره جزئیات لاندې ولیکئ",
    id: "ID",
    loadingOrganizations: "ادارې  ترلاسه کیږي...",
    name: "نوم",
    noOrganizationsMessage: "ادارې  نشته. خپل لومړی اداره اضافه کړئ.",
    noSettingsConfigured: "تنظیمات نه دي شوي",
    organizationDetails: "د اداره جزئیات",
    rooms: "اتاقونه",
    schools: "ښوونځي",
    settings: "تنظیمات",
    settingsTitle: "تنظیمات",
    slug: "لنډه پته (Slug)",
    staff: "کارکوونکي",
    statistics: "احصایه",
    students: "زده کوونکي",
    subtitle: "په خپل څو څانګیز سیسټم کې ادارې  مدیریت کړئ",
    title: "د سازمانونو مدیریت",
    update: "تازه کول",
    updateOrganizationInfo: "د اداره معلومات تازه کړئ",
    users: "کاروونکي",
    viewCompleteInfo: "د اداره بشپړ معلومات وګورئ"
  }
};
