/**
 * Shared search translations (ar).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  search: {
    academicYears: "السنوات الأكاديمية",
    class: "الفصل",
    classes: "الفصول",
    code: "الرمز",
    employeeId: "رقم الموظف",
    placeholder: "البحث عن الطلاب والفصول والمعلمين...",
    position: "المنصب",
    schools: "المدارس",
    staff: "الموظفون",
    startTyping: "ابدأ الكتابة للبحث...",
    students: "الطلاب",
    subjects: "المواد"
  }
};
