/**
 * Shared search translations (fa).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  search: {
    academicYears: "Academic Years",
    class: "Class",
    classes: "Classes",
    code: "Code",
    employeeId: "Employee ID",
    placeholder: "Search students, classes, teachers...",
    position: "Position",
    schools: "Schools",
    staff: "Staff",
    startTyping: "Start typing to search...",
    students: "Students",
    subjects: "Subjects"
  }
};
