/**
 * Shared search translations (fa).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  search: {
    academicYears: "سال‌های تعلیمی",
    class: "صنف",
    classes: "صنف‌ها",
    code: "کد",
    employeeId: "شناسه کارمند",
    placeholder: "شاگردان، صنف‌ها، معلمان را جستجو کنید...",
    position: "بست",
    schools: "مکاتب",
    staff: "کارمندان",
    startTyping: "برای جستجو تایپ کنید...",
    students: "شاگردان",
    subjects: "مضامین"
  }
};
