/**
 * Shared errorBoundary translations (ps).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  errorBoundary: {
    anErrorOccurred: "یوه تېروتنه رامنځته شوه",
    applicationCrashed: "څه ستونزه رامنځته شوه او اپلیکیشن کار بند کړ.",
    applicationError: "د اپلیکیشن تېروتنه",
    componentError: "څه ستونزه رامنځته شوه",
    errorDetailsDev: "د تېروتنې جزیات (پراختیا)",
    goHome: "کور پاڼې ته لاړ شئ",
    maxRetriesReached: "نورې هڅې نه کیږي",
    refreshOrContactSupport: "مهرباني وکړئ پاڼه تازه کړئ یا له  ادارې سره اړیکه ونیسئ.",
    refreshPage: "پاڼه تازه کړئ",
    report: "شکایت ثبت کړئ",
    reportBug: "د سیستم مشکل په ګوته کړئ",
    reportDescription: "په اختیاري ډول ووایاست چې تاسو څه کول غواړئ . د تېروتنې جزیات لا دمخه ثبت شوي دي.",
    whatWereYouDoing: "تاسو څه کول غواړئ ؟ (اختیاري)",
    notePlaceholder: "هغه ګامونه بیان کړئ چې دې تېروتنې ته یې رسولي…",
    submitReport: "راپور واستوئ",
    reportSent: "مننه. ستاسو راپور ثبت شو.",
    reportFailed: "راپور ونه لېږل شو. بیا هڅه وکړئ.",
    somethingWentWrong: "څه ستونزه رامنځته شوه",
    technicalDetails: "تخنیکي جزیات",
    tryAgainLater: "مهرباني وکړئ لږ وروسته بیا هڅه وکړئ.",
    tryReloading: "دا برخه له تېروتنې سره مخ شوه. تاسو کولی شئ د هغې په بیا پورته کولو هڅه وکړئ.",
    workingOnFix: "موږ د دې په حل کولو کار کوو."
  }
};
