/**
 * Shared errorBoundary translations (fa).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  errorBoundary: {
    anErrorOccurred: "یک خطا رخ داد",
    applicationCrashed: "مشکلی پیش آمد و برنامه متوقف شد.",
    applicationError: "خطای برنامه",
    componentError: "مشکلی پیش آمد",
    errorDetailsDev: "جزئیات خطا (توسعه‌دهنده)",
    goHome: "رفتن به خانه",
    maxRetriesReached: "حداکثر تلاش مجدد انجام شد",
    refreshOrContactSupport: "لطفاً صفحه را رفرش کنید یا با پشتیبانی تماس بگیرید.",
    refreshPage: "رفرش صفحه",
    report: "گزارش",
    reportBug: "گزارش باگ",
    reportDescription: "اختیاری توضیح دهید چه کاری انجام می‌دادید. جزئیات خطا قبلاً ذخیره شده است.",
    whatWereYouDoing: "چه کاری انجام می‌دادید؟ (اختیاری)",
    notePlaceholder: "مراحل منجر به این خطا را بنویسید…",
    submitReport: "ارسال گزارش",
    reportSent: "تشکر. گزارش شما ثبت شد.",
    reportFailed: "ارسال گزارش ممکن نشد. دوباره تلاش کنید.",
    somethingWentWrong: "مشکلی پیش آمد",
    technicalDetails: "جزئیات فنی",
    tryAgainLater: "لطفاً بعداً دوباره تلاش کنید.",
    tryReloading: "این بخش با خطا مواجه شد. می‌توانید بارگذاری مجدد را امتحان کنید.",
    workingOnFix: "ما خطا را ثبت کردیم و در حال رفع آن هستیم."
  }
};
