/**
 * Shared errorBoundary translations (ar).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  errorBoundary: {
    anErrorOccurred: "An error occurred",
    applicationCrashed: "Something went wrong and the application crashed.",
    applicationError: "Application Error",
    componentError: "Something went wrong",
    errorDetailsDev: "Error Details (Development)",
    goHome: "Go Home",
    maxRetriesReached: "Maximum retry attempts reached",
    refreshOrContactSupport: "Please refresh the page or contact support.",
    refreshPage: "Refresh Page",
    report: "Report",
    reportBug: "Report Bug",
    somethingWentWrong: "Something went wrong",
    technicalDetails: "Technical Details",
    tryAgainLater: "Please try again later.",
    tryReloading: "This component encountered an error. You can try reloading it.",
    workingOnFix: "We"
  }
};
