// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { env } from '@/lib/env';
import type { Database } from '@/integrations/supabase/types';


const SUPABASE_URL = env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = env.VITE_SUPABASE_ANON_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Supabase is deprecated - using Laravel API instead
// Validate environment variables (optional - won't throw if missing)
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.warn('⚠️ Supabase not configured - using Laravel API instead. This is expected after migration.');
  // Don't throw - just create a dummy client that won't be used
}

// Supabase client is deprecated - using Laravel API instead
// This file is kept for backward compatibility but should not be used for new features
// console.log('✅ Supabase client initialized:', {
//   url: SUPABASE_URL,
//   hasKey: !!SUPABASE_PUBLISHABLE_KEY,
// });

// Create Supabase client only if configured (for backward compatibility)
// In production, this should be removed once all Supabase dependencies are migrated
export const supabase = createClient<Database>(
  SUPABASE_URL || 'http://localhost:54321', 
  SUPABASE_PUBLISHABLE_KEY || 'dummy-key', 
  {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
  global: {
    headers: {
      'x-client-info': 'nazim-school-manager@1.0.0',
    },
    fetch: (url: string | Request, options: RequestInit = {}) => {
      // Add better error handling for network issues
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 30000); // 30 second timeout
      
      return fetch(url, {
        ...options,
        signal: controller.signal,
      })
      .finally(() => clearTimeout(timeoutId))
      .catch((error) => {
        // Log detailed error information
        console.error('❌ Supabase fetch error:', {
          url: typeof url === 'string' ? url : url.toString(),
          method: options.method || 'GET',
          error: error.message,
          name: error.name,
          supabaseUrl: SUPABASE_URL,
        });
        
        // Provide more helpful error messages
        if (error.name === 'AbortError' || error.message?.includes('timeout') || error.message?.includes('aborted')) {
          throw new Error('Request timeout: Supabase server is not responding. Please check if Supabase is running (run "supabase start").');
        } else if (error.message?.includes('Failed to fetch') || error.message?.includes('NetworkError') || error.message?.includes('ERR_')) {
          throw new Error(`Network error: Unable to connect to Supabase at ${SUPABASE_URL}. Please ensure Supabase is running (run "supabase start").`);
        }
        throw error;
      });
    },
  },
});
