/**
 * Shared toast translations (fa).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  toast: {
    schoolRulesUpdated: "قوانین مکتب با موفقیت به‌روزرسانی شد",
    schoolRulesUpdateFailed: "به‌روزرسانی قوانین مکتب ناموفق بود"
  }
};
