/**
 * Shared forms translations (fa).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  forms: {
    invalidEmail: "لطفاً ایمیل معتبر وارد کنید",
    required: "پر کردن این بخش الزامی است"
  }
};
