/**
 * Shared forms translations (ar).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  forms: {
    invalidEmail: "يرجى إدخال عنوان بريد إلكتروني صحيح",
    required: "هذا الحقل مطلوب"
  }
};
