/**
 * Shared forms translations (ps).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  forms: {
    invalidEmail: "مهرباني وکړئ سم بریښنالیک ولیکئ",
    required: "دا برخه ډکول اړین دي"
  }
};
