/**
 * schools page translations (fa).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  schools: {
    schoolRules: "قوانین مکتب",
    editSchoolRules: "ویرایش قوانین مکتب",
    commitmentItems: "فهرست تعهدات (تعهد نامه)",
    commitmentItem: "بند تعهد",
    guaranteeText: "متن ضمانت (ضمانت نامه)",
    guaranteeTextPlaceholder: "متن ضمانت را وارد کنید...",
    noCommitmentItems: "هیچ بند تعهدی وجود ندارد. برای افزودن روی \"افزودن\" کلیک کنید."
  }
};
