/**
 * short-term-courses page translations (ps).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  shortTermCourses: {
    subtitle: "لنډمهاله دورې او نوم لیکنې مدیریت کړئ",
    completionDate: "د بشپړتیا نیټه",
    courseDocuments: "د دوره اسناد",
    deleteDocument: "سند پاک کړئ",
    deleteDocumentConfirm: "د سند د پاکولو تایید",
    documentType: "د سند ډول",
    noDocuments: "هیڅ سند نشته",
    size: "اندازه",
    student: "زده کوونکی",
    uploadDocument: "سند پورته کړئ",
    uploaded: "پورته شوی"
  }
};
