/**
 * short-term-courses page translations (fa).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  shortTermCourses: {
    subtitle: "مدیریت کورس‌های کوتاه‌مدت و شمولیت‌ها",
    completionDate: "تاریخ تکمیل",
    courseDocuments: "اسناد کورس",
    deleteDocument: "حذف سند",
    deleteDocumentConfirm: "تأیید حذف سند",
    documentType: "نوع سند",
    noDocuments: "اسناد موجود نیست",
    size: "اندازه",
    student: "شاگرد",
    uploadDocument: "بارگذاری سند",
    uploaded: "بارگذاری شده"
  }
};
