/**
 * graduation page translations (ar).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  graduation: {
    attendance: {
      requireAttendance: "require Attendance",
      requireAttendanceDescription: "يجب على الطلاب تلبية متطلبات الحضور للتخرج",
      requireAttendanceNotEnforced: "متطلبات الحضور غير مفروضة",
      minPercentage: "min Percentage",
      minPercentageDescription: "يجب أن يكون لدى الطلاب على الأقل {percentage}% حضور ليكونوا مؤهلين للتخرج",
      excludeLeaves: "exclude Leaves",
      excludeLeavesDescription: "الإجازات المعتمدة (إجازة مرضية، إجازة شخصية، إلخ) لن تُحسب كغياب عند حساب نسبة الحضور",
      title: "title"
    },
    exams: {
      weights: "weights",
      equalWeights: "equal Weights",
      totalWeight: "total Weight"
    },
    validation: {
      weightsMustSum100: "weights Must Sum100"
    },
    batches: "batches",
    status: {
      draft: "draft",
      approved: "approved",
      issued: "issued"
    },
    graduationType: "graduation Type",
    type: {
      transfer: "transfer",
      promotion: "promotion",
      finalYear: "final Year"
    },
    classTransfer: "class Transfer",
    transferringTo: "transferring To",
    table: {
      students: "students"
    },
    types: {
      finalYear: "final Year",
      promotion: "promotion",
      transfer: "transfer"
    },
    filters: {
      dateFrom: "date From",
      dateTo: "date To",
      searchPlaceholder: "search Placeholder"
    },
    selectSchoolDescription: "select School Description",
    fromClass: "from Class",
    selectFromClass: "select From Class",
    toClass: "to Class",
    selectToClass: "select To Class",
    summary: {
      totalBatches: "total Batches",
      draftBatches: "draft Batches",
      approvedBatches: "approved Batches",
      issuedBatches: "issued Batches"
    },
    noBatches: {
      title: "title",
      description: "description"
    },
    pagination: {
      showing: "showing",
      of: "of"
    },
    editBatchDescription: "edit Batch Description",
    cannotChangeTypeWithStudents: "cannot Change Type With Students",
    dashboard: {
      title: "title",
      noSchools: "no Schools",
      selectSchool: "select School",
      currentYearBatches: "current Year Batches",
      certificatesThisYear: "certificates This Year",
      quickActions: "quick Actions",
      createBatch: "create Batch",
      createBatchDesc: "create Batch Desc",
      viewTemplates: "view Templates",
      viewTemplatesDesc: "view Templates Desc",
      issuedCertificates: "issued Certificates",
      issuedCertificatesDesc: "issued Certificates Desc",
      recentBatches: "recent Batches",
      pendingApprovals: "pending Approvals",
      noPendingApprovals: "no Pending Approvals",
      upcomingGraduations: "upcoming Graduations"
    }
  }
};
