/**
 * graduation page translations (ps).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  graduation: {
    attendance: {
      requireAttendance: "حاضري ته اړتیا ده",
      requireAttendanceDescription: "زده کوونکي باید د حاضري اړتیاوې پوره کړي ترڅو فراغت ترلاسه کړي",
      requireAttendanceNotEnforced: "د حاضري اړتیاوې نه دي پلي شوي",
      minPercentage: "لږترلږه سلنه",
      minPercentageDescription: "زده کوونکي باید لږترلږه {percentage}% حاضري ولري ترڅو د فراغت وړ وګڼل شي",
      excludeLeaves: "رخصتۍ لرې کړئ",
      excludeLeavesDescription: "منظور شوي رخصتۍ (ناروغي، شخصي رخصتۍ، او داسې نور) به د حاضري سلنې محاسبه کولو کې د غیر حاضري په توګه ونه شمیرل شي",
      title: "عنوان"
    },
    exams: {
      weights: "وزنونه",
      equalWeights: "مساوي وزنونه",
      totalWeight: "ټول وزن"
    },
    validation: {
      weightsMustSum100: "وزنونه باید د 100 مجموعه وي"
    },
    batches: "ډلې",
    status: {
      draft: "مسوده",
      approved: "تصویب شوی",
      issued: "صادر شوی"
    },
    graduationType: "د فراغت ډول",
    type: {
      transfer: "لیږد",
      promotion: "ارتقا",
      finalYear: "وروستی کال"
    },
    classTransfer: "د ټولګي لیږد",
    transferringTo: "لیږد ته",
    table: {
      students: "زده کوونکي"
    },
    types: {
      finalYear: "وروستی کال",
      promotion: "ارتقا",
      transfer: "لیږد"
    },
    filters: {
      dateFrom: "نېټه له",
      dateTo: "نېټه تر",
      searchPlaceholder: "لټون ځای لرونکی"
    },
    selectSchoolDescription: "د ښوونځي تفصیل وټاکئ",
    fromClass: "له ټولګي څخه",
    selectFromClass: "له ټولګي څخه وټاکئ",
    toClass: "ټولګي ته",
    selectToClass: "ټولګي ته وټاکئ",
    summary: {
      totalBatches: "ټولې ډلې",
      draftBatches: "مسوده ډلې",
      approvedBatches: "تصویب شوې ډلې",
      issuedBatches: "صادر شوې ډلې"
    },
    noBatches: {
      title: "عنوان",
      description: "توضیحات"
    },
    pagination: {
      showing: "ښودل",
      of: "د"
    },
    editBatchDescription: "د ډلې توضیحات سم کړئ",
    cannotChangeTypeWithStudents: "د زده کوونکو سره ډول نشي بدلیدلی",
    dashboard: {
      title: "عنوان",
      noSchools: "ښوونځي نشته",
      selectSchool: "ښوونځی وټاکئ",
      currentYearBatches: "د اوسني کال ډلې",
      certificatesThisYear: "د دې کال سندونه",
      quickActions: "چټک عملونه",
      createBatch: "ډله جوړه کړئ",
      createBatchDesc: "د ډلې توضیحات جوړ کړئ",
      viewTemplates: "قالبونه وګورئ",
      viewTemplatesDesc: "د قالبونو توضیحات وګورئ",
      issuedCertificates: "صادر شوي سندونه",
      issuedCertificatesDesc: "د صادر شویو سندونو توضیحات",
      recentBatches: "وروستۍ ډلې",
      pendingApprovals: "په تمه تصویبونه",
      noPendingApprovals: "هیڅ په تمه تصویبونه نشته",
      upcomingGraduations: "راتلونکي فراغتونه"
    }
  }
};
