/**
 * graduation page translations (fa).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  graduation: {
    attendance: {
      requireAttendance: "الزام حاضري",
      requireAttendanceDescription: "شاگردان باید شرایط حاضري را برای فراغت رعایت کنند",
      requireAttendanceNotEnforced: "شرایط حاضري اعمال نمی‌شود",
      minPercentage: "حداقل درصد",
      minPercentageDescription: "شاگردان باید حداقل {percentage}٪ حاضري داشته باشند تا واجد فراغت شوند",
      excludeLeaves: "حذف رخصتی‌ها",
      excludeLeavesDescription: "رخصتی‌های تأیید شده (مریضی، شخصی و غیره) در محاسبه درصد حاضري به عنوان غیبت شمارش نمی‌شوند",
      title: "عنوان"
    },
    exams: {
      weights: "وزن‌ها",
      equalWeights: "وزن‌های مساوی",
      totalWeight: "وزن کل"
    },
    validation: {
      weightsMustSum100: "مجموع وزن‌ها باید ۱۰۰ باشد"
    },
    batches: "بست‌ها",
    status: {
      draft: "پیش‌نویس",
      approved: "تأیید شده",
      issued: "صادر شده"
    },
    graduationType: "نوع فراغت",
    type: {
      transfer: "انتقال",
      promotion: "ترفیع",
      finalYear: "سال پایانی"
    },
    classTransfer: "انتقال صنف",
    transferringTo: "انتقال به",
    table: {
      students: "شاگردان"
    },
    types: {
      finalYear: "سال پایانی",
      promotion: "ترفیع",
      transfer: "انتقال"
    },
    filters: {
      dateFrom: "تاریخ از",
      dateTo: "تاریخ تا",
      searchPlaceholder: "جستجو..."
    },
    selectSchoolDescription: "مکتب را انتخاب کنید",
    fromClass: "از صنف",
    selectFromClass: "انتخاب صنف مبدأ",
    toClass: "به صنف",
    selectToClass: "انتخاب صنف مقصد",
    summary: {
      totalBatches: "مجموع بست‌ها",
      draftBatches: "بست‌های پیش‌نویس",
      approvedBatches: "بست‌های تأیید شده",
      issuedBatches: "بست‌های صادر شده"
    },
    noBatches: {
      title: "عنوان",
      description: "توضیحات"
    },
    pagination: {
      showing: "نمایش",
      of: "از"
    },
    editBatchDescription: "ویرایش بست",
    cannotChangeTypeWithStudents: "با وجود شاگردان در بست، نوع قابل تغییر نیست",
    dashboard: {
      title: "فراغت",
      noSchools: "مکتبی یافت نشد",
      selectSchool: "انتخاب مکتب",
      currentYearBatches: "بست‌های سال جاری",
      certificatesThisYear: "تصدیق‌نامه‌های امسال",
      quickActions: "اقدامات سریع",
      createBatch: "ایجاد بست",
      createBatchDesc: "ایجاد بست فراغت جدید",
      viewTemplates: "مشاهده قالب‌ها",
      viewTemplatesDesc: "مدیریت قالب‌های تصدیق‌نامه",
      issuedCertificates: "تصدیق‌نامه‌های صادر شده",
      issuedCertificatesDesc: "مشاهده تصدیق‌نامه‌های صادر شده",
      recentBatches: "بست‌های اخیر",
      pendingApprovals: "تأییدهای در انتظار",
      noPendingApprovals: "تأیید در انتظاری نیست",
      upcomingGraduations: "فراغت‌های پیش‌رو"
    }
  }
};
