<?php

namespace App\Services\Reports;

/**
 * Labels for leave request gate-slip PDF.
 */
class LeaveRequestSlipLabels
{
    /**
     * @return array<string, string>
     */
    public static function forLanguage(string $language): array
    {
        $maps = self::maps();
        $lang = strtolower(trim($language));

        if ($lang === 'dari') {
            $lang = 'fa';
        }

        return $maps[$lang] ?? $maps['en'];
    }

    public static function isRtl(string $language): bool
    {
        $lang = strtolower(trim($language));

        return in_array($lang, ['ps', 'fa', 'ar', 'dari'], true);
    }

    /**
     * @return array<string, array<string, string>>
     */
    private static function maps(): array
    {
        return [
            'en' => [
                'title' => 'Leave Request Slip',
                'student' => 'Student',
                'fatherName' => 'Father Name',
                'code' => 'Student Code',
                'class' => 'Class',
                'leaveType' => 'Leave Type',
                'fullDay' => 'Full Day',
                'partialDay' => 'Partial Day',
                'timeBound' => 'Time Bound',
                'startDate' => 'Start Date',
                'endDate' => 'End Date',
                'time' => 'Time',
                'duration' => 'Duration',
                'days' => 'day(s)',
                'hours' => 'hour(s)',
                'reason' => 'Reason',
                'status' => 'Status',
                'pending' => 'Pending',
                'approved' => 'Approved',
                'rejected' => 'Rejected',
                'cancelled' => 'Cancelled',
                'approvalNote' => 'Approval Note',
                'approvedBy' => 'Approved By',
                'approvedAt' => 'Approved At',
                'leaveId' => 'Leave ID',
                'printedOn' => 'Printed On',
                'scanToVerify' => 'Scan QR to verify this leave request',
                'signatureGuard' => 'Guard / Staff Signature',
                'signatureDate' => 'Date',
                'systemNote' => 'Generated by Nazim system.',
            ],
            'ps' => [
                'title' => 'د رخصتۍ غوښتنلیک',
                'student' => 'زده کوونکی',
                'fatherName' => 'د پلار نوم',
                'code' => 'د زده کوونکي کوډ',
                'class' => 'صنف',
                'leaveType' => 'د رخصتۍ ډول',
                'fullDay' => 'بشپړه ورځ',
                'partialDay' => 'نیمه ورځ',
                'timeBound' => 'وخت مشخص',
                'startDate' => 'د پیل نېټه',
                'endDate' => 'د پای نېټه',
                'time' => 'وخت',
                'duration' => 'موده',
                'days' => 'ورځې',
                'hours' => 'ساعتونه',
                'reason' => 'دلیل',
                'status' => 'حالت',
                'pending' => 'په تمه',
                'approved' => 'منل شوی',
                'rejected' => 'رد شوی',
                'cancelled' => 'لغوه شوی',
                'approvalNote' => 'د تایید یادښت',
                'approvedBy' => 'تاییدوونکی',
                'approvedAt' => 'د تایید نېټه',
                'leaveId' => 'د رخصتۍ شمېره',
                'printedOn' => 'چاپ نېټه',
                'scanToVerify' => 'د تایید لپاره QR سکین کړئ',
                'signatureGuard' => 'د ساتونکي / کارمند لاسلیک',
                'signatureDate' => 'نېټه',
                'systemNote' => 'دا راپور د ناظم سیستم په مټ جوړ شوی دی.',
            ],
            'fa' => [
                'title' => 'درخواست رخصتی',
                'student' => 'شاگرد',
                'fatherName' => 'نام پدر',
                'code' => 'کود شاگرد',
                'class' => 'صنف',
                'leaveType' => 'نوع رخصتی',
                'fullDay' => 'روز کامل',
                'partialDay' => 'نیمه روز',
                'timeBound' => 'محدود به وقت',
                'startDate' => 'تاریخ شروع',
                'endDate' => 'تاریخ پایان',
                'time' => 'وقت',
                'duration' => 'مدت',
                'days' => 'روز',
                'hours' => 'ساعت',
                'reason' => 'دلیل',
                'status' => 'وضعیت',
                'pending' => 'در انتظار',
                'approved' => 'تأیید شده',
                'rejected' => 'رد شده',
                'cancelled' => 'لغو شده',
                'approvalNote' => 'یادداشت تأیید',
                'approvedBy' => 'تأییدکننده',
                'approvedAt' => 'تاریخ تأیید',
                'leaveId' => 'شماره رخصتی',
                'printedOn' => 'تاریخ چاپ',
                'scanToVerify' => 'برای تأیید، QR را اسکن کنید',
                'signatureGuard' => 'امضای نگهبان / کارمند',
                'signatureDate' => 'تاریخ',
                'systemNote' => 'تولید شده توسط سیستم ناظم.',
            ],
            'ar' => [
                'title' => 'طلب إجازة',
                'student' => 'الطالب',
                'fatherName' => 'اسم الأب',
                'code' => 'رمز الطالب',
                'class' => 'الصف',
                'leaveType' => 'نوع الإجازة',
                'fullDay' => 'يوم كامل',
                'partialDay' => 'نصف يوم',
                'timeBound' => 'محدد بوقت',
                'startDate' => 'تاريخ البدء',
                'endDate' => 'تاريخ الانتهاء',
                'time' => 'الوقت',
                'duration' => 'المدة',
                'days' => 'يوم/أيام',
                'hours' => 'ساعة/ساعات',
                'reason' => 'السبب',
                'status' => 'الحالة',
                'pending' => 'قيد الانتظار',
                'approved' => 'موافق عليه',
                'rejected' => 'مرفوض',
                'cancelled' => 'ملغى',
                'approvalNote' => 'ملاحظة الموافقة',
                'approvedBy' => 'وافق عليه',
                'approvedAt' => 'تاريخ الموافقة',
                'leaveId' => 'رقم الإجازة',
                'printedOn' => 'تاريخ الطباعة',
                'scanToVerify' => 'امسح رمز QR للتحقق من طلب الإجازة',
                'signatureGuard' => 'توقيع الحارس / الموظف',
                'signatureDate' => 'التاريخ',
                'systemNote' => 'تم الإنشاء بواسطة نظام ناظم.',
            ],
        ];
    }
}
