/**
 * question-bank page translations (ar).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  questionBank: {
    academicYear: "Question Bank",
    activate: "Question Bank",
    addOption: "Question Bank",
    classAcademicYear: "Question Bank",
    classSubject: "Question Bank",
    correct: "Question Bank",
    correctAnswer: "Question Bank",
    correctAnswerPlaceholder: "Question Bank",
    createDescription: "Question Bank",
    deactivate: "Question Bank",
    deleteConfirmMessage: "Question Bank",
    editDescription: "Question Bank",
    filterAcademicYear: "Question Bank",
    filterClass: "Question Bank",
    filterDifficulty: "Question Bank",
    filterSchool: "Question Bank",
    filterSubject: "Question Bank",
    filterType: "Question Bank",
    marks: "Question Bank",
    noQuestions: "Question Bank",
    noQuestionsFound: "Question Bank",
    optionPlaceholder: "Question Bank",
    options: "Question Bank",
    questionsList: "Question Bank",
    questionText: "Question Bank",
    questionTextPlaceholder: "Question Bank",
    reference: "Question Bank",
    referencePlaceholder: "Question Bank",
    school: "Question Bank",
    selectAcademicYear: "Question Bank",
    selectAcademicYearFirst: "Question Bank",
    selectSubject: "Question Bank",
    subject: "Question Bank",
    totalQuestions: "Question Bank",
    "type.descriptive": "وصفي",
    "type.essay": "مقالي",
    "type.mcq": "اختيار من متعدد",
    "type.short": "إجابة قصيرة",
    "type.true_false": "صح/خطأ",
    viewQuestion: "Question Bank"
  }
};
