/**
 * question-bank page translations (ps).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  questionBank: {
    academicYear: "تعلیمي کال",
    activate: "فعالول",
    addOption: "غوراوی (Option) اضافه کړئ",
    classAcademicYear: "ټولګی (اختیاري)",
    classSubject: "مضمون",
    correct: "سم",
    correctAnswer: "نمونوي ځواب",
    correctAnswerPlaceholder: "نمونوي ځواب ولیکئ (اختیاري)...",
    createDescription: "د پوښتنو بانک ته نوې پوښتنه اضافه کړئ",
    deactivate: "غیر فعالول",
    deleteConfirmMessage: "ایا ډاډه یاست چې غواړئ دا پوښتنه پاکه کړئ؟ دا عمل بېرته نه ګرځیدونکی دی.",
    editDescription: "د پوښتنې جزئیات تازه کړئ",
    filterAcademicYear: "تعلیمي کال",
    filterClass: "ټولګی",
    filterDifficulty: "سختوالی",
    filterSchool: "ښوونځی",
    filterSubject: "مضمون",
    filterType: "ډول",
    marks: "نمرې",
    noQuestions: "پوښتنې ونه موندل شوې",
    noQuestionsFound: "پوښتنې نشته. د پیل لپاره خپله لومړۍ پوښتنه جوړه کړئ.",
    optionPlaceholder: "د ځواب متن...",
    options: "غوراوي (Options)",
    questionsList: "پوښتنې",
    questionText: "د پوښتنې متن",
    questionTextPlaceholder: "د پوښتنې متن ولیکئ...",
    reference: "ماخذ / حواله",
    referencePlaceholder: "د بېلګې په توګه: پنځم فصل، ۱۲۰ پاڼه",
    school: "ښوونځی",
    selectAcademicYear: "تعلیمي کال وټاکئ",
    selectAcademicYearFirst: "لومړی تعلیمي کال وټاکئ",
    selectSubject: "مضمون وټاکئ",
    subject: "مضمون",
    totalQuestions: "{count} پوښتنې وموندل شوې",
    "type.descriptive": "تشریحي",
    "type.essay": "مقالوي",
    "type.mcq": "څو ځوابیزه (MCQ)",
    "type.short": "لنډ ځواب",
    "type.true_false": "صحیح / غلط",
    viewQuestion: "پوښتنه وګورئ"
  }
};
