/**
 * question-bank page translations (fa).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  questionBank: {
    academicYear: "Academic Year",
    activate: "Activate",
    addOption: "Add Option",
    classAcademicYear: "Class (Optional)",
    classSubject: "Subject",
    correct: "Correct",
    correctAnswer: "Model Answer",
    correctAnswerPlaceholder: "Enter model answer (optional)...",
    createDescription: "Add a new question to the question bank",
    deactivate: "Deactivate",
    deleteConfirmMessage: "Are you sure you want to delete this question? This action cannot be undone.",
    editDescription: "Update the question details",
    filterAcademicYear: "Academic Year",
    filterClass: "Class",
    filterDifficulty: "Difficulty",
    filterSchool: "School",
    filterSubject: "Subject",
    filterType: "Type",
    marks: "Marks",
    noQuestions: "No questions found",
    noQuestionsFound: "No questions found. Create your first question to get started.",
    optionPlaceholder: "Option text...",
    options: "Options",
    questionsList: "Questions",
    questionText: "Question Text",
    questionTextPlaceholder: "Enter question text...",
    reference: "Reference",
    referencePlaceholder: "e.g., Chapter 5, Page 120",
    school: "School",
    selectAcademicYear: "Select academic year",
    selectAcademicYearFirst: "Select academic year first",
    selectSubject: "Select subject",
    subject: "Subject",
    totalQuestions: "{count} question(s) found",
    "type.descriptive": "Descriptive",
    "type.essay": "Essay",
    "type.mcq": "Multiple Choice",
    "type.short": "Short Answer",
    "type.true_false": "True/False",
    viewQuestion: "View Question"
  }
};
