/**
 * Shared notFound translations (en).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  notFound: {
    title: "Page Not Found",
    goHome: "Go Home",
    message: "The page you are looking for does not exist."
  }
};
