/**
 * Shared notFound translations (fa).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  notFound: {
    title: "صفحه یافت نشد",
    goHome: "بازگشت به صفحه اصلی",
    message: "صفحه‌ای که جستجو می‌کنید وجود ندارد."
  }
};
