/**
 * Shared notFound translations (ar).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  notFound: {
    goHome: "Go Home",
    message: "The page you are looking for does not exist."
  }
};
