#!/usr/bin/env bash

# Fix Container Dashboard - Shows Working Queries
# Dashboard 15798 doesn't work because cAdvisor uses systemd cgroup IDs

set -e

echo "=========================================="
echo "Fix: Dashboard 15798 Shows No Data"
echo "=========================================="
echo ""
echo "Problem: Dashboard 15798 expects container names, but cAdvisor"
echo "         uses systemd cgroup IDs: /system.slice/docker-{id}.scope"
echo ""
echo "Solution 1: Import Dashboard 11074 ⭐ RECOMMENDED"
echo "----------------------------------------"
echo "1. Open Grafana: http://168.231.125.153:3000"
echo "2. Go to: Dashboards → Import"
echo "3. Enter dashboard ID: 11074"
echo "4. Click 'Load'"
echo "5. Select 'Prometheus' as data source"
echo "6. Click 'Import'"
echo ""
echo "Solution 2: Use Grafana Explore (Always Works!)"
echo "----------------------------------------"
echo "1. Go to: Explore (compass icon)"
echo "2. Select: Prometheus"
echo "3. Use these queries:"
echo ""
echo "# Container CPU Usage"
echo "rate(container_cpu_usage_seconds_total{id=~\"/system.slice/docker-.*scope\"}[5m]) * 100"
echo ""
echo "# Container Memory Usage"
echo "container_memory_usage_bytes{id=~\"/system.slice/docker-.*scope\"}"
echo ""
echo "# Container Network Receive"
echo "rate(container_network_receive_bytes_total{id=~\"/system.slice/docker-.*scope\"}[5m])"
echo ""
echo "# Container Network Transmit"
echo "rate(container_network_transmit_bytes_total{id=~\"/system.slice/docker-.*scope\"}[5m])"
echo ""
echo "# List all containers"
echo "container_last_seen{id=~\"/system.slice/docker-.*scope\"}"
echo ""
echo "Solution 3: Fix Dashboard 15798 Queries"
echo "----------------------------------------"
echo "1. Open dashboard 15798"
echo "2. Click Edit (pencil icon)"
echo "3. For each panel, change queries:"
echo "   - Replace 'name=~\"...\"' with 'id=~\"/system.slice/docker-.*scope\"'"
echo "   - Replace 'container=~\"...\"' with 'id=~\"/system.slice/docker-.*scope\"'"
echo "4. Save dashboard"
echo ""
echo "Why Dashboard 11074 is Better:"
echo "- Handles different container ID formats"
echo "- More flexible queries"
echo "- Works out-of-the-box"
echo ""
echo "Quick Test:"
echo "----------------------------------------"
echo "Test in Grafana Explore:"
echo "  rate(container_cpu_usage_seconds_total{id=~\"/system.slice/docker-.*scope\"}[5m]) * 100"
echo ""
echo "If this shows data, metrics are working - just need the right dashboard!"
echo ""

