/**
 * Shared privacyPolicy translations (en).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  privacyPolicy: {
    contact: {
      content: "If you have any questions about this Privacy Policy or our data practices, please contact us at support@nazimapp.com or through our contact form.",
      title: "Contact Us"
    },
    dataRetention: {
      content: "We retain your personal information for as long as necessary to provide our services and comply with legal obligations. When you delete your account, we will delete or anonymize your personal information, except where we are required to retain it by law.",
      title: "Data Retention"
    },
    dataSecurity: {
      content: "We implement industry-standard security measures to protect your information, including encryption, secure data storage, and access controls. However, no method of transmission over the internet is 100% secure, and we cannot guarantee absolute security.",
      title: "Data Security"
    },
    howWeUse: {
      analytics: "To analyze usage patterns and improve user experience",
      communicate: "To communicate with you about your account and our services",
      provide: "To provide, maintain, and improve our services",
      security: "To ensure the security and integrity of our platform",
      support: "To provide customer support and respond to your inquiries",
      title: "How We Use Your Information"
    },
    informationWeCollect: {
      personal: {
        content: "We collect personal information that you provide to us, such as your name, email address, phone number, and school information when you register for our services.",
        title: "Personal Information"
      },
      technical: {
        content: "We collect technical information such as IP address, browser type, device information, and operating system for security and performance purposes.",
        title: "Technical Information"
      },
      title: "Information We Collect",
      usage: {
        content: "We automatically collect information about how you use our platform, including pages visited, features used, and time spent on the platform.",
        title: "Usage Information"
      }
    },
    introduction: {
      content: "At Nazim School Management System, we are committed to protecting your privacy and ensuring the security of your personal information. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our platform.",
      title: "Introduction"
    },
    lastUpdated: "Last Updated: January 2026",
    title: "Privacy Policy",
    yourRights: {
      access: "Access your personal information",
      correct: "Correct inaccurate or incomplete information",
      delete: "Request deletion of your personal information",
      export: "Export your data in a portable format",
      intro: "You have the right to:",
      object: "Object to processing of your personal information",
      title: "Your Rights"
    }
  }
};
