/**
 * Shared resetPassword translations (ar).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  resetPassword: {
    invalidResetLink: "Reset Password",
    passwordRequirements: "Reset Password",
    passwordsDoNotMatch: "Reset Password",
    passwordStrength: "Reset Password",
    requirement8Chars: "Reset Password",
    requirementLowercase: "Reset Password",
    requirementNumber: "Reset Password",
    requirementSpecial: "Reset Password",
    requirementUppercase: "Reset Password",
    updatePassword: "Reset Password",
    updatingPassword: "Reset Password"
  }
};
