/**
 * Shared resetPassword translations (fa).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  resetPassword: {
    subtitle: "Create a new secure password for your account",
    invalidResetLink: "Invalid reset link. Please request a new password reset.",
    passwordRequirements: "Password must contain:",
    passwordsDoNotMatch: "Passwords do not match",
    passwordStrength: "Password Strength",
    requirement8Chars: "At least 8 characters",
    requirementLowercase: "One lowercase letter",
    requirementNumber: "One number",
    requirementSpecial: "One special character",
    requirementUppercase: "One uppercase letter",
    updatePassword: "Update Password",
    updatingPassword: "Updating Password..."
  }
};
