/**
 * Shared resetPassword translations (ps).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  resetPassword: {
    subtitle: "د خپل حساب لپاره نوی خوندي پاسورډ جوړ کړئ",
    invalidResetLink: "د بیا تنظیمولو لینک ناسمه دی. مهرباني وکړئ د نوي لینک غوښتنه وکړئ.",
    passwordRequirements: "پاسورډ باید لاندې ځانګړتیاوې ولري:",
    passwordsDoNotMatch: "پاسورډونه سره سمون نه لري",
    passwordStrength: "د پاسورډ ځواک",
    requirement8Chars: "لږترلږه ۸ توري",
    requirementLowercase: "یو کوچنی تورى",
    requirementNumber: "یو عدد",
    requirementSpecial: "یو ځانګړی سمبول (Special Character)",
    requirementUppercase: "یو لوی تورى",
    updatePassword: "پاسورډ تازه کړئ",
    updatingPassword: "پاسورډ تازه کیږي..."
  }
};
