/**
 * permissions page translations (ps).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  permissions: {
    accessDenied: "لاسرسی رد شو",
    action: "کړنه",
    actions: "کړنې",
    cancel: "لغوه",
    createDialogTitle: "اجازه جوړه کړئ",
    creating: "د جوړېدو په حال کې...",
    delete: "پاک کړئ",
    description: "تفصیل",
    descriptionPlaceholder: "د اجازې تفصیل ولیکئ (اختیاري)",
    failedToUpdate: "د اجازې د رولونو په تازه کولو کې تېروتنه",
    fromRole: "له رول څخه",
    loadingPermissions: "اجازې ترلاسه کیږي...",
    managingPermissionsFor: "د دې لپاره اجازې مدیریت کیږي",
    noDescription: "تفصیل نشته",
    noPermissionMessage: "تاسو د اجازې مدیریت حق نلرئ",
    resource: "سرچینه",
    resources: "سرچینې",
    roles: "رولونه",
    save: "ثبت",
    subtitle: "اجازې وګورئ، مدیریت یې کړئ او رولونو ته یې وټاکئ",
    title: "د اجازو مدیریت",
    userSpecific: "د کاروونکي اړوند",
    viewGlobalAndManage: "تاسو کولی شئ عمومي اجازې وګورئ خو یوازې د خپل اداره اجازې مدیریت کولی شئ"
  }
};
