/**
 * permissions page translations (en).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  permissions: {
    accessDenied: "Access Denied",
    action: "Action",
    actions: "Actions",
    cancel: "Cancel",
    createDialogTitle: "Create Permission",
    creating: "Creating...",
    delete: "Delete",
    description: "Description",
    descriptionPlaceholder: "Enter permission description (optional)",
    failedToUpdate: "Failed to update permission roles",
    fromRole: "From Role",
    loadingPermissions: "Loading permissions...",
    managingPermissionsFor: "Managing permissions for",
    noDescription: "No description",
    noPermissionMessage: "You do not have permission to manage permissions",
    resource: "Resource",
    resources: "Resources",
    roles: "Roles",
    save: "Save",
    subtitle: "View and manage permissions and assign them to roles",
    title: "Permissions Management",
    userSpecific: "User Specific",
    viewGlobalAndManage: "You can view global permissions but can only manage your organization's permissions"
  }
};
