/**
 * settings page translations (ps).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  settings: {
    building: "ودانۍ",
    buildings: {
      addBuilding: "ودانۍ جوړه کړئ",
      buildingName: "د ودانۍ نوم",
      create: "جوړ کړئ",
      createdAt: "د جوړېدو نېټه",
      deleteConfirm: "دا عمل بېرته نه ګرځیدونکی دی. دا به ودانۍ په دایمي توګه پاکه کړي",
      deleteConfirmRooms: ". که په دې ودانۍ کې اتاقونه شتون ولري، پاکول به ناکام شي.",
      editBuilding: "ودانۍ سمه کړئ",
      enterBuildingName: "د ودانۍ نوم ولیکئ",
      loadingBuildings: "ودانۍ ترلاسه کیږي...",
      management: "د ودانیو مدیریت",
      na: "د تطبیق وړ نه دی",
      noBuildingsFound: "ودانۍ ونه موندل شوه",
      noBuildingsMessage: "ودانۍ نشته. خپله لومړۍ ودانۍ جوړه کړئ.",
      reportBuildingName: "د ودانۍ نوم",
      reportSchoolName: "د ښوونځي نوم",
      reportOrganization: "د سازمان نوم",
      reportCreatedAt: "د جوړېدو نېټه",
      exportErrorNoSchool: "مهرباني وکړئ د راپور صادرولو دمخه د ښوونځي نښانونه تنظیم کړئ.",
      exportErrorNoBuildings: "د صادرولو لپاره ودانۍ نشته.",
      exportSuccessPdf: "د PDF صادرول پیل شول",
      exportSuccessExcel: "د Excel صادرول پیل شول",
      exportErrorPdf: "د PDF صادرول ناکام شول",
      exportErrorExcel: "د Excel صادرول ناکام شول",
      reportRoomsCount: "د ودانۍ د اتاقونه شمېره",
      viewAll: "ټول کتل"
    },
    activityLogs: {
      title: "د فعالیت لاګونه",
      description: "تفصیل",
      todayLogs: "نن ورځ لاګونه",
      weekLogs: "دې اونۍ لاګونه",
      uniqueUsersToday: "نن ورځ ځانګړي کاروونکي",
      topEvent: "ډېر پیښه",
      searchPlaceholder: "تفصیل یا لاره وپلټئ...",
      selectLogName: "د لاګ نوم غوره کړئ",
      selectEvent: "د پیښې ډول غوره کړئ",
      dateTime: "نېټه او وخت",
      logName: "د لاګ نوم",
      event: "پیښه",
      user: "کاروونکی",
      method: "میتود",
      status: "حالت",
      noLogs: "د فعالیت لاګونه ونه موندل شول",
      logDetails: "د فعالیت لاګ جزئیات",
      requestInfo: "د غوښتنې معلومات",
      ipAddress: "IP پته",
      route: "لاره",
      subjectInfo: "د موضوع معلومات",
      subjectType: "د موضوع ډول",
      subjectId: "د موضوع ID",
      properties: "ځانګړتیاوې",
      userAgent: "د کاروونکي عامل",
      startDate: "د پیل نېټه",
      endDate: "د پای نېټه"
    },
    shortTermCourses: {
      subtitle: "لنډمهاله کورسونه او نوم لیکنې مدیریت کړئ",
      completionDate: "د بشپړېدو نېټه",
      courseDocuments: "د کورس اسناد",
      deleteDocument: "سند حذف کړئ",
      deleteDocumentConfirm: "د سند حذفول تائید کړئ",
      documentType: "د سند ډول",
      noDocuments: "اسناد نشته",
      size: "اندازه",
      student: "زده کوونکی",
      uploadDocument: "سند پورته کړئ",
      uploaded: "پورته شوی"
    },
    userSettings: {
      changePassword: "د پاسورډ بدلول",
      changePasswordDescription: "خپل پاسورډ تازه کړئ ترڅو ستاسو حساب خوندي پاتې شي",
      description: "خپل حساب غوره توبونه او امنیتي تنظیمات مدیریت کړئ",
      preferences: "غوره توبونه",
      security: "امنیت",
      title: "د کاروونکي تنظیمات"
    }
  }
};
