/**
 * settings page translations (ar).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  settings: {
    building: "المبنى",
    buildings: {
      addBuilding: "Settings",
      buildingName: "Settings",
      create: "Settings",
      createdAt: "Settings",
      deleteConfirm: "Settings",
      deleteConfirmRooms: "Settings",
      editBuilding: "Settings",
      enterBuildingName: "Settings",
      exportErrorExcel: "Settings",
      exportErrorNoBuildings: "Settings",
      exportErrorNoSchool: "Settings",
      exportErrorPdf: "Settings",
      exportSuccessExcel: "Settings",
      exportSuccessPdf: "Settings",
      loadingBuildings: "Settings",
      management: "Settings",
      na: "Settings",
      noBuildingsFound: "Settings",
      noBuildingsMessage: "Settings",
      reportBuildingName: "Settings",
      reportCreatedAt: "Settings",
      reportOrganization: "Settings",
      reportRoomsCount: "Settings",
      reportSchoolName: "Settings",
      reportTitle: "Settings",
      room: "Settings",
      rooms: "Settings",
      school: "Settings",
      schoolRequired: "Settings",
      searchPlaceholder: "Settings",
      selectSchool: "Settings",
      title: "Settings",
      unknownSchool: "Settings",
      update: "Settings",
      viewAll: "عرض الكل"
    },
    roomNumber: "رقم الغرفة",
    rooms: {
      addRoom: "Settings",
      building: "Settings",
      create: "Settings",
      createdAt: "Settings",
      deleteConfirm: "Settings",
      deleteConfirmRooms: "Settings",
      editRoom: "Settings",
      exportErrorExcel: "Settings",
      exportErrorNoRooms: "Settings",
      exportErrorNoSchool: "Settings",
      exportErrorPdf: "Settings",
      exportSuccessExcel: "Settings",
      exportSuccessPdf: "Settings",
      loadingRooms: "Settings",
      management: "Settings",
      na: "Settings",
      noRoomsFound: "Settings",
      noRoomsMessage: "Settings",
      noStaffAssigned: "Settings",
      reportTitle: "Settings",
      roomNumber: "Settings",
      searchPlaceholder: "Settings",
      selectBuilding: "Settings",
      selectStaff: "Settings",
      staffWarden: "Settings",
      staffWardenOptional: "Settings",
      title: "Settings",
      update: "Settings"
    },
    staff: "الموظفون",
    userSettings: {
      changePassword: "تغيير كلمة المرور",
      changePasswordDescription: "قم بتحديث كلمة المرور للحفاظ على أمان حسابك",
      description: "إدارة تفضيلات الحساب وإعدادات الأمان",
      preferences: "التفضيلات",
      security: "الأمان",
      title: "إعدادات المستخدم"
    },
    datePreferences: {
      title: "تفضيلات تنسيق التاريخ",
      description: "اختر نظام التقويم المفضل لديك. ستُعرض جميع التواريخ في جميع أنحاء التطبيق بالتنسيق المحدد.",
      calendarSystem: "نظام التقويم",
      gregorian: {
        label: "التقويم الميلادي",
        description: "التقويم الدولي القياسي (يناير، فبراير، مارس...)"
      },
      hijriShamsi: {
        label: "الهجري الشمسي (الشمسي)",
        description: "التقويم الشمسي الأفغاني/الإيراني (الحمل، الثور، الجوزاء...)"
      },
      hijriQamari: {
        label: "الهجري القمري (القمري)",
        description: "التقويم القمري الإسلامي (محرم، صفر، ربيع...)"
      },
      preview: "معاينة:",
      date: "التاريخ:",
      dateTime: "التاريخ والوقت:",
      note: "ملاحظة:",
      noteText: "يتم حفظ تفضيل التاريخ محليًا وسيستمر عبر الجلسات. يؤثر هذا التفضيل على كيفية عرض التواريخ في الجداول والنماذج والتقارير وفي جميع أنحاء التطبيق."
    },
    warden: "المسؤول"
  }
};
