/**
 * grades page translations (en).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  grades: {
    create: "Create Grade",
    created: "Grade created successfully",
    createDescription: "Create description",
    createError: "Failed to create grade",
    delete: "Delete Grade",
    deleteConfirmMessage: "Are you sure you want to delete this grade? This action cannot be undone.",
    deleted: "Grade deleted successfully",
    deleteError: "Failed to delete grade",
    edit: "Edit Grade",
    editDescription: "Edit description",
    failing: "Failing",
    failingGrade: "Failing Grade",
    isPass: "Is Passing Grade",
    list: "Grade List",
    management: "Grade Management",
    managementDescription: "Management description",
    maxPercentage: "Maximum Percentage",
    maxPercentagePlaceholder: "Max percentage placeholder",
    minPercentagePlaceholder: "Min percentage placeholder",
    name: "Name",
    nameAr: "Name (Arabic)",
    nameArPlaceholder: "Name ar placeholder",
    nameEn: "Name (English)",
    nameEnPlaceholder: "Name en placeholder",
    nameFa: "Name (Farsi)",
    nameFaPlaceholder: "Name fa placeholder",
    namePs: "Name (Pashto)",
    namePsPlaceholder: "Name ps placeholder",
    noGrades: "No grades found. Create your first grade to get started.",
    noGradesDescription: "No grades description",
    order: "Display Order",
    orderPlaceholder: "Order placeholder",
    passing: "Passing",
    passingGrade: "Passing Grade",
    percentageRange: "Percentage Range",
    title: "Grades",
    updated: "Grade updated successfully",
    updateError: "Failed to update grade"
  }
};
