/**
 * grades page translations (fa).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  grades: {
    create: "ایجاد درجه",
    created: "درجه با موفقیت ایجاد شد",
    createDescription: "تعریف یک سطح نمره جدید",
    createError: "ایجاد درجه ناموفق بود",
    delete: "حذف درجه",
    deleteConfirmMessage: "آیا مطمئن هستید که می‌خواهید این درجه را حذف کنید؟ این عمل غیرقابل بازگشت است.",
    deleted: "درجه با موفقیت حذف شد",
    deleteError: "حذف درجه ناموفق بود",
    edit: "ویرایش درجه",
    editDescription: "به‌روزرسانی تعریف درجه",
    failing: "ناکام",
    failingGrade: "درجه ناکامی",
    isPass: "درجه کامیابی است",
    list: "فهرست درجات",
    management: "مدیریت درجات",
    managementDescription: "تعریف سیستم نمره‌دهی سازمان خود",
    maxPercentage: "حداکثر فیصدی",
    maxPercentagePlaceholder: "مثال: ۱۰۰",
    minPercentagePlaceholder: "مثال: ۹۰",
    name: "نام",
    nameAr: "نام (عربی)",
    nameArPlaceholder: "مثال: ممتاز",
    nameEn: "نام (انگلیسی)",
    nameEnPlaceholder: "مثال: A+",
    nameFa: "نام (دری)",
    nameFaPlaceholder: "مثال: عالی",
    namePs: "نام (پشتو)",
    namePsPlaceholder: "مثال: اعلی",
    noGrades: "درجه‌ای یافت نشد. اولین درجه خود را ایجاد کنید.",
    noGradesDescription: "برای شروع، درجه جدیدی اضافه کنید",
    order: "ترتیب نمایش",
    orderPlaceholder: "شماره ترتیب",
    passing: "کامیاب",
    passingGrade: "درجه کامیابی",
    percentageRange: "محدوده فیصدی",
    title: "درجات",
    updated: "درجه با موفقیت به‌روزرسانی شد",
    updateError: "به‌روزرسانی درجه ناموفق بود"
  }
};
