/**
 * grades page translations (ps).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  grades: {
    create: "درجه جوړه کړئ",
    created: "درجه په بریالیتوب سره جوړه شوه",
    createDescription: "د نوې درجې تفصیل",
    createError: "د درجې په جوړولو کې تېروتنه",
    delete: "درجه پاکه کړئ",
    deleteConfirmMessage: "ایا ډاډه یاست چې غواړئ دا درجه پاکه کړئ؟ دا عمل بېرته نه ګرځیدونکی دی.",
    deleted: "درجه په بریالیتوب سره پاکه شوه",
    deleteError: "د درجې په پاکولو کې تېروتنه",
    edit: "درجه سمه کړئ",
    editDescription: "د درجې تفصیل سم کړئ",
    failing: "ناکام",
    failingGrade: "د ناکامۍ درجه",
    isPass: "د کامیابۍ درجه ده",
    list: "د درجو لیست",
    management: "د درجو مدیریت",
    managementDescription: "د نمرو او درجو سیسټم تنظیم کړئ",
    maxPercentage: "اعظمي سلنه",
    maxPercentagePlaceholder: "د اعظمي سلنې حد",
    minPercentagePlaceholder: "د لږترلږه سلنې حد",
    name: "نوم",
    nameAr: "نوم (عربي)",
    nameArPlaceholder: "نوم په عربي ژبه",
    nameEn: "نوم (انګلیسي)",
    nameEnPlaceholder: "نوم په انګلیسي ژبه",
    nameFa: "نوم (فارسي)",
    nameFaPlaceholder: "نوم په فارسي ژبه",
    namePs: "نوم (پښتو)",
    namePsPlaceholder: "نوم په پښتو ژبه",
    noGrades: "درجې ونه موندل شوې. د پیل لپاره لومړۍ درجه جوړه کړئ.",
    noGradesDescription: "تر اوسه د درجو سیسټم نه دی تعریف شوی.",
    order: "د ښودلو ترتیب",
    orderPlaceholder: "د ترتیب شمېره",
    passing: "کامیاب",
    passingGrade: "د کامیابۍ درجه",
    percentageRange: "د سلنې حد",
    title: "درجې",
    updated: "درجه په بریالیتوب سره تازه شوه",
    updateError: "د درجې په تازه کولو کې تېروتنه"
  }
};
