/**
 * grades page translations (ar).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  grades: {
    create: "إنشاء درجة",
    created: "تم إنشاء الدرجة بنجاح",
    createDescription: "Create description",
    createError: "فشل في إنشاء الدرجة",
    delete: "حذف الدرجة",
    deleteConfirmMessage: "هل أنت متأكد من أنك تريد حذف هذه الدرجة؟ لا يمكن التراجع عن هذا الإجراء.",
    deleted: "تم حذف الدرجة بنجاح",
    deleteError: "فشل في حذف الدرجة",
    edit: "تعديل الدرجة",
    editDescription: "Edit description",
    failing: "راسب",
    failingGrade: "درجة الرسوب",
    isPass: "هل هي درجة النجاح",
    list: "قائمة الدرجات",
    management: "إدارة الدرجات",
    managementDescription: "Management description",
    maxPercentage: "الحد الأقصى للنسبة المئوية",
    maxPercentagePlaceholder: "Max percentage placeholder",
    minPercentagePlaceholder: "Min percentage placeholder",
    name: "الاسم",
    nameAr: "الاسم (العربية)",
    nameArPlaceholder: "Name ar placeholder",
    nameEn: "الاسم (الإنجليزية)",
    nameEnPlaceholder: "Name en placeholder",
    nameFa: "الاسم (الفارسية)",
    nameFaPlaceholder: "Name fa placeholder",
    namePs: "الاسم (البشتو)",
    namePsPlaceholder: "Name ps placeholder",
    noGrades: "لم يتم العثور على درجات. قم بإنشاء درجتك الأولى للبدء.",
    noGradesDescription: "No grades description",
    order: "ترتيب العرض",
    orderPlaceholder: "Order placeholder",
    passing: "ناجح",
    passingGrade: "درجة النجاح",
    percentageRange: "نطاق النسبة المئوية",
    title: "الدرجات",
    updated: "تم تحديث الدرجة بنجاح",
    updateError: "فشل في تحديث الدرجة"
  }
};
