/**
 * Shared validation translations (fa).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  validation: {
    ageMax: "سن باید برای مکتب واقع‌بینانه باشد",
    ageMin: "سن باید حداقل {min} باشد",
    atLeastOneEntryRequired: "حداقل یک مدخل الزامی است",
    currentPasswordRequired: "رمز عبور فعلی الزامی است",
    endDateAfterStart: "تاریخ پایان باید بعد از تاریخ شروع یا برابر با آن باشد",
    fieldMaxLength: "{fieldName} باید {max} کاراکتر یا کمتر باشد",
    fieldRequired: "{fieldName} الزامی است",
    fileRequired: "فایل الزامی است",
    fileSizeMax: "حجم فایل باید کمتر از {maxMB} مگابایت باشد",
    fileTypeInvalid: "نوع فایل باید یکی از موارد زیر باشد: {types}",
    incidentDateRequired: "تاریخ حادثه الزامی است",
    invalidClassInstance: "صنف نامعتبر است",
    invalidScheduleSlot: "وقت برنامه نامعتبر است",
    invalidScheduleSlotId: "شناسه وقت برنامه نامعتبر است",
    invalidSubject: "مضمون نامعتبر است",
    invalidTeacher: "معلم نامعتبر است",
    invalidUuid: "فرمت UUID نامعتبر است",
    passwordConfirmationRequired: "تأیید رمز عبور الزامی است",
    passwordLowercase: "رمز عبور باید حداقل یک حرف کوچک داشته باشد",
    passwordNumber: "رمز عبور باید حداقل یک عدد داشته باشد",
    passwordsDoNotMatch: "رمزهای عبور مطابقت ندارند",
    passwordSpecial: "رمز عبور باید حداقل یک کاراکتر خاص داشته باشد",
    passwordUppercase: "رمز عبور باید حداقل یک حرف بزرگ داشته باشد",
    phoneMaxLength: "شماره تلفون باید ۳۰ کاراکتر یا کمتر باشد",
    teacherRequired: "معلم الزامی است"
  }
};
