/**
 * Shared validation translations (en).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  validation: {
    ageMax: "Age must be realistic for school",
    ageMin: "Age must be at least {min}",
    atLeastOneEntryRequired: "At least one entry is required",
    currentPasswordRequired: "Current password is required",
    endDateAfterStart: "End date must be after or equal to start date",
    fieldMaxLength: "{fieldName} must be {max} characters or less",
    fieldRequired: "{fieldName} is required",
    fileRequired: "File is required",
    fileSizeMax: "File size must be less than {maxMB}MB",
    fileTypeInvalid: "File type must be one of: {types}",
    incidentDateRequired: "Incident date is required",
    invalidClassInstance: "Invalid class instance",
    invalidScheduleSlot: "Invalid schedule slot",
    invalidScheduleSlotId: "Invalid schedule slot ID",
    invalidSubject: "Invalid subject",
    invalidTeacher: "Invalid teacher",
    invalidUuid: "Invalid UUID format",
    passwordConfirmationRequired: "Password confirmation is required",
    passwordLowercase: "Password must contain at least one lowercase letter",
    passwordNumber: "Password must contain at least one number",
    passwordsDoNotMatch: "Passwords do not match",
    passwordSpecial: "Password must contain at least one special character",
    passwordUppercase: "Password must contain at least one uppercase letter",
    phoneMaxLength: "Phone number must be 30 characters or less",
    teacherRequired: "Teacher is required"
  }
};
