/**
 * Shared validation translations (ps).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  validation: {
    ageMax: "عمر باید د ښوونځي لپاره حقیقي وي",
    ageMin: "عمر باید لږترلږه {min} وي",
    atLeastOneEntryRequired: "لږترلږه یوه ننوتنه اړینه ده",
    currentPasswordRequired: "اوسنی پاسورډ اړین دی",
    endDateAfterStart: "د پای نېټه باید د پیل نېټې وروسته یا مساوي وي",
    fieldMaxLength: "{fieldName} باید {max} حروف یا لږ وي",
    fieldRequired: "{fieldName} اړین دی",
    fileRequired: "فایل اړین دی",
    fileSizeMax: "د فایل اندازه باید د {maxMB}MB څخه کم وي",
    fileTypeInvalid: "د فایل ډول باید یو له دې څخه وي: {types}",
    incidentDateRequired: "د پېښې نېټه اړینه ده",
    invalidClassInstance: "ناسم ټولګي مثال",
    invalidScheduleSlot: "ناسم مهالوېش سلاټ",
    invalidScheduleSlotId: "ناسم مهالوېش سلاټ ID",
    invalidSubject: "ناسم مضمون",
    invalidTeacher: "ناسم ښوونکی",
    invalidUuid: "ناسم UUID بڼه",
    passwordConfirmationRequired: "د پاسورډ تایید اړین دی",
    passwordLowercase: "پاسورډ باید لږترلږه یو کوچنی توری ولري",
    passwordNumber: "پاسورډ باید لږترلږه یوه شمیره ولري",
    passwordsDoNotMatch: "پاسورډونه سره نه خوري",
    passwordSpecial: "پاسورډ باید لږترلږه یو ځانګړی کرکټر ولري",
    passwordUppercase: "پاسورډ باید لږترلږه یو لوی توری ولري",
    phoneMaxLength: "د تلیفون شمیره باید 30 حروف یا لږ وي",
    teacherRequired: "ښوونکی اړین دی"
  }
};
