/**
 * onboarding page translations (fa).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  onboarding: {
    welcome: {
      title: "به سیستم مدیریت مکتب ناظم خوش آمدید",
      description: "با مشاهده راهنمای سیستم یا خواندن راهنما، از تمام ویژگی‌های موجود در سیستم مطلع شوید."
    },
    actions: {
      takeTour: "مشاهده راهنما",
      skip: "رد کردن",
      initialSetup: "initial Setup"
    },
    tour: {
      dashboard: "داشبورد",
      sidebar: "منو",
      users: "کاربران",
      schools: "مکاتب",
      academic: "آموزشی",
      students: "شاگردان",
      staff: "کارمندان",
      settings: "تنظیمات",
      subscription: "اشتراک",
      help: "کمک"
    },
    schoolSetup: {
      title: "راهنمای تنظیم مکتب",
      description: "راهنمای کامل برای تنظیم مکتب شما: جزئیات مکتب، سال‌های تحصیلی، کلاس‌ها و مضامین",
      steps: {
        editSchoolDetails: {
          title: "ویرایش جزئیات مکتب",
          text: {}
        },
        createAcademicYear: {
          title: "ایجاد سال تحصیلی",
          text: {}
        },
        createClasses: {
          title: "ایجاد کلاس‌ها",
          text: {}
        },
        assignClassesToYear: {
          title: "اختصاص کلاس‌ها به سال تحصیلی",
          text: {}
        },
        createSubjects: {
          title: "ایجاد مضامین",
          text: {}
        },
        assignSubjectsClassLevel: {
          title: "اختصاص مضامین به کلاس‌ها (سطح کلاس)",
          text: {}
        },
        assignSubjectsAcademicYear: {
          title: "اختصاص مضامین به کلاس‌ها (محدوده سال تحصیلی)",
          text: {}
        }
      }
    }
  }
};
