/**
 * onboarding page translations (ps).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  onboarding: {
    welcome: {
      title: "ناظم. د دیني مدارسو د مالي او اداري چارو د تنظیم سیسټم ته ښه راغلاست",
      description: "د سیسټم د ټولو ځانګړتیاوو د زده کړې لپاره لارښود ولوستئ یا د سیسټم لارښود وګورئ."
    },
    actions: {
      takeTour: "لارښود وګورئ",
      skip: "پرېښودل",
      initialSetup: "لومړنی تنظیم"
    },
    tour: {
      dashboard: "ډشبورډ",
      sidebar: "منو",
      users: "کاروونکي",
      schools: "ښوونځي",
      academic: "روزنیز",
      students: "زده کوونکي",
      staff: "کارکوونکي",
      settings: "تنظیمات",
      subscription: "ګډون",
      help: "مرسته"
    },
    schoolSetup: {
      title: "د ښوونځي د ترتیب لارښود",
      description: "د خپل ښوونځي د تنظیمولو بشپړ لارښود: د ښوونځي جزئیات، اکاډمیک کلونه، ټولګي، او موضوعات",
      steps: {
        editSchoolDetails: {
          title: "د ښوونځي جزئیات سمول",
          text: {}
        },
        createAcademicYear: {
          title: "اکاډمیک کال رامینځته کول",
          text: {}
        },
        createClasses: {
          title: "ټولګي رامینځته کول",
          text: {}
        },
        assignClassesToYear: {
          title: "ټولګي اکاډمیک کال ته وټاکل",
          text: {}
        },
        createSubjects: {
          title: "موضوعات رامینځته کول",
          text: {}
        },
        assignSubjectsClassLevel: {
          title: "موضوعات ټولګیو ته وټاکل (د ټولګي کچه)",
          text: {}
        },
        assignSubjectsAcademicYear: {
          title: "موضوعات ټولګیو ته وټاکل (د اکاډمیک کال ساحه)",
          text: {}
        }
      }
    }
  }
};
