/**
 * onboarding page translations (en).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  onboarding: {
    welcome: {
      title: "Welcome to Nazim School Management System",
      description: "Get started by taking a tour of the system or reading the guide to learn about all the features available to you."
    },
    actions: {
      takeTour: "Take a Tour",
      skip: "Skip",
      initialSetup: "initial Setup"
    },
    tour: {
      dashboard: "Dashboard",
      sidebar: "Navigation",
      users: "Users",
      schools: "Schools",
      academic: "Academic",
      students: "Students",
      staff: "Staff",
      settings: "Settings",
      subscription: "Subscription",
      help: "Help"
    },
    schoolSetup: {
      title: "School Setup Tour",
      description: "Complete guide to setting up your school: school details, academic years, classes, and subjects",
      steps: {
        editSchoolDetails: {
          title: "Edit School Details",
          text: {}
        },
        createAcademicYear: {
          title: "Create Academic Year",
          text: {}
        },
        createClasses: {
          title: "Create Classes",
          text: {}
        },
        assignClassesToYear: {
          title: "Assign Classes to Academic Year",
          text: {}
        },
        createSubjects: {
          title: "Create Subjects",
          text: {}
        },
        assignSubjectsClassLevel: {
          title: "Assign Subjects to Classes (Class-level)",
          text: {}
        },
        assignSubjectsAcademicYear: {
          title: "Assign Subjects to Classes (Academic-year scoped)",
          text: {}
        }
      }
    }
  }
};
