/**
 * onboarding page translations (ar).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  onboarding: {
    welcome: {
      title: "مرحباً بك في نظام إدارة مدرسة ناظم",
      description: "ابدأ بجولة تعريفية في النظام أو اقرأ الدليل للتعرف على جميع الميزات المتاحة لك."
    },
    actions: {
      takeTour: "جولة تعريفية",
      skip: "تخطي",
      initialSetup: "initial Setup"
    },
    tour: {
      dashboard: "لوحة التحكم",
      sidebar: "القائمة",
      users: "المستخدمين",
      schools: "المدارس",
      academic: "الأكاديمي",
      students: "الطلاب",
      staff: "الموظفين",
      settings: "الإعدادات",
      subscription: "الاشتراك",
      help: "المساعدة"
    },
    schoolSetup: {
      title: "جولة إعداد المدرسة",
      description: "دليل كامل لإعداد مدرستك: تفاصيل المدرسة، السنوات الأكاديمية، الفصول والمواد",
      steps: {
        editSchoolDetails: {
          title: "تعديل تفاصيل المدرسة",
          text: {}
        },
        createAcademicYear: {
          title: "إنشاء سنة أكاديمية",
          text: {}
        },
        createClasses: {
          title: "إنشاء الفصول",
          text: {}
        },
        assignClassesToYear: {
          title: "تعيين الفصول للسنة الأكاديمية",
          text: {}
        },
        createSubjects: {
          title: "إنشاء المواد",
          text: {}
        },
        assignSubjectsClassLevel: {
          title: "تعيين المواد للفصول (مستوى الفصل)",
          text: {}
        },
        assignSubjectsAcademicYear: {
          title: "تعيين المواد للفصول (نطاق السنة الأكاديمية)",
          text: {}
        }
      }
    }
  }
};
