/**
 * misc page translations (fa).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  buildings: {
    buildingCreated: "building Created",
    buildingUpdated: "building Updated",
    buildingDeleted: "building Deleted",
    viewAll: "مشاهده همه"
  },
  classes: {
    noClasses: "صنفی وجود ندارد",
    viewAll: "مشاهده همه"
  },
  articleFound: "مقاله برای کمک در این صفحه",
  browseHelpCenter: "مرور مرکز کمک",
  completionDate: "تاریخ تکمیل",
  contextualHelp: "کمک متنی",
  course: "کورس",
  courseDocuments: "اسناد کورس",
  deleteDocument: "حذف سند",
  deleteDocumentConfirm: "تایید حذف سند",
  documentDescription: "توضیحات سند",
  documentTitle: "عنوان سند",
  documentType: "نوع سند",
  errorLoading: "خطا در بارگذاری مقاله راهنما",
  generateCertificate: "تولید گواهینامه",
  generated: "تولید شد",
  generating: "در حال تولید...",
  generatingReport: "در حال تولید گزارش",
  goBack: "بازگشت",
  goHome: "رفتن به خانه",
  failed: "ناموفق بود"
};
