/**
 * misc page translations (fa).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  status: {
    issued: "صادر شده",
    approved: "تأیید شده",
    draft: "مسوده"
  },
  table: {
    students: "شاگردان"
  },
  buildings: {
    buildingCreated: "ساختمان ایجاد شد",
    buildingUpdated: "ساختمان به‌روزرسانی شد",
    buildingDeleted: "ساختمان حذف شد",
    viewAll: "مشاهده همه"
  },
  classes: {
    noClasses: "صنفی وجود ندارد",
    viewAll: "مشاهده همه"
  },
  articleFound: "مقاله برای کمک در این صفحه",
  browseHelpCenter: "مرور مرکز کمک",
  completionDate: "تاریخ تکمیل",
  contextualHelp: "کمک متنی",
  course: "کورس",
  courseDocuments: "اسناد کورس",
  deleteDocument: "حذف سند",
  deleteDocumentConfirm: "تایید حذف سند",
  documentDescription: "توضیحات سند",
  documentTitle: "عنوان سند",
  documentType: "نوع سند",
  errorLoading: "خطا در بارگذاری مقاله راهنما",
  generateCertificate: "تولید گواهینامه",
  generated: "تولید شد",
  generating: "در حال تولید...",
  generatingReport: "در حال تولید گزارش",
  goBack: "بازگشت",
  goHome: "رفتن به خانه",
  message: "صفحه‌ای که به دنبال آن هستید وجود ندارد.",
  noArticleFound: "هیچ مقاله راهنمایی برای این صفحه یافت نشد. در حال باز کردن مرکز راهنما...",
  noDocuments: "هیچ سندی نیست",
  pleaseWait: "لطفاً منتظر بمانید...",
  reportGeneration: "تولید گزارش",
  size: "حجم",
  student: "شاگرد",
  title: "صفحه یافت نشد",
  uploadDocument: "بارگذاری سند",
  uploaded: "بارگذاری شده",
  viewFullArticle: "مشاهده کامل مقاله",
  failed: "ناموفق بود"
};
