/**
 * misc page translations (ps).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  status: {
    issued: "صادر شوی",
    approved: "تصویب شوی",
    draft: "مسوده"
  },
  table: {
    students: "زده کوونکي"
  },
  buildings: {
    buildingCreated: "ودانۍ جوړه شوه",
    buildingUpdated: "ودانۍ تازه شوه",
    buildingDeleted: "ودانۍ ړنګه شوه",
    viewAll: "ټول کتل"
  },
  classes: {
    noClasses: "ټولګي نشته",
    viewAll: "ټول کتل"
  },
  articleFound: "د دې پاڼې اړوند مرستندویه مقاله",
  browseHelpCenter: "د مرستې مرکز کتل",
  completionDate: "د تکمیل نېټه",
  contextualHelp: "مرسته تر لاسه کړئ",
  course: "دوره / کورس",
  courseDocuments: "د دورې / کورس اسناد",
  deleteDocument: "سند حذف کړئ",
  deleteDocumentConfirm: "د سند حذفول تائید کړئ",
  documentDescription: "د سند تفصیل",
  documentTitle: "د سند عنوان",
  documentType: "د سند ډول",
  errorLoading: "د مقالې ترلاسه کولو په مهال ستونزه را منځته شوه",
  generateCertificate: "سند جوړ کړئ",
  generated: "جوړ شوی",
  generating: "د جوړېدو په حال کې...",
  generatingReport: "راپور د جوړېدو په حال کې دی",
  goBack: "شاته لاړ شئ",
  goHome: "کور پاڼې ته لاړ شئ",
  message: "هغه پاڼه چې تاسو یې لټوئ شتون نلري.",
  noArticleFound: "د دې پاڼې لپاره د مرستې مقاله ونه موندل شوه. د مرستې مرکز خلاصیږي...",
  noDocuments: "اسناد نشته",
  pleaseWait: "مهرباني وکړئ انتظار وکړئ...",
  reportGeneration: "د راپور جوړول",
  size: "اندازه",
  student: "زده کوونکی",
  title: "پاڼه ونه موندل شوه",
  uploadDocument: "سند اپلوډ کړئ",
  uploaded: "اپلوډ شوی",
  viewFullArticle: "بشپړه مقاله وګورئ",
  failed: "ناکام شو"
};
