/**
 * misc page translations (en).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  status: {
    issued: "issued",
    approved: "approved",
    draft: "draft"
  },
  table: {
    students: "students"
  },
  buildings: {
    buildingCreated: "building Created",
    buildingUpdated: "building Updated",
    buildingDeleted: "building Deleted",
    viewAll: "View All"
  },
  classes: {
    noClasses: "no Classes",
    viewAll: "View All"
  },
  articleFound: "Here is the help article for this page",
  browseHelpCenter: "Browse Help Center",
  completionDate: "Completion date",
  contextualHelp: "Get help",
  course: "Course",
  courseDocuments: "Course documents",
  deleteDocument: "Delete document",
  deleteDocumentConfirm: "Delete document confirm",
  documentDescription: "Document description",
  documentTitle: "Document title",
  documentType: "Document type",
  errorLoading: "Error loading help article",
  generateCertificate: "Generate certificate",
  generated: "راپور بریالی شو",
  generating: "راپور جوړیږي...",
  generatingReport: "Report generation in progress",
  goBack: "Go Back",
  goHome: "Go Home",
  message: "The page you are looking for does not exist.",
  noArticleFound: "No help article found for this page. Opening Help Center...",
  noDocuments: "No documents",
  pleaseWait: "مهرباني وکړئ انتظار وکړئ...",
  reportGeneration: "د راپور جوړول",
  size: "Size",
  student: "Student",
  title: "Page Not Found",
  uploadDocument: "Upload document",
  uploaded: "Uploaded",
  viewFullArticle: "View Full Article",
  failed: "راپور ناکام شو"
};
