/**
 * misc page translations (ar).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  status: {
    issued: "issued",
    approved: "approved",
    draft: "draft"
  },
  table: {
    students: "students"
  },
  buildings: {
    buildingCreated: "building Created",
    buildingUpdated: "building Updated",
    buildingDeleted: "building Deleted",
    viewAll: "عرض الكل"
  },
  classes: {
    noClasses: "no Classes",
    viewAll: "عرض الكل"
  },
  articleFound: undefined,
  browseHelpCenter: undefined,
  completionDate: undefined,
  contextualHelp: undefined,
  course: undefined,
  courseDocuments: undefined,
  deleteDocument: undefined,
  deleteDocumentConfirm: undefined,
  documentDescription: undefined,
  documentTitle: undefined,
  documentType: undefined,
  errorLoading: undefined,
  generateCertificate: undefined,
  generated: undefined,
  generating: undefined,
  generatingReport: undefined,
  goBack: undefined,
  goHome: undefined,
  message: undefined,
  noArticleFound: undefined,
  noDocuments: undefined,
  pleaseWait: undefined,
  reportGeneration: "د راپور جوړول",
  size: undefined,
  student: undefined,
  title: undefined,
  uploadDocument: undefined,
  uploaded: undefined,
  viewFullArticle: undefined,
  failed: undefined
};
