/**
 * roles page translations (ps).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  roles: {
    actions: "کړنې",
    cancel: "لغوه",
    create: "جوړ کړئ",
    createNewRole: "نوی رول جوړ کړئ",
    createRole: "رول جوړ کړئ",
    createRoleDialog: "رول جوړ کړئ",
    delete: "پاک کړئ",
    deleteRole: "رول پاک کړئ",
    description: "تفصیل",
    edit: "سم کړئ",
    editRole: "رول سم کړئ",
    global: "عمومي (Global)",
    name: "نوم",
    noRolesFound: "رول ونه موندل شو",
    noRolesMessage: "رولونه نشته. خپل لومړی رول جوړ کړئ.",
    organization: "سازمان",
    organizationRoles: "د اداره رولونه",
    organizationSpecific: "د اداره اړوند",
    roleNameCannotChange: "د رول نوم د بدلون وړ نه دی",
    roleNamePlaceholder: "د رول نوم ولیکئ",
    roleNameRequired: "د رول نوم اړین دی",
    subtitle: "په خپل اداره کې د کاروونکو رولونه مدیریت کړئ",
    title: "د رولونو مدیریت",
    totalRoles: "ټول رولونه",
    update: "تازه کول",
    updateRoleInfo: "د رول معلومات تازه کړئ"
  }
};
