/**
 * roles page translations (fa).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  roles: {
    actions: "Actions",
    cancel: "Cancel",
    create: "Create",
    createNewRole: "Create a new role",
    createRole: "Create Role",
    createRoleDialog: "Create Role",
    delete: "Delete",
    deleteRole: "Delete Role",
    description: "Description",
    edit: "Edit",
    editRole: "Edit Role",
    global: "Global",
    name: "Name",
    noRolesFound: "No roles found matching your search",
    noRolesMessage: "No roles found. Create your first role.",
    organization: "Organization",
    organizationRoles: "Organization Roles",
    organizationSpecific: "Organization Specific",
    roleNameCannotChange: "Role name cannot be changed",
    roleNamePlaceholder: "Enter role name",
    roleNameRequired: "Role name is required",
    subtitle: "Manage user roles within your organization",
    title: "Roles Management",
    totalRoles: "Total Roles",
    update: "Update",
    updateRoleInfo: "Update role information"
  }
};
