/**
 * roles page translations (ar).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  roles: {
    actions: "الإجراءات",
    cancel: "إلغاء",
    create: "إنشاء",
    createNewRole: "إنشاء دور جديد",
    createRole: "إنشاء دور",
    createRoleDialog: "إنشاء دور",
    delete: "حذف",
    deleteRole: "حذف الدور",
    description: "الوصف",
    edit: "تعديل",
    editRole: "تعديل الدور",
    global: "عالمي",
    name: "الاسم",
    noRolesFound: "لم يتم العثور على أدوار تطابق بحثك",
    noRolesMessage: "لم يتم العثور على أدوار. قم بإنشاء دورك الأول.",
    organization: "المنظمة",
    organizationRoles: "أدوار المنظمة",
    organizationSpecific: "خاص بالمنظمة",
    roleNameCannotChange: "لا يمكن تغيير اسم الدور",
    roleNamePlaceholder: "أدخل اسم الدور",
    roleNameRequired: "اسم الدور مطلوب",
    subtitle: "إدارة أدوار المستخدمين في منظمتك",
    title: "إدارة الأدوار",
    totalRoles: "إجمالي الأدوار",
    update: "تحديث",
    updateRoleInfo: "تحديث معلومات الدور"
  }
};
