/**
 * image-capture page translations (en).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  imageCapture: {
    takePhoto: "Take photo",
    capturePhoto: "Capture",
    cropImage: "Crop image",
    cropDescription: "Adjust the crop area, then click Done.",
    done: "Done",
    cameraAccessDenied: "Camera permission is required. Please allow camera access.",
    noCameraFound: "No camera found on this device.",
    cameraInUse: "Camera is already in use. Close other apps and try again.",
    cameraError: "Failed to start camera.",
    cameraHint: "Use \"Select Picture\" to choose a file instead.",
    cameraPreview: "Camera preview",
    fileTooLarge: "Image exceeds maximum size of 5MB. Please crop to a smaller area or use a lower resolution image.",
    cropFailed: "Failed to crop image. Please try again."
  }
};
