/**
 * image-capture page translations (fa).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  imageCapture: {
    takePhoto: "عکس بگیرید",
    capturePhoto: "ثبت",
    cropImage: "برش تصویر",
    cropDescription: "ناحیه برش را تنظیم کنید، سپس انجام دهید را بزنید.",
    done: "انجام شد",
    cameraAccessDenied: "دسترسی به دوربین لازم است. لطفاً اجازه دسترسی به دوربین را بدهید.",
    noCameraFound: "دوربینی در این دستگاه یافت نشد.",
    cameraInUse: "دوربین در حال استفاده است. برنامه‌های دیگر را ببندید و دوباره امتحان کنید.",
    cameraError: "راه‌اندازی دوربین ناموفق بود.",
    cameraHint: "برای انتخاب فایل از «انتخاب تصویر» استفاده کنید.",
    cameraPreview: "پیش‌نمایش دوربین",
    fileTooLarge: "تصویر از حداکثر ۵ مگابایت بیشتر است. لطفاً ناحیه کوچکتری برش دهید یا تصویر با وضوح کمتر استفاده کنید.",
    cropFailed: "برش تصویر ناموفق بود. لطفاً دوباره امتحان کنید."
  }
};
