import { useState, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { issuedCertificatesApi } from '@/lib/api/client';
import { useIssuedCertificates, useRevokeCertificate } from '@/hooks/useGraduation';
import { useSchools } from '@/hooks/useSchools';
import { useLanguage } from '@/hooks/useLanguage';
import { useAuth } from '@/hooks/useAuth';
import { GraduationCertificatePdfGenerator } from '@/components/graduation/GraduationCertificatePdfGenerator';
import { Eye } from 'lucide-react';

export default function IssuedCertificatesPage() {
  const { t } = useLanguage();
  const { profile } = useAuth();
  const { data: schools = [] } = useSchools();
  const [schoolId, setSchoolId] = useState<string | undefined>(undefined);
  const [batchId, setBatchId] = useState<string | undefined>(undefined);
  const [studentId, setStudentId] = useState<string | undefined>(undefined);
  const [previewCertificateId, setPreviewCertificateId] = useState<string | null>(null);
  const [isPreviewOpen, setIsPreviewOpen] = useState(false);

  // Auto-select school if there's only one, or use profile's default_school_id
  useEffect(() => {
    if (schools.length === 1 && !schoolId) {
      // Auto-select if only one school
      setSchoolId(schools[0].id);
    } else if (profile?.default_school_id && !schoolId) {
      // Use default school from profile if available
      setSchoolId(profile.default_school_id);
    }
  }, [schools, profile?.default_school_id, schoolId]);

  const { data: certificates = [], isLoading } = useIssuedCertificates({
    school_id: schoolId,
    batch_id: batchId,
    student_id: studentId,
  });

  const revoke = useRevokeCertificate();

  const handleDownload = async (id: string) => {
    const file = await issuedCertificatesApi.downloadPdf(id);
    const url = URL.createObjectURL(file.blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = file.filename || 'certificate.pdf';
    document.body.appendChild(link);
    link.click();
    link.remove();
    URL.revokeObjectURL(url);
  };

  const handleRevoke = async (id: string) => {
    const reason = window.prompt('Enter revoke reason');
    if (!reason) return;
    await revoke.mutateAsync({ id, reason });
  };

  const handlePreview = (certId: string) => {
    setPreviewCertificateId(certId);
    setIsPreviewOpen(true);
  };

  const handleClosePreview = () => {
    setIsPreviewOpen(false);
    setPreviewCertificateId(null);
  };

  return (
    <div className="space-y-6 max-w-6xl mx-auto">
      <Card>
        <CardHeader>
          <CardTitle>{t('certificates.issued') ?? 'Issued Certificates'}</CardTitle>
        </CardHeader>
        <CardContent className="grid grid-cols-1 md:grid-cols-4 gap-4">
          <div>
            <Label>{t('common.schoolManagement')}</Label>
            <Select value={schoolId || ''} onValueChange={(val) => setSchoolId(val || undefined)}>
              <SelectTrigger>
                <SelectValue placeholder={t('common.selectSchool')} />
              </SelectTrigger>
              <SelectContent>
                {schools.map((school) => (
                  <SelectItem key={school.id} value={school.id}>
                    {school.schoolName}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
          <div>
            <Label>{t('nav.graduation.batches')}</Label>
            <Input value={batchId || ''} onChange={(e) => setBatchId(e.target.value || undefined)} placeholder={t('common.autoGenerated')} />
          </div>
          <div>
            <Label>{t('students.name') ?? 'Student ID'}</Label>
            <Input value={studentId || ''} onChange={(e) => setStudentId(e.target.value || undefined)} placeholder="Student ID" />
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>{t('certificates.issued') ?? 'Issued Certificates'}</CardTitle>
        </CardHeader>
        <CardContent>
          {isLoading ? (
            <p>{t('common.loading')}</p>
          ) : certificates.length === 0 ? (
            <div className="text-center py-8 text-muted-foreground">
              <p>{t('common.noData') || 'No certificates found'}</p>
              <p className="text-xs mt-2">
                {t('certificates.noIssuedCertificates') || 'No certificates have been issued yet, or you may not have permission to view them.'}
              </p>
            </div>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Certificate No</TableHead>
                  <TableHead>{t('students.name') ?? 'Student'}</TableHead>
                  <TableHead>{t('common.statusLabel')}</TableHead>
                  <TableHead>Issued At</TableHead>
                  <TableHead>{t('common.actions')}</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {certificates.map((cert: any) => (
                  <TableRow key={cert.id}>
                    <TableCell>{cert.certificate_no}</TableCell>
                    <TableCell>{cert.student?.full_name || cert.student_id}</TableCell>
                    <TableCell>{cert.revoked_at ? 'Revoked' : 'Valid'}</TableCell>
                    <TableCell>{cert.issued_at}</TableCell>
                    <TableCell className="space-x-2">
                      <Button
                        size="sm"
                        variant="ghost"
                        onClick={() => handlePreview(cert.id)}
                        title="Preview Certificate"
                      >
                        <Eye className="h-4 w-4" />
                      </Button>
                      <Button size="sm" variant="outline" onClick={() => handleDownload(cert.id)}>
                        {t('common.download')}
                      </Button>
                      {!cert.revoked_at && (
                        <Button size="sm" variant="ghost" onClick={() => handleRevoke(cert.id)}>
                          Revoke
                        </Button>
                      )}
                      <Button size="sm" variant="link" asChild>
                        <a href={`/verify/certificate/${cert.verification_hash}`} target="_blank" rel="noreferrer">
                          Verify
                        </a>
                      </Button>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </CardContent>
      </Card>

      {/* Certificate Preview Dialog */}
      {previewCertificateId && (
        <GraduationCertificatePdfGenerator
          certificateId={previewCertificateId}
          schoolId={schoolId}
          isOpen={isPreviewOpen}
          onClose={handleClosePreview}
        />
      )}
    </div>
  );
}
