/**
 * AR translations - merged from per-page structure.
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 * Source: shared/ and pages/ directory structure
 */

import { websitePublicAr } from './website/public-ar';
import { websiteAdminAr } from './website/admin-ar';

import shared_common_ar from './shared/common/common.ar';
import shared_nav_ar from './shared/nav/nav.ar';
import shared_toast_ar from './shared/toast/toast.ar';
import shared_forms_ar from './shared/forms/forms.ar';
import shared_validation_ar from './shared/validation/validation.ar';
import shared_pagination_ar from './shared/pagination/pagination.ar';
import shared_ui_ar from './shared/ui/ui.ar';
import shared_errorBoundary_ar from './shared/errorBoundary/errorBoundary.ar';
import shared_notFound_ar from './shared/notFound/notFound.ar';
import shared_footer_ar from './shared/footer/footer.ar';
import shared_search_ar from './shared/search/search.ar';
import shared_privacyPolicy_ar from './shared/privacyPolicy/privacyPolicy.ar';
import shared_termsOfService_ar from './shared/termsOfService/termsOfService.ar';
import shared_resetPassword_ar from './shared/resetPassword/resetPassword.ar';
import pages_academic_ar from './pages/academic/academic.ar';
import pages_admissions_ar from './pages/admissions/admissions.ar';
import pages_activity_logs_ar from './pages/activity-logs/activityLogs.ar';
import pages_assets_ar from './pages/assets/assets.ar';
import pages_attendance_ar from './pages/attendance/attendance.ar';
import pages_auth_ar from './pages/auth/auth.ar';
import pages_certificates_ar from './pages/certificates/certificates.ar';
import pages_courses_ar from './pages/courses/courses.ar';
import pages_dashboard_ar from './pages/dashboard/dashboard.ar';
import pages_dms_ar from './pages/dms/dms.ar';
import pages_events_ar from './pages/events/events.ar';
import pages_exams_ar from './pages/exams/exams.ar';
import pages_fees_ar from './pages/fees/fees.ar';
import pages_finance_ar from './pages/finance/finance.ar';
import pages_grades_ar from './pages/grades/grades.ar';
import pages_guards_ar from './pages/guards/guards.ar';
import pages_help_center_ar from './pages/help-center/helpCenter.ar';
import pages_hostel_ar from './pages/hostel/hostel.ar';
import pages_id_cards_ar from './pages/id-cards/idCards.ar';
import pages_image_capture_ar from './pages/image-capture/imageCapture.ar';
import pages_leave_ar from './pages/leave/leave.ar';
import pages_library_ar from './pages/library/library.ar';
import pages_maintenance_ar from './pages/maintenance/maintenance.ar';
import pages_onboarding_ar from './pages/onboarding/onboarding.ar';
import pages_organizations_ar from './pages/organizations/organizations.ar';
import pages_permissions_ar from './pages/permissions/permissions.ar';
import pages_phone_book_ar from './pages/phone-book/phoneBook.ar';
import pages_profile_management_ar from './pages/profile-management/profileManagement.ar';
import pages_question_bank_ar from './pages/question-bank/questionBank.ar';
import pages_reports_ar from './pages/reports/reports.ar';
import pages_roles_ar from './pages/roles/roles.ar';
import pages_schools_ar from './pages/schools/schools.ar';
import pages_settings_ar from './pages/settings/settings.ar';
import pages_short_term_courses_ar from './pages/short-term-courses/shortTermCourses.ar';
import pages_staff_ar from './pages/staff/staff.ar';
import pages_student_report_ar from './pages/student-report/studentReport.ar';
import pages_students_ar from './pages/students/students.ar';
import pages_student_history_ar from './pages/student-history/studentHistory.ar';
import pages_subscription_ar from './pages/subscription/subscription.ar';
import pages_subjects_ar from './pages/subjects/subjects.ar';
import pages_teacher_subject_assignments_ar from './pages/teacher-subject-assignments/teacherSubjectAssignments.ar';
import pages_timetable_ar from './pages/timetable/timetable.ar';
import pages_user_management_ar from './pages/user-management/userManagement.ar';
import pages_user_permissions_ar from './pages/user-permissions/userPermissions.ar';
import pages_watermarks_ar from './pages/watermarks/watermarks.ar';
import pages_graduation_ar from './pages/graduation/graduation.ar';
import pages_website_admin_ar from './pages/website-admin/websiteAdmin.ar';
import pages_platform_ar from './pages/platform/platform.ar';
import pages_misc_ar from './pages/misc/misc.ar';

export const ar = {
  ...websitePublicAr,
  ...shared_common_ar,
  ...shared_nav_ar,
  ...shared_toast_ar,
  ...shared_forms_ar,
  ...shared_validation_ar,
  ...shared_pagination_ar,
  ...shared_ui_ar,
  ...shared_errorBoundary_ar,
  ...shared_notFound_ar,
  ...shared_footer_ar,
  ...shared_search_ar,
  ...shared_privacyPolicy_ar,
  ...shared_termsOfService_ar,
  ...shared_resetPassword_ar,
  ...pages_academic_ar,
  ...pages_admissions_ar,
  ...pages_activity_logs_ar,
  ...pages_assets_ar,
  ...pages_attendance_ar,
  ...pages_auth_ar,
  ...pages_certificates_ar,
  ...pages_courses_ar,
  ...pages_dashboard_ar,
  ...pages_dms_ar,
  ...pages_events_ar,
  ...pages_exams_ar,
  ...pages_fees_ar,
  ...pages_finance_ar,
  ...pages_grades_ar,
  ...pages_guards_ar,
  ...pages_help_center_ar,
  ...pages_hostel_ar,
  ...pages_id_cards_ar,
  ...pages_image_capture_ar,
  ...pages_leave_ar,
  ...pages_library_ar,
  ...pages_maintenance_ar,
  ...pages_onboarding_ar,
  ...pages_organizations_ar,
  ...pages_permissions_ar,
  ...pages_phone_book_ar,
  ...pages_profile_management_ar,
  ...pages_question_bank_ar,
  ...pages_reports_ar,
  ...pages_roles_ar,
  ...pages_schools_ar,
  ...pages_settings_ar,
  ...pages_short_term_courses_ar,
  ...pages_staff_ar,
  ...pages_student_report_ar,
  ...pages_students_ar,
  ...pages_student_history_ar,
  ...pages_subscription_ar,
  ...pages_subjects_ar,
  ...pages_teacher_subject_assignments_ar,
  ...pages_timetable_ar,
  ...pages_user_management_ar,
  ...pages_user_permissions_ar,
  ...pages_watermarks_ar,
  ...pages_graduation_ar,
  ...pages_website_admin_ar,
  ...pages_platform_ar,
  ...pages_misc_ar,
  websiteManager: websiteAdminAr.websiteManager,
  website: websiteAdminAr.website,
};
