/**
 * EN translations - merged from per-page structure.
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 * Source: shared/ and pages/ directory structure
 */

import { websitePublicEn } from './website/public-en';
import { websiteAdminEn } from './website/admin-en';

import shared_common_en from './shared/common/common.en';
import shared_nav_en from './shared/nav/nav.en';
import shared_toast_en from './shared/toast/toast.en';
import shared_forms_en from './shared/forms/forms.en';
import shared_validation_en from './shared/validation/validation.en';
import shared_pagination_en from './shared/pagination/pagination.en';
import shared_ui_en from './shared/ui/ui.en';
import shared_errorBoundary_en from './shared/errorBoundary/errorBoundary.en';
import shared_notFound_en from './shared/notFound/notFound.en';
import shared_footer_en from './shared/footer/footer.en';
import shared_search_en from './shared/search/search.en';
import shared_privacyPolicy_en from './shared/privacyPolicy/privacyPolicy.en';
import shared_termsOfService_en from './shared/termsOfService/termsOfService.en';
import shared_resetPassword_en from './shared/resetPassword/resetPassword.en';
import pages_academic_en from './pages/academic/academic.en';
import pages_admissions_en from './pages/admissions/admissions.en';
import pages_activity_logs_en from './pages/activity-logs/activityLogs.en';
import pages_assets_en from './pages/assets/assets.en';
import pages_attendance_en from './pages/attendance/attendance.en';
import pages_auth_en from './pages/auth/auth.en';
import pages_certificates_en from './pages/certificates/certificates.en';
import pages_courses_en from './pages/courses/courses.en';
import pages_dashboard_en from './pages/dashboard/dashboard.en';
import pages_dms_en from './pages/dms/dms.en';
import pages_events_en from './pages/events/events.en';
import pages_exams_en from './pages/exams/exams.en';
import pages_fees_en from './pages/fees/fees.en';
import pages_finance_en from './pages/finance/finance.en';
import pages_grades_en from './pages/grades/grades.en';
import pages_guards_en from './pages/guards/guards.en';
import pages_help_center_en from './pages/help-center/helpCenter.en';
import pages_hostel_en from './pages/hostel/hostel.en';
import pages_id_cards_en from './pages/id-cards/idCards.en';
import pages_image_capture_en from './pages/image-capture/imageCapture.en';
import pages_leave_en from './pages/leave/leave.en';
import pages_library_en from './pages/library/library.en';
import pages_maintenance_en from './pages/maintenance/maintenance.en';
import pages_onboarding_en from './pages/onboarding/onboarding.en';
import pages_organizations_en from './pages/organizations/organizations.en';
import pages_permissions_en from './pages/permissions/permissions.en';
import pages_phone_book_en from './pages/phone-book/phoneBook.en';
import pages_profile_management_en from './pages/profile-management/profileManagement.en';
import pages_question_bank_en from './pages/question-bank/questionBank.en';
import pages_reports_en from './pages/reports/reports.en';
import pages_roles_en from './pages/roles/roles.en';
import pages_schools_en from './pages/schools/schools.en';
import pages_settings_en from './pages/settings/settings.en';
import pages_short_term_courses_en from './pages/short-term-courses/shortTermCourses.en';
import pages_staff_en from './pages/staff/staff.en';
import pages_student_report_en from './pages/student-report/studentReport.en';
import pages_students_en from './pages/students/students.en';
import pages_student_history_en from './pages/student-history/studentHistory.en';
import pages_subscription_en from './pages/subscription/subscription.en';
import pages_subjects_en from './pages/subjects/subjects.en';
import pages_teacher_subject_assignments_en from './pages/teacher-subject-assignments/teacherSubjectAssignments.en';
import pages_timetable_en from './pages/timetable/timetable.en';
import pages_user_management_en from './pages/user-management/userManagement.en';
import pages_user_permissions_en from './pages/user-permissions/userPermissions.en';
import pages_watermarks_en from './pages/watermarks/watermarks.en';
import pages_graduation_en from './pages/graduation/graduation.en';
import pages_website_admin_en from './pages/website-admin/websiteAdmin.en';
import pages_platform_en from './pages/platform/platform.en';
import pages_misc_en from './pages/misc/misc.en';

export const en = {
  ...websitePublicEn,
  ...shared_common_en,
  ...shared_nav_en,
  ...shared_toast_en,
  ...shared_forms_en,
  ...shared_validation_en,
  ...shared_pagination_en,
  ...shared_ui_en,
  ...shared_errorBoundary_en,
  ...shared_notFound_en,
  ...shared_footer_en,
  ...shared_search_en,
  ...shared_privacyPolicy_en,
  ...shared_termsOfService_en,
  ...shared_resetPassword_en,
  ...pages_academic_en,
  ...pages_admissions_en,
  ...pages_activity_logs_en,
  ...pages_assets_en,
  ...pages_attendance_en,
  ...pages_auth_en,
  ...pages_certificates_en,
  ...pages_courses_en,
  ...pages_dashboard_en,
  ...pages_dms_en,
  ...pages_events_en,
  ...pages_exams_en,
  ...pages_fees_en,
  ...pages_finance_en,
  ...pages_grades_en,
  ...pages_guards_en,
  ...pages_help_center_en,
  ...pages_hostel_en,
  ...pages_id_cards_en,
  ...pages_image_capture_en,
  ...pages_leave_en,
  ...pages_library_en,
  ...pages_maintenance_en,
  ...pages_onboarding_en,
  ...pages_organizations_en,
  ...pages_permissions_en,
  ...pages_phone_book_en,
  ...pages_profile_management_en,
  ...pages_question_bank_en,
  ...pages_reports_en,
  ...pages_roles_en,
  ...pages_schools_en,
  ...pages_settings_en,
  ...pages_short_term_courses_en,
  ...pages_staff_en,
  ...pages_student_report_en,
  ...pages_students_en,
  ...pages_student_history_en,
  ...pages_subscription_en,
  ...pages_subjects_en,
  ...pages_teacher_subject_assignments_en,
  ...pages_timetable_en,
  ...pages_user_management_en,
  ...pages_user_permissions_en,
  ...pages_watermarks_en,
  ...pages_graduation_en,
  ...pages_website_admin_en,
  ...pages_platform_en,
  ...pages_misc_en,
  websiteManager: websiteAdminEn.websiteManager,
  website: websiteAdminEn.website,
};
