/**
 * FA translations - merged from per-page structure.
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 * Source: shared/ and pages/ directory structure
 */

import { websitePublicFa } from './website/public-fa';
import { websiteAdminFa } from './website/admin-fa';

import shared_common_fa from './shared/common/common.fa';
import shared_nav_fa from './shared/nav/nav.fa';
import shared_toast_fa from './shared/toast/toast.fa';
import shared_forms_fa from './shared/forms/forms.fa';
import shared_validation_fa from './shared/validation/validation.fa';
import shared_pagination_fa from './shared/pagination/pagination.fa';
import shared_ui_fa from './shared/ui/ui.fa';
import shared_errorBoundary_fa from './shared/errorBoundary/errorBoundary.fa';
import shared_notFound_fa from './shared/notFound/notFound.fa';
import shared_footer_fa from './shared/footer/footer.fa';
import shared_search_fa from './shared/search/search.fa';
import shared_privacyPolicy_fa from './shared/privacyPolicy/privacyPolicy.fa';
import shared_termsOfService_fa from './shared/termsOfService/termsOfService.fa';
import shared_resetPassword_fa from './shared/resetPassword/resetPassword.fa';
import pages_academic_fa from './pages/academic/academic.fa';
import pages_admissions_fa from './pages/admissions/admissions.fa';
import pages_activity_logs_fa from './pages/activity-logs/activityLogs.fa';
import pages_assets_fa from './pages/assets/assets.fa';
import pages_attendance_fa from './pages/attendance/attendance.fa';
import pages_auth_fa from './pages/auth/auth.fa';
import pages_certificates_fa from './pages/certificates/certificates.fa';
import pages_courses_fa from './pages/courses/courses.fa';
import pages_dashboard_fa from './pages/dashboard/dashboard.fa';
import pages_dms_fa from './pages/dms/dms.fa';
import pages_events_fa from './pages/events/events.fa';
import pages_exams_fa from './pages/exams/exams.fa';
import pages_fees_fa from './pages/fees/fees.fa';
import pages_finance_fa from './pages/finance/finance.fa';
import pages_grades_fa from './pages/grades/grades.fa';
import pages_guards_fa from './pages/guards/guards.fa';
import pages_help_center_fa from './pages/help-center/helpCenter.fa';
import pages_hostel_fa from './pages/hostel/hostel.fa';
import pages_id_cards_fa from './pages/id-cards/idCards.fa';
import pages_image_capture_fa from './pages/image-capture/imageCapture.fa';
import pages_leave_fa from './pages/leave/leave.fa';
import pages_library_fa from './pages/library/library.fa';
import pages_maintenance_fa from './pages/maintenance/maintenance.fa';
import pages_onboarding_fa from './pages/onboarding/onboarding.fa';
import pages_organizations_fa from './pages/organizations/organizations.fa';
import pages_permissions_fa from './pages/permissions/permissions.fa';
import pages_phone_book_fa from './pages/phone-book/phoneBook.fa';
import pages_profile_management_fa from './pages/profile-management/profileManagement.fa';
import pages_question_bank_fa from './pages/question-bank/questionBank.fa';
import pages_reports_fa from './pages/reports/reports.fa';
import pages_roles_fa from './pages/roles/roles.fa';
import pages_schools_fa from './pages/schools/schools.fa';
import pages_settings_fa from './pages/settings/settings.fa';
import pages_short_term_courses_fa from './pages/short-term-courses/shortTermCourses.fa';
import pages_staff_fa from './pages/staff/staff.fa';
import pages_student_report_fa from './pages/student-report/studentReport.fa';
import pages_students_fa from './pages/students/students.fa';
import pages_student_history_fa from './pages/student-history/studentHistory.fa';
import pages_subscription_fa from './pages/subscription/subscription.fa';
import pages_subjects_fa from './pages/subjects/subjects.fa';
import pages_teacher_subject_assignments_fa from './pages/teacher-subject-assignments/teacherSubjectAssignments.fa';
import pages_timetable_fa from './pages/timetable/timetable.fa';
import pages_user_management_fa from './pages/user-management/userManagement.fa';
import pages_user_permissions_fa from './pages/user-permissions/userPermissions.fa';
import pages_watermarks_fa from './pages/watermarks/watermarks.fa';
import pages_graduation_fa from './pages/graduation/graduation.fa';
import pages_website_admin_fa from './pages/website-admin/websiteAdmin.fa';
import pages_platform_fa from './pages/platform/platform.fa';
import pages_misc_fa from './pages/misc/misc.fa';

export const fa = {
  ...websitePublicFa,
  ...shared_common_fa,
  ...shared_nav_fa,
  ...shared_toast_fa,
  ...shared_forms_fa,
  ...shared_validation_fa,
  ...shared_pagination_fa,
  ...shared_ui_fa,
  ...shared_errorBoundary_fa,
  ...shared_notFound_fa,
  ...shared_footer_fa,
  ...shared_search_fa,
  ...shared_privacyPolicy_fa,
  ...shared_termsOfService_fa,
  ...shared_resetPassword_fa,
  ...pages_academic_fa,
  ...pages_admissions_fa,
  ...pages_activity_logs_fa,
  ...pages_assets_fa,
  ...pages_attendance_fa,
  ...pages_auth_fa,
  ...pages_certificates_fa,
  ...pages_courses_fa,
  ...pages_dashboard_fa,
  ...pages_dms_fa,
  ...pages_events_fa,
  ...pages_exams_fa,
  ...pages_fees_fa,
  ...pages_finance_fa,
  ...pages_grades_fa,
  ...pages_guards_fa,
  ...pages_help_center_fa,
  ...pages_hostel_fa,
  ...pages_id_cards_fa,
  ...pages_image_capture_fa,
  ...pages_leave_fa,
  ...pages_library_fa,
  ...pages_maintenance_fa,
  ...pages_onboarding_fa,
  ...pages_organizations_fa,
  ...pages_permissions_fa,
  ...pages_phone_book_fa,
  ...pages_profile_management_fa,
  ...pages_question_bank_fa,
  ...pages_reports_fa,
  ...pages_roles_fa,
  ...pages_schools_fa,
  ...pages_settings_fa,
  ...pages_short_term_courses_fa,
  ...pages_staff_fa,
  ...pages_student_report_fa,
  ...pages_students_fa,
  ...pages_student_history_fa,
  ...pages_subscription_fa,
  ...pages_subjects_fa,
  ...pages_teacher_subject_assignments_fa,
  ...pages_timetable_fa,
  ...pages_user_management_fa,
  ...pages_user_permissions_fa,
  ...pages_watermarks_fa,
  ...pages_graduation_fa,
  ...pages_website_admin_fa,
  ...pages_platform_fa,
  ...pages_misc_fa,
  websiteManager: websiteAdminFa.websiteManager,
  website: websiteAdminFa.website,
};
