/**
 * PS translations - merged from per-page structure.
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 * Source: shared/ and pages/ directory structure
 */

import { websitePublicPs } from './website/public-ps';
import { websiteAdminPs } from './website/admin-ps';

import shared_common_ps from './shared/common/common.ps';
import shared_nav_ps from './shared/nav/nav.ps';
import shared_toast_ps from './shared/toast/toast.ps';
import shared_forms_ps from './shared/forms/forms.ps';
import shared_validation_ps from './shared/validation/validation.ps';
import shared_pagination_ps from './shared/pagination/pagination.ps';
import shared_ui_ps from './shared/ui/ui.ps';
import shared_errorBoundary_ps from './shared/errorBoundary/errorBoundary.ps';
import shared_notFound_ps from './shared/notFound/notFound.ps';
import shared_footer_ps from './shared/footer/footer.ps';
import shared_search_ps from './shared/search/search.ps';
import shared_privacyPolicy_ps from './shared/privacyPolicy/privacyPolicy.ps';
import shared_termsOfService_ps from './shared/termsOfService/termsOfService.ps';
import shared_resetPassword_ps from './shared/resetPassword/resetPassword.ps';
import pages_academic_ps from './pages/academic/academic.ps';
import pages_admissions_ps from './pages/admissions/admissions.ps';
import pages_activity_logs_ps from './pages/activity-logs/activityLogs.ps';
import pages_assets_ps from './pages/assets/assets.ps';
import pages_attendance_ps from './pages/attendance/attendance.ps';
import pages_auth_ps from './pages/auth/auth.ps';
import pages_certificates_ps from './pages/certificates/certificates.ps';
import pages_courses_ps from './pages/courses/courses.ps';
import pages_dashboard_ps from './pages/dashboard/dashboard.ps';
import pages_dms_ps from './pages/dms/dms.ps';
import pages_events_ps from './pages/events/events.ps';
import pages_exams_ps from './pages/exams/exams.ps';
import pages_fees_ps from './pages/fees/fees.ps';
import pages_finance_ps from './pages/finance/finance.ps';
import pages_grades_ps from './pages/grades/grades.ps';
import pages_guards_ps from './pages/guards/guards.ps';
import pages_help_center_ps from './pages/help-center/helpCenter.ps';
import pages_hostel_ps from './pages/hostel/hostel.ps';
import pages_id_cards_ps from './pages/id-cards/idCards.ps';
import pages_image_capture_ps from './pages/image-capture/imageCapture.ps';
import pages_leave_ps from './pages/leave/leave.ps';
import pages_library_ps from './pages/library/library.ps';
import pages_maintenance_ps from './pages/maintenance/maintenance.ps';
import pages_onboarding_ps from './pages/onboarding/onboarding.ps';
import pages_organizations_ps from './pages/organizations/organizations.ps';
import pages_permissions_ps from './pages/permissions/permissions.ps';
import pages_phone_book_ps from './pages/phone-book/phoneBook.ps';
import pages_profile_management_ps from './pages/profile-management/profileManagement.ps';
import pages_question_bank_ps from './pages/question-bank/questionBank.ps';
import pages_reports_ps from './pages/reports/reports.ps';
import pages_roles_ps from './pages/roles/roles.ps';
import pages_schools_ps from './pages/schools/schools.ps';
import pages_settings_ps from './pages/settings/settings.ps';
import pages_short_term_courses_ps from './pages/short-term-courses/shortTermCourses.ps';
import pages_staff_ps from './pages/staff/staff.ps';
import pages_student_report_ps from './pages/student-report/studentReport.ps';
import pages_students_ps from './pages/students/students.ps';
import pages_student_history_ps from './pages/student-history/studentHistory.ps';
import pages_subscription_ps from './pages/subscription/subscription.ps';
import pages_subjects_ps from './pages/subjects/subjects.ps';
import pages_teacher_subject_assignments_ps from './pages/teacher-subject-assignments/teacherSubjectAssignments.ps';
import pages_timetable_ps from './pages/timetable/timetable.ps';
import pages_user_management_ps from './pages/user-management/userManagement.ps';
import pages_user_permissions_ps from './pages/user-permissions/userPermissions.ps';
import pages_watermarks_ps from './pages/watermarks/watermarks.ps';
import pages_graduation_ps from './pages/graduation/graduation.ps';
import pages_website_admin_ps from './pages/website-admin/websiteAdmin.ps';
import pages_platform_ps from './pages/platform/platform.ps';
import pages_misc_ps from './pages/misc/misc.ps';

export const ps = {
  ...websitePublicPs,
  ...shared_common_ps,
  ...shared_nav_ps,
  ...shared_toast_ps,
  ...shared_forms_ps,
  ...shared_validation_ps,
  ...shared_pagination_ps,
  ...shared_ui_ps,
  ...shared_errorBoundary_ps,
  ...shared_notFound_ps,
  ...shared_footer_ps,
  ...shared_search_ps,
  ...shared_privacyPolicy_ps,
  ...shared_termsOfService_ps,
  ...shared_resetPassword_ps,
  ...pages_academic_ps,
  ...pages_admissions_ps,
  ...pages_activity_logs_ps,
  ...pages_assets_ps,
  ...pages_attendance_ps,
  ...pages_auth_ps,
  ...pages_certificates_ps,
  ...pages_courses_ps,
  ...pages_dashboard_ps,
  ...pages_dms_ps,
  ...pages_events_ps,
  ...pages_exams_ps,
  ...pages_fees_ps,
  ...pages_finance_ps,
  ...pages_grades_ps,
  ...pages_guards_ps,
  ...pages_help_center_ps,
  ...pages_hostel_ps,
  ...pages_id_cards_ps,
  ...pages_image_capture_ps,
  ...pages_leave_ps,
  ...pages_library_ps,
  ...pages_maintenance_ps,
  ...pages_onboarding_ps,
  ...pages_organizations_ps,
  ...pages_permissions_ps,
  ...pages_phone_book_ps,
  ...pages_profile_management_ps,
  ...pages_question_bank_ps,
  ...pages_reports_ps,
  ...pages_roles_ps,
  ...pages_schools_ps,
  ...pages_settings_ps,
  ...pages_short_term_courses_ps,
  ...pages_staff_ps,
  ...pages_student_report_ps,
  ...pages_students_ps,
  ...pages_student_history_ps,
  ...pages_subscription_ps,
  ...pages_subjects_ps,
  ...pages_teacher_subject_assignments_ps,
  ...pages_timetable_ps,
  ...pages_user_management_ps,
  ...pages_user_permissions_ps,
  ...pages_watermarks_ps,
  ...pages_graduation_ps,
  ...pages_website_admin_ps,
  ...pages_platform_ps,
  ...pages_misc_ps,
  websiteManager: websiteAdminPs.websiteManager,
  website: websiteAdminPs.website,
};
