/**
 * user-permissions page translations (ar).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  userPermissions: {
    title: "أذونات المستخدم",
    subtitle: "إدارة الأدوار والأذونات الفردية لمستخدمي النظام",
    accessDenied: "تم رفض الوصول",
    assignRole: "تعيين دور",
    assignSpecificPermissions: "تعيين أذونات محددة لهذا المستخدم",
    currentRoles: "الأدوار الحالية",
    directPermissions: "الأذونات المباشرة",
    directPermissionsDescription: "تعيين أذونات محددة مباشرة لهذا المستخدم (تتجاوز أذونات الدور)",
    failedToAssignRole: "فشل تعيين الدور",
    failedToRemoveRole: "فشل إزالة الدور",
    failedToUpdate: "فشل تحديث الأذونات",
    filterByRole: "تصفية حسب الدور",
    loadingPermissions: "جاري تحميل الأذونات...",
    loadingUserPermissions: "جاري تحميل أذونات المستخدم...",
    managePermissions: "إدارة الأذونات",
    managePermissionsDialogDescription: "تعيين الأدوار والأذونات المباشرة لهذا المستخدم",
    managePermissionsDialogTitle: "إدارة الأذونات لـ {name}",
    manageRolesDescription: "تعيين أو إزالة الأدوار لهذا المستخدم",
    managingUserPermissionsFor: "إدارة أذونات المستخدم لـ {name}",
    noEmail: "لا يوجد بريد إلكتروني",
    noName: "لا يوجد اسم",
    user: "المستخدم",
    noPermissionMessage: "ليس لديك إذن لإدارة أذونات المستخدم",
    noPermissionsAvailable: "لا توجد أذونات متاحة",
    noRolesAssigned: "لم يتم تعيين أي أدوار",
    permissionAssigned: "تم تعيين الإذن بنجاح",
    permissionFromRole: "الإذن من الدور",
    permissionRemoved: "تم حذف الإذن بنجاح",
    removeRoleConfirm: "هل أنت متأكد أنك تريد إزالة الدور \"{roleName}\" من هذا المستخدم؟",
    userRoles: "أدوار المستخدم",
    roleStaff: "الموظفون",
    roleAdmin: "المدير",
    roleTeacher: "المعلم",
    roleAccountant: "المحاسب",
    roleLibrarian: "أمين المكتبة",
    roleHostelManager: "مدير السكن",
    roleAssetManager: "مدير الأصول"
  }
};
