/**
 * user-permissions page translations (ps).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  userPermissions: {
    title: "د کاروونکي اجازې",
    subtitle: "د سیسټم کاروونکو لپاره رولونه او انفرادي اجازې اداره کړئ",
    accessDenied: "لاس رسی رد شو",
    assignRole: "رول وټاکئ",
    assignSpecificPermissions: "دې کاروونکي ته ځانګړې اجازې ورکړئ",
    currentRoles: "اوسني رولونه",
    directPermissions: "مستقیمې اجازې",
    directPermissionsDescription: "مستقیمې اجازې په ځانګړي ډول دې کارونکي ته ورکړئ (د رول اجازې له مینځه وړي)",
    failedToAssignRole: "د رول په ټاکلو کې پاتې راغلی",
    failedToRemoveRole: "د رول په لرې کولو کې پاتې راغلی",
    failedToUpdate: "د اجازو په تازه کولو کې پاتې راغلی",
    filterByRole: "د رول لخوا فلټر کړئ",
    loadingPermissions: "اجازې بارېږي...",
    loadingUserPermissions: "د کاروونکي اجازې بارېږي...",
    managePermissions: "اجازې اداره کړئ",
    managePermissionsDialogDescription: "دې کاروونکي ته رولونه او مستقیمې اجازې ورکړئ",
    managePermissionsDialogTitle: "د {name} لپاره اجازې اداره کړئ",
    manageRolesDescription: "دې کاروونکي لپاره رولونه وټاکئ یا لرې کړئ",
    managingUserPermissionsFor: "د {name} لپاره د کاروونکي اجازې اداره کول",
    noEmail: "بریښنالیک نشته",
    noName: "نوم نشته",
    user: "کاروونکی",
    noPermissionMessage: "تاسو د کاروونکي اجازو اداره کولو اجازه نلرئ",
    noPermissionsAvailable: "اجازې شتون نلري",
    noRolesAssigned: "رولونه نه دي ټاکل شوي",
    permissionAssigned: "اجازه په بریالیتوب سره ورکړل شوه",
    permissionFromRole: "د رول څخه اجازه",
    permissionRemoved: "اجازه په بریالیتوب سره لرې شوه",
    removeRoleConfirm: "ایا تاسو ډاډه یاست چې غواړئ د دې کاروونکي څخه \"{roleName}\" رول لرې کړئ؟",
    userRoles: "د کاروونکي رولونه",
    roleStaff: "کارمندان",
    roleAdmin: "مدیر",
    roleTeacher: "ښوونکی",
    roleAccountant: "محاسب",
    roleLibrarian: "کتابتونپوه",
    roleHostelManager: "لیلیه مدیر",
    roleAssetManager: "د شتمنۍ مدیر",
    searchPermissions: "د اجازې یا سرچینې له مخې لټون..."
  }
};
