/**
 * phone-book page translations (fa).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  phoneBook: {
    allEntries: "All Phone Book Entries",
    allEntriesDescription: "View all phone numbers from students, staff, donors, and guests",
    contactPerson: "Contact Person",
    donor: "Donor",
    donorContacts: "Donor Contacts",
    donorContactsDescription: "Phone numbers from all donors",
    donors: "Donors",
    guest: "Guest",
    guestCode: "Guest Code",
    guestContacts: "Guest Contacts",
    guestContactsDescription: "Phone numbers from event guests",
    guests: "Guests",
    relation: "Relation",
    staffContacts: "Staff Contacts",
    staffContactsDescription: "Phone numbers from all staff members",
    student: "Student",
    studentContacts: "Student Contacts",
    studentContactsDescription: "Phone numbers from student guardians, emergency contacts, and zamin",
    studentEmergency: "Student Emergency",
    studentGuardian: "Student Guardian",
    studentZamin: "Student Zamin"
  }
};
