/**
 * phone-book page translations (ps).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  phoneBook: {
    allEntries: "د اړیکو ټول لیست",
    allEntriesDescription: "د زده کوونکو، کارکوونکو، تمویلونکو او میلمنو ټولې شمېرې وګورئ",
    contactPerson: "د اړیکې کس",
    donor: "تمویلونکی",
    donorContacts: "د تمویلونکو اړیکې",
    donorContactsDescription: "د ټولو تمویلونکو شمېرې",
    donors: "تمویلونکي",
    guest: "میلمه",
    guestCode: "د میلمه کوډ",
    guestContacts: "د میلمنو اړیکې",
    guestContactsDescription: "د پروګرام د میلمنو شمېرې",
    guests: "میلمانه",
    relation: "اړیکه / خپلوي",
    staffContacts: "د کارکوونکو اړیکې",
    staffContactsDescription: "د ټولو کارکوونکو شمېرې",
    student: "زده کوونکی",
    studentContacts: "د زده کوونکو اړیکې",
    studentContactsDescription: "د زده کوونکو د سرپرستانو، بیړنیو اړیکو او ضامنانو شمېرې",
    studentEmergency: "بیړنۍ اړیکه",
    studentGuardian: "سرپرست",
    studentZamin: "ضامن"
  }
};
