/**
 * phone-book page translations (ar).
 * Auto-generated by: scripts/i18n/migrate-to-page-structure.ts
 */

export default {
  phoneBook: {
    allEntries: "جميع دليل الهاتف",
    allEntriesDescription: "عرض جميع أرقام الهواتف من الطلاب والموظفين والمتبرعين والضيوف",
    contactPerson: "جهة الاتصال",
    donor: "متبرع",
    donorContacts: "جهات اتصال المتبرعين",
    donorContactsDescription: "أرقام هواتف جميع المتبرعين",
    donors: "المتبرعون",
    guest: "ضيف",
    guestCode: "رمز الضيف",
    guestContacts: "جهات اتصال الضيوف",
    guestContactsDescription: "أرقام هواتف ضيوف الفعاليات",
    guests: "الضيوف",
    relation: "العلاقة",
    staffContacts: "جهات اتصال الموظفين",
    staffContactsDescription: "أرقام هواتف جميع الموظفين",
    student: "طالب",
    studentContacts: "جهات اتصال الطلاب",
    studentContactsDescription: "أرقام هواتف أولياء الأمور وجهات الاتصال للطوارئ والكفلاء للطلاب",
    studentEmergency: "طوارئ الطالب",
    studentGuardian: "ولي أمر الطالب",
    studentZamin: "كفيل الطالب"
  }
};
