// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';


const SUPABASE_URL = 'https://wkrzoelctjwpiwdswmdj.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndrcnpvZWxjdGp3cGl3ZHN3bWRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3Mzk0MTEsImV4cCI6MjA2ODMxNTQxMX0.IKuOqZlXNCdCW5aacYzSB71hqIeB6KB9kCuCbERMzb0';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
